### ISSUE TITLE
What files should I grab in some versions? (v0.1.0~v0.1.6)

### ISSUE THREAD

**Issue by nolsherry** [mwilliamson/mammoth.js#100]
Hi @mwilliamson , 
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs/) project,
and we want to host this library, 
However I have some problems,
I downloaded the library from [npm](https://www.npmjs.com/package/mammoth), 
and I wanted to grab `mammoth.browser.js` and `mammoth.browser.min.js`, 
but I found that there are not the two files in the versions between `v0.1.0` with `v0.1.6`,
What files should I grab in those versions? Thanks!

cdnjs/cdnjs#9168

**Comment by mwilliamson** [comment]
In the past, browser builds weren't included in the published npm packages. If those files aren't there, then there aren't pre-built browser files available for that version. In fact, I probably wouldn't include any browser builds before 1.0.3, when the generation of browser builds was enforced as a prepublish step.

**Comment by nolsherry** [comment]
Thanks @mwilliamson , maybe we can ignore these versions. What do you think?

**Comment by mwilliamson** [comment]
From my point of view, the more versions you ignore, the better.

**Comment by mwilliamson** [comment]
By which I mean: I don't suppose old versions, so I'd prefer not to encourage people to use them.

**Comment by mwilliamson** [comment]
Closing since I think the question is answered, feel free to disagree through.
