### ISSUE TITLE
Mammoth is not creating tables in its Markdown output

### ISSUE THREAD

**Issue by NickGeek** [mwilliamson/mammoth.js#103]
In most applications of markdown a table can be created like so:

````
| Test | Another test|
|--|--|
|More test code|Even more test code|
|Another row|etc|
````

Producing:

| Test | Another test|
|--|--|
|More test code|Even more test code|
|Another row|etc|

**Comment by mwilliamson** [comment]
Markdown support is fairly rudimentary. In retrospect, a better
approach would probably have been to just use an existing HTML to
Markdown converter (either directly in the source, or as a
recommendation in the docs).

In any case: I'm unlikely to work on this any time soon, so patches
with tests welcome. But I suspect you'll get the best results by
converting to HTML, and then converting that to Markdown using another
tool.

**Comment by mwilliamson** [comment]
Closing since Markdown support is deprecated.
