### ISSUE TITLE
React js parsing word docx file to html using mammoth

### ISSUE THREAD

**Issue by zeal29gdd** [mwilliamson/mammoth.js#105]
![screenshot from 2016-12-28 14 46 21](https://cloud.githubusercontent.com/assets/12289959/21515638/75e16946-cd0c-11e6-8fa6-6cde33426d6f.png)

**Comment by mwilliamson** [comment]
Could you post the code that you're using to invoke Mammoth? Note that, in the browser, the invocation should be something like:

```javascript
mammoth.convertToHtml({arrayBuffer: arrayBuffer})
```

**Comment by zeal29gdd** [comment]
![screenshot from 2016-12-28 23 19 29](https://cloud.githubusercontent.com/assets/12289959/21524847/39be7218-cd54-11e6-8384-63eefbe648d1.png)

**Comment by mwilliamson** [comment]
As I said, when using Mammoth in the browser, you should be passing an array buffer to `convertToHtml`, not a path.

**Comment by zeal29gdd** [comment]
thanks :+1:

**Comment by sunkanmii** [comment]
So where do we include the file itself? I'm confused.
