### ISSUE TITLE
mammoth used in a Office Add-in for Word doesn't see images 

### ISSUE THREAD

**Issue by constantinrosu** [mwilliamson/mammoth.js#108]
Tested with Win7x64 and Win10x64.

Steps to reproduce the issue:

SETTING UP
1. If you do not have already installed Git, please go to https://git-scm.com/download/win and install it
2. If you do not have NodeJS installed then go to: https://nodejs.org/en/ , get V6.9.4 LTS and install it.
3. Create a TempFolder like C:\TempOfficeAddIn
4. Open CMD and got to C:\TempOfficeAddIn
5. run "npm install -g tsd bower gulp"
6. copy the folder MyAddInSite within the zip file "MyAddInSite.zip" to the C:\TempOfficeAddIn
7. run "gulp serve-static"
8. you should now be able to access: https://localhost:8443/app/home/home.html
9. copy the file "onlineFile.1.docx" I sent you, in your OneDrive

TO TEST ONLINE
1. go to office.com, and sign in with your account
2. choose Word
3. Open in browser from your online drive the file
4. Click on "Edit Document" and choose "Edit in Browser"
5. Click on "Insert" menu, 
	then on "Office Add-Ins", 
	then on "Upload My Add-in", 
	browse for C:\TempOfficeAddIn\MyAddInSite\manifest-my-office-project.xml, 
	then click "Upload"
6. you should now see in the right side the add-in loaded.
7. open the dev tools (F12) - I use Chrome,  click on Console and cler the console history
8. click on "GetHtml" button and wait about 5-6 seconds, you will see the "result" object received from mammoth in the console. The HTML is generated without any image...

Because Word for desktop is working only with registered Add-in, I cannot give you details on how to test it on Desktop version (which seems to work fine on my side).

If you need any other details, please let me know.

[onlineFile(1).docx](https://github.com/mwilliamson/mammoth.js/files/724577/onlineFile.1.docx)
[MyAddInSite.zip](https://github.com/mwilliamson/mammoth.js/files/724579/MyAddInSite.zip)

**Comment by mwilliamson** [comment]
Could try the latest version and see if the problem persists?

**Comment by constantinrosu** [comment]
Sure,

**Comment by constantinrosu** [comment]
So far so good!
