### ISSUE TITLE
Support for color property

### ISSUE THREAD

**Issue by ShawnLin013** [mwilliamson/mammoth.js#109]
It seems that the color property could not convert from docx.
`<span style="#ff0000">red</span>` or `<font color="#ff0000">red</font>`
But just found another library that fork from you could.(https://github.com/sbabushkin/mammoth-colors.js)
Thanks for sharing this amazing library. 😍

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't copy the exact formatting of the document. The idea is that you'd use styles to semantically mark up your document instead. I wouldn't be opposed to adding colours to the document AST for use in transforms though.

**Comment by takuy** [comment]
I'd really prefer if this did colors. The use case of where I use mammoth doesn't give me control over what users upload. The docx files are just transformed into HTML for viewing. If there were at least a flag or option for colors or other similar formatting, that'd be great.

**Comment by mwilliamson** [comment]
Closing since I think this is covered by #57.

**Comment by rohitkhadatkar** [comment]
Hello All, If someone wants to turn-on add color formatting in mammoth then how can we do?

**Comment by mahendra119** [comment]
Plugin Maker did not provided any text color parsing. but i have changed some code inside this package to get color parsing work. I am using version 1.4.6
go to mammoth/lib/documents.js and update this code
function Run(children, properties) {
    properties = properties || {};
    return {
        type: types.run,
        children: children,
        styleId: properties.styleId || null,
        styleName: properties.styleName || null,
        isBold: properties.isBold,
        isUnderline: properties.isUnderline,
        isItalic: properties.isItalic,
        isStrikethrough: properties.isStrikethrough,
        isSmallCaps: properties.isSmallCaps,
        verticalAlignment: properties.verticalAlignment || verticalAlignment.baseline,
        font: properties.font || null,
        color: properties.color
    };
}
I have added only last line for color property

go to mammoth/lib/document-to-html.js and find convertRun function and add these lines-
if (run.color) {
            paths.push(htmlPaths.element('span', {color : run.color}, {fresh: false}));
        }
i have added span tag here but you can add any tag.

Next, go to mammoth/lib/docx/body-reader.js and find readRunProperties function and add this line-
color: element.firstOrEmpty("w:color").attributes["w:val"]

And that's it. you will get final result like this after parsing
<span color="FF0000">Hello</span>
but we know this is not valid so we need to convert it in valid CSS like below
(result).replace(/color="/g, 'style="color:#');

I didn't got any support for background-color. 
hopefully plugin maker will provide support for this in next version and give an option whether user want to turn on color parsing or not, instead of disabling by default.

**Comment by rohitkhadatkar** [comment]
Thank you so much @mahendra119. This will very helpful.

**Comment by frantwo** [comment]
Hello!! First at all, thank you very much for this parser. It is very useful!! Congratulations team!!

**Comment by frantwo** [comment]
Sorry! 
Already I understood myself! jejejeje I did it.

**Comment by bigiCrab** [comment]
By imitate @mahendra119 solution,
found out how to convert highlight(bg-color, I think is same)

> btw, in my workflow i dont want to convert css by hand.
> so i made some change for conver color. 

mammoth/lib/documents.js in function Run()
```
color: properties.color ? '#' + properties.color : null,
highlight: properties.highlight ? properties.highlight : null
```
mammoth/lib/document-to-html.js in function convertRun()
```
if (run.color) {
    paths.push(htmlPaths.element('font', {color : run.color}, {fresh: false}));
}
if (run.highlight) {
// i think set attr by style might cause some issue.
    paths.push(htmlPaths.element('mark', {'style' : 'background-color:' + run.highlight}, {fresh: false}));
}
```
mammoth/lib/docx/body-reader.js in function readRunProperties()
```
color: element.firstOrEmpty("w:color").attributes["w:val"],
highlight: element.firstOrEmpty("w:highlight").attributes["w:val"],
```

**Comment by frantwo** [comment]
Thank you very much!!!

**Comment by re54k** [comment]
Following @bigiCrab, to convert "Shading" (much as highlight):

mammoth/lib/documents.js in function Run()

``` js
color: properties.color ? '#' + properties.color : null,
highlight: properties.highlight ? properties.highlight : null,
shading: properties.shading ? '#' + properties.shading : null
```
mammoth/lib/document-to-html.js in function convertRun()

```
if (run.color) {
    paths.push(htmlPaths.element('font', {color : run.color}, {fresh: false}));
}
if (run.highlight) {
// i think set attr by style might cause some issue.
    paths.push(htmlPaths.element('mark', {'style' : 'background-color:' + run.highlight}, {fresh: false}));
}
if (run.shading) {
    paths.push(htmlPaths.element('mark', {style : "background-color:" + run.shading}, {fresh: false}));
}
```
mammoth/lib/docx/body-reader.js in function readRunProperties()

```
color: element.firstOrEmpty("w:color").attributes["w:val"],
highlight: element.firstOrEmpty("w:highlight").attributes["w:val"],
shading: element.firstOrEmpty("w:shd").attributes["w:fill"]
```

**Comment by ahsanshakil9700** [comment]
> 

Does this work? I am trying this in mammoth-patching but this does not seem to work
