### ISSUE TITLE
Getting a warning about Promise.defer being deprecated

### ISSUE THREAD

**Issue by admehta01** [mwilliamson/mammoth.js#113]
`Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.`

Getting this warning when executing `convertToHtml`, with the following setup:
- Windows 10
- Node v6.9.4
- Mammoth 1.3.3

**Comment by mwilliamson** [comment]
`defer()` is now polyfilled as of `fb1bff7`.

**Comment by mwilliamson** [comment]
Perhaps also worth noting that I was only able to see the error when `NODE_ENV` was set to `development`.
