### ISSUE TITLE
Feature Request: Support for Content Control

### ISSUE THREAD

**Issue by ash47** [mwilliamson/mammoth.js#115]
Mammoth.js does not parse content control fields.

Content control fields such as text restrictions and drop down fields are ignored.

Minimal word document:
https://mega.nz/#!OwdDQCjC!rweo_5fgoQzyaR-a0zHgxcvTt-Rq4zgATBZD0kU8Edk

![What the document looks like](http://i.imgur.com/USNLDO5.png)

Content Control Fields can be accessed via the developer ribbon.
![Developer Tools](http://i.imgur.com/vWhGbZY.png)

**Comment by mwilliamson** [comment]
What behaviour are you expecting? So far as I can tell, Mammoth is displaying the content of the SDT block correctly.

**Comment by ash47** [comment]
I've just gone ahead and updated my Mammoth, I was using an old NPM version, and these functionality has already been implemented.

I apologise for wasting your time. Thanks a lot for all your hard work, this project is impressive.
