### ISSUE TITLE
Adding class to table tag in html

### ISSUE THREAD

**Issue by espindl** [mwilliamson/mammoth.js#116]
I am trying to add a styleMap for tables: `"tbl => table.table"`
This is for adding all the tables a class: `<table class="table">`
I couldn't do it. Isn't it the <w:tbl> that is converted to <table> tag?

**Comment by mwilliamson** [comment]
On Wed, 03 May 2017 05:08:42 -0700
espindl <notifications@github.com> wrote:

> I am trying to add a styleMap for tables: "tbl => table.table"
> This is for adding all the tables a class: <table class="table">
> I couldn't do it. Isn't it the <w:tbl> that is converted to <table>
> tag?

Style maps don't currently support tables, so there's no way to
directly set the class on tables. Your best bet to get something
working right now is probably to post-process the output i.e. add the
class to the tables in the resulting HTML.

**Comment by mwilliamson** [comment]
Table style mappings are now supported as of 1.4.3.
