### ISSUE TITLE
Link hash disappears

### ISSUE THREAD

**Issue by leomastoras** [mwilliamson/mammoth.js#117]
I have a word document with a link that points to

https://www.test.com/test.html#testhash

and after the conversion to html the hash (#testhash) is removed

is there any way to prevent this from happening?

**Comment by mwilliamson** [comment]
Could you provide a minimal example document?

**Comment by leomastoras** [comment]
[Link.docx](https://github.com/mwilliamson/mammoth.js/files/1010545/Link.docx)

this document has a link that points to https://www.test.com/test.html#hashtest

after the conversion the #hashtest information is lost

**Comment by mwilliamson** [comment]
Hmm, looks like both the `r:id` and `w:anchor` attributes are set. According to the spec:

> If a hyperlink target is also specified using the `r:id` attribute, then this attribute [`w:anchor`] shall be ignored.

Evidently, that's not what's happening here though. Just to check: did you use Microsoft Word or something else to make the document?

**Comment by leomastoras** [comment]
i used ms word 2010 yes

**Comment by mwilliamson** [comment]
The latest commit on master should now handle fragments. Could you give it a try?

**Comment by leomastoras** [comment]
yes it now works very well thanks a lot for the swift resolve

**Comment by mwilliamson** [comment]
Glad to hear it works.
