### ISSUE TITLE
Support w:nonBreakingHyphen

### ISSUE THREAD

**Issue by leomastoras** [mwilliamson/mammoth.js#119]
[testhyphen.docx](https://github.com/mwilliamson/mammoth.js/files/1061093/testhyphen.docx)

Hello again,

I have encountered a strange document (see attachment) that included this weird character that looked like a dash but it isn't. I opened the xml and it seems that the character is an element <w:noBreakHyphen /> and it looks like a dash. Is it possible to convert this character to a real dash or at least pass something over to the tree because it is getting lost at the moment with no warning message.

Thanks in advance

**Comment by leomastoras** [comment]
@update 
in case anyone has the same issue i was able to tackle it by adding the following code

        "w:noBreakHyphen": function(element) {
            return elementResult(new documents.Text('\u2011'));
        },

to the body-readers.js under the xmlElementReaders object
not sure if this is correct but this solution works for me

**Comment by mwilliamson** [comment]
Thanks for the issue. This should be supported in 1.4.1. Let me know if that's not the case.
