### ISSUE TITLE
Warning: An unrecognised element was ignored: v:group

### ISSUE THREAD

**Issue by preciousjoyb** [mwilliamson/mammoth.js#120]
Hi William,
Good day!  

I really love but I have an issue.  Hope you respond asap.  I really need help.  Thank you so much!

I encounter this issue, I grouped images in the Microsoft Word document but, those group images doesn't displayed in mammoth converter.  And these messages displays.
Warning: An unrecognised element was ignored: v:group
Warning: Unrecognised paragraph style: 'Note' (Style ID: Note)
Thank you for your reply.

I'm using Wordpress 4.8
Browser: Chrome

Best Regards,
Precious

**Comment by mwilliamson** [comment]
Could you provide a minimal example document?

**Comment by preciousjoyb** [comment]
Hi Michael,

Thank you for replying.  Please this video screenshot I've made.
https://screencast-o-matic.com/watch/cbilbtlYxw

Precious

**Comment by mwilliamson** [comment]
Thanks for the video, unfortunately I'll need an actual document to look at, so if you could provide a minimal example document that'd be helpful.

**Comment by preciousjoyb** [comment]
here..

**Comment by mwilliamson** [comment]
I'm afraid I'm not seeing a document. You might need to attach it by leaving a comment through the website rather than sending it as an e-mail.

**Comment by preciousjoyb** [comment]
[1 Getting started with connections.docx](https://github.com/mwilliamson/mammoth.js/files/1144991/1.Getting.started.with.connections.docx)

**Comment by mwilliamson** [comment]
The latest version of Mammoth now reads the children of `v:group` elements, so the images should show up. However, they will be rendered one after the other rather than being overlaid since the layout information is non-trivial to parse from the document. Specifically, from a quick glance, it looks like it would require some CSS (or CSS-like) attributes to work out the positioning of elements:

```
              <v:group w14:anchorId="67710F6D" id="Group 1" o:spid="_x0000_s1026" style="position:absolute;margin-left:19.95pt;margin-top:.6pt;width:393.7pt;height:44.45pt;z-index:251674624" coordsize="49999,5645" o:gfxdata="(snipped)">
                <v:shapetype id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
                  <v:stroke joinstyle="miter"/>
                  <v:formulas>
                    <v:f eqn="if lineDrawn pixelLineWidth 0"/>
                    <v:f eqn="sum @0 1 0"/>
                    <v:f eqn="sum 0 0 @1"/>
                    <v:f eqn="prod @2 1 2"/>
                    <v:f eqn="prod @3 21600 pixelWidth"/>
                    <v:f eqn="prod @3 21600 pixelHeight"/>
                    <v:f eqn="sum @0 0 1"/>
                    <v:f eqn="prod @6 1 2"/>
                    <v:f eqn="prod @7 21600 pixelWidth"/>
                    <v:f eqn="sum @8 21600 0"/>
                    <v:f eqn="prod @7 21600 pixelHeight"/>
                    <v:f eqn="sum @10 21600 0"/>
                  </v:formulas>
                  <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
                  <o:lock v:ext="edit" aspectratio="t"/>
                </v:shapetype>
                <v:shape id="Picture 31" o:spid="_x0000_s1027" type="#_x0000_t75" style="position:absolute;width:49999;height:5645;visibility:visible;mso-wrap-style:square" o:gfxdata="(snipped)">
                  <v:imagedata r:id="rId8" o:title=""/>
                  <v:path arrowok="t"/>
                </v:shape>
                <v:shape id="Picture 173" o:spid="_x0000_s1028" type="#_x0000_t75" alt="mouse-cursor-handcursor-hand-clip-art---vector-clip-art-online-royalty-free-gdk4nrze" style="position:absolute;left:235
13;top:2458;width:2387;height:3182;visibility:visible;mso-wrap-style:square" o:gfxdata="(snipped)">
                  <v:imagedata r:id="rId9" o:title="mouse-cursor-handcursor-hand-clip-art---vector-clip-art-online-royalty-free-gdk4nrze"/>
                  <v:path arrowok="t"/>
                </v:shape>
                <w10:wrap type="square"/>
              </v:group>
```

**Comment by preciousjoyb** [comment]
HI Michael, when can we fix this? I still can see the same issue.  Please help.  Thanks!

**Comment by mwilliamson** [comment]
Could you check which version of Mammoth you're running? When I try the
example document you provided, the images appear in the output.

To clarify: you're saying the images don't appear, and you still get
the warning that v:group was ignored?

**Comment by preciousjoyb** [comment]
version 1.6.0

**Comment by mwilliamson** [comment]
The latest version of Mammoth is 1.4.2, so I'm not sure how you have 1.6.0 installed. How are you checking the version?

Could you clarify whether you're still getting the warning that `v:group` was ignored, and what output you're getting?

**Comment by preciousjoyb** [comment]
I got it from google ill send you screenshot

**Comment by preciousjoyb** [comment]
![mammoth](https://user-images.githubusercontent.com/30124462/28320759-0466608a-6b97-11e7-82dd-f9b366d486fb.png)

**Comment by preciousjoyb** [comment]
please check the screenshot.  My downloaded mammoth is version 1.6.0.  Where can I get the 1.4.2?

**Comment by mwilliamson** [comment]
Ah right, you're using the WordPress plugin, not the JavaScript library directly (this is the repository for the JavaScript plugin). I'll update the WordPress plugin when I get a chance.

**Comment by preciousjoyb** [comment]
Thank you so much! Please update me asap.  We will wait for it.  We love
mammoth.

On Jul 19, 2017 1:16 AM, "Michael Williamson" <notifications@github.com>
wrote:

Ah right, you're using the WordPress plugin, not the JavaScript library
directly (this is the repository for the JavaScript plugin). I'll update
the WordPress plugin when I get a chance.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mwilliamson/mammoth.js/issues/120#issuecomment-316133687>,
or mute the thread

**Comment by mwilliamson** [comment]
Could you try the latest version (1.7.0) of the plugin?

**Comment by preciousjoyb** [comment]
Hi MIchael,
Good day!
I still see that the arrows still doesn't group.  and it is unable to move to the specific location that I want to put.
Please check the screenshot video.  Thanks! https://screencast-o-matic.com/watch/cbiYbultgK

**Comment by mwilliamson** [comment]
It looks like the behaviour is working as expected, since I believe the images are now appearing? As I said, getting the images to overlay is non-trivial due to having to parse the attributes that control the positioning, so is unlikely to be supported. Mammoth doesn't change the editor itself, so being able to move the image feels like an issue separate to Mammoth.

My suggestion would be to create a single image in the document, rather than overlaying one image on top of the other.

**Comment by preciousjoyb** [comment]
Ok noted.  Thanks Michael!

**Comment by preciousjoyb** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/c639fc460e",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Precious is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
