### ISSUE TITLE
How can I centre a paragraph?

### ISSUE THREAD

**Issue by Rocketman21** [mwilliamson/mammoth.js#130]
I tried various things with style map, but can't figure out how exactly should I use it.
I know that there is alignment property in the docx's xml, which is something like `<w:jc w:val="center"/>`
And I tried to do it like 

> p[style-name=^'center'] => center
> p[style-name='jc center'] => center
> p[style-name='alignment center'] => center
> center => center

and much more, but can't make it working :(
Help me please!

**Comment by mwilliamson** [comment]
Mammoth uses styles rather than the specific formatting applied to runs of text. You'll need to apply a named style in Word that centres the text, and then map that Word style to the appropriate HTML.

**Comment by Rocketman21** [comment]
Ok, so how to apply a named style in this case?

**Comment by mwilliamson** [comment]
I'd suggest looking for some guides on how to use styles in Word if you're not familiar with them. For instance: https://support.office.com/en-gb/article/Using-Styles-in-Word-9db4c0f4-2754-4294-9758-c14a0abd8cfa

**Comment by mwilliamson** [comment]
Closing since either named styles or document transforms should be able to support this case.
