### ISSUE TITLE
Auto Add page Break after fixed height like A4 page , Letter

### ISSUE THREAD

**Issue by jinbullsushil** [mwilliamson/mammoth.js#133]
Hi ,

Auto Add page Break after fixed height like an A4 page, Letter.

I want to add page break when an A4 paper size end, next page auto start.

**Comment by mwilliamson** [comment]
Working out where the page breaks is non-trivial -- even full-blown office suites such as different versions of Word and LibreOffice sometimes disagree, and it also depends on other factors such as the fonts installed on the local system. As such, I don't think this is something that can be sensibly added into Mammoth. Using document transforms or manipulating the HTML that Mammoth produces seems like the best option.
