### ISSUE TITLE
Caption not supported

### ISSUE THREAD

**Issue by oninross** [mwilliamson/mammoth.js#134]
Captions from images are not supported

`[ { type: 'warning', message: 'Unrecognised paragraph style: \'caption\' (Style ID: Caption)' } ]`

**Comment by mwilliamson** [comment]
An example document, the HTML you're getting and the HTML you expect would be useful.

In this case, it just looks like there's no paragraph style for captions, but they should still be showing up. Is this the case? If you want to apply specific styles, then you can add them in the style map.

**Comment by oninross** [comment]
Sorry for the vague description.  But yeah, I attached a caption to an image and I received that warning.  Its still generating as a paragraph.  I'll check out the style map.  Thank you!

**Comment by oninross** [comment]
yes! works with custom style mapping.  You just have to use convertToHtml.  Can I suggest that you upgrade or recompose your documentation so that we know that we should be using convertToHtml and we can use classnames as well.  The code below actually works pretty well:

`
{
    styleMap: [
        "p[style-name='Image With Caption'] => div.image-with-caption",
        "p[style-name='Caption'] => div.image-with-caption > span.caption",
        "p[style-name='Quote'] => blockquote > p:fresh"
    ]
}
`

**Comment by mwilliamson** [comment]
I'm not sure I follow. Style maps are supported by both the CLI and the
API, and both are documented in the README. The allowed style mappings
are described in their own section.

**Comment by oninross** [comment]
Yes it is documented in the README.  But the documentation seems so short and broad that I had to do some trial and error and looked at the past issues for ideas of how to do it.
