### ISSUE TITLE
how to output html  

### ISSUE THREAD

**Issue by zhaoxueyin000** [mwilliamson/mammoth.js#135]
![image](https://user-images.githubusercontent.com/17424860/32529879-f8835ab0-c475-11e7-8d74-c1f005cd1fda.png)
When I run my code,I happened to got o mistake.This is my code.How can I resolve it,and output html?
![image](https://user-images.githubusercontent.com/17424860/32529973-7ca0062c-c476-11e7-9dc9-1c62a96c016b.png)
`gulp.task('docxToHtml',` function() {
        `return gulp.src([`doc/**/*.docx`])
           `.pipe(mammoth.convertToHtml({
                    `path: "doc/ksrcbDepository.docx"
                 `})
                `.then(function(result) {
                    `var html = result.value;
                    `var messages = result.messages;
               ` })
               ` .done())
           ` .pipe(gulp.dest('doc/'));

   ` });

**Comment by mwilliamson** [comment]
The result of `convertToHtml` isn't a stream, so you can't just pass it into `pipe()` (which I believe expects a stream with an `on` method, hence the error you're seeing). I'm not particularly familiar with gulp, so I'm not sure what the correct approach is.
