### ISSUE TITLE
Indented text doesn't work

### ISSUE THREAD

**Issue by JohnMcLear** [mwilliamson/mammoth.js#137]
To replicate:

Opening Microsoft Word, make document contents:
```
hello
world
```

Click at the beginning of the line "world"
Click indent button on the toolbar

Run document through mammoth (cli is fine too)

output is 

```
<p>hello</p>
<p>world</p>
```

Expected is..
```
<p>hello</p>
<p class='indent1'>world</p>
```

or some such.

I grep'd through the source code and it appears indent should be supported but I can't find anything useful.

**Tabbed indentation works great.**

Any thoughts?

Further notes to self as I debug..  I can reference the output that can be created using this as a ref:
https://github.com/mwilliamson/mammoth.js/issues/24

This should give me further insights to how mammoth is treating indented items.

**Comment by mwilliamson** [comment]
Mammoth doesn't currently have any explicit support for indentation. As with other formatting, the suggested approach is to use explicit styles instead. There's already [a pull request](https://github.com/mwilliamson/mammoth.js/pull/132) to add indentation to the parser so they can be used in document transforms.
