### ISSUE TITLE
Get the docx file from a local address (ex: ~abc/abc/...) and turn it into an array buffer?

### ISSUE THREAD

**Issue by hnguyen48206** [mwilliamson/mammoth.js#141]
Dear Mr,

I also have the same problem using mammoth.js in the browser. May I know how to get the docx file from a localhost address (ex: ~content/abc/test.docx) and turn it into an array buffer which is the only thing that mammoth would accept as a valid input?

Best Regards.

**Comment by mwilliamson** [comment]
Client-side code isn't allowed to access arbitrary local files. You'll need to use a file input element, as in the browser demo: https://github.com/mwilliamson/mammoth.js/blob/master/browser-demo/demo.js
