### ISSUE TITLE
warning - "An unrecognised element was ignored: v:rect"

### ISSUE THREAD

**Issue by coffeepy** [mwilliamson/mammoth.js#142]
Hello im getting the following warning:

`[{"type":"warning","message":"An unrecognised element was ignored: v:rect"}]`

Any way to add support to v:rect and its text inside? Or perhaps a workaround?

Example:
[test.docx](https://github.com/mwilliamson/mammoth.js/files/1590318/test.docx)

Windows 10 Home
Node.js v9.2.0

**Comment by mwilliamson** [comment]
Thanks for the document, I'll take a look when I get a chance, although
I've no idea when that will be.

**Comment by coffeepy** [comment]
Thanks! It would be a huge help if you can add support. Appreciate it.

**Comment by frnd** [comment]
Hello, I have added a fast fix for this issue. I hope it helps.

**Comment by mwilliamson** [comment]
This should be fixed in the latest version, 1.4.5. Feel free to reopen if that turns out not to be the case.
