### ISSUE TITLE
MsWord Symbols

### ISSUE THREAD

**Issue by edfora-infotech** [mwilliamson/mammoth.js#144]
#143 
This to handle MsWord symbols, if your symbols are not getting converted, add the Unicode in the symbolsToUnicode.json file

**Comment by anaghakomawar** [comment]
Hello edfora-infotech,

Can you please help me how to do it. As I am new to meteor react. I am not able to get it.

Thanks in advance

**Comment by abishek28007** [comment]
@iAssureIT the pr for symbol was not merged

**Comment by mwilliamson** [comment]
Symbols should now be supported for a subset of fonts (Symbol, Webdings, Wingdings, Wingdings 2 and Windings 3).
