### ISSUE TITLE
Breaks on docx from Word Online

### ISSUE THREAD

**Issue by johnestes4** [mwilliamson/mammoth.js#145]
I'm using Mammoth to extract raw text from docxs and I get a fatal error whenever a docx from Word Online is used, telling me it can't find the document.xml file. I opened up one of those files to see, and it looks like Word Online saves that data in a file called document2.xml for some reason. Could it be set up to check for those as well?

I attached a file that you can use to verify.

[breakmammoth.docx](https://github.com/mwilliamson/mammoth.js/files/1636510/breakmammoth.docx)

**Comment by mwilliamson** [comment]
Thanks for providing the file. Could you try using the latest version on `master` to see if that fixes the issue?

There are a few other places that use hard-coded paths inside the ZIP file where it should instead be reading the relationship targets, but let's see if this fixes the issue for the main document file first.

**Comment by johnestes4** [comment]
I updated to the latest version and I'm still getting the same error.

**Comment by mwilliamson** [comment]
Hmm, that's odd. When I try it myself using the file you've provided,
it seems to work. Are you using that same file to test it?

Can I just check that you're using the latest commit from master,
rather than a version from npm?

**Comment by johnestes4** [comment]
OK, I just tried to update from npm before. I downloaded the new commit directly from github and now it works, thanks!

**Comment by mwilliamson** [comment]
This should be fixed in 1.4.4. Feel free to shout if this turns out not to be the case.
