### ISSUE TITLE
Feature request: Upgrade jszip to v3.x

### ISSUE THREAD

**Issue by anthony-o** [mwilliamson/mammoth.js#148]
I'm using v3.x of [Stuk/jszip](https://github.com/Stuk/jszip) and it seems that it interfere with the 2.x version used by `mammoth.js`: when using `extractRawText` API, I have the following error:

    Error: Uncaught (in promise): Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.

And the error point is here: https://github.com/mwilliamson/mammoth.js/blob/8b9ca6ca68fec89926cfb02a96506bbee54a5b2c/lib/zipfile.js#L10

Do you think there is a way for `mammoth.js` to use v3.x version of jszip?

**Comment by mwilliamson** [comment]
If you're using npm, then Mammoth should get a separate copy of jszip that satisfies its own dependencies. If that's not the case, then it sounds like something's gone wrong with the installation.

**Comment by anthony-o** [comment]
Thanks for your quick answer @mwilliamson .
Yes I'm using `npm` and here is an extract from my `dependencies` section:
```json
    "@types/jszip": "~3.1.3",
    "jszip3": "~3.1.5",
    "mammoth": "~1.4.4",
```
I'm using Ionic 3 which uses Angular 5 & TypeScript by default... perhaps it is linked to this?

**Comment by mwilliamson** [comment]
And I assume that Mammoth doesn't have its own copy of jszip in its `node_modules` directory? Have you tried running `npm install`? Does npm think all of the dependencies are satisfied?

I'm not familiar with Ionic 3. Are you getting this issue when running in node, or after bundling? It could be that the bundler isn't resolving dependencies correctly.

**Comment by anthony-o** [comment]
It's strange because I installed my packages with `npm install` and I've checked that `mammoth` had its own 2.x version of jszip in its own `node_modules` but in my browser, it seems that when `mammoth` tries to use `JSZip`, it uses "my" 3.x version anyways...

It seems that Ionic 3 which uses Angular 5 uses webpack, could it cause any problem here?

**Comment by mwilliamson** [comment]
I'm afraid I've no idea, I'm no webpack expert.

**Comment by anthony-o** [comment]
OK really weird, it is caused by webpack configuration bundled with Ionic.
So I had to follow [this SO hint](https://stackoverflow.com/a/42290843/535203) in order to create my own `webpack.config.js` configuration by copying from `node_modules/@ionic/app-scripts/config/webpack.config`, declare it in the `package.json`, and modify the `webpack.config.js` from `modules: [path.resolve('node_modules')]` lines to `modules: ['node_modules', path.resolve('node_modules')]`...

**Comment by mwilliamson** [comment]
Does that mean you've got it working?

**Comment by anthony-o** [comment]
Yes with this settings set in `webpack.config.js`.

**Comment by mwilliamson** [comment]
Great, I think this can be closed then.
