### ISSUE TITLE
Can mammoth.js convert client side file to docx without uploading??????

### ISSUE THREAD

**Issue by nil186007** [mwilliamson/mammoth.js#149]
If you're reporting a bug or requesting a feature, it's handy to have:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using

**Comment by mwilliamson** [comment]
Yes, you'll need to provide the document as an `ArrayBuffer` e.g. `mammoth.convertToHtml({arrayBuffer: arrayBuffer})`. The [browser demo](https://github.com/mwilliamson/mammoth.js/blob/master/browser-demo/demo.js) is one example of this.

**Comment by slavajacobson** [comment]
The browser demo uses a form to upload a file. OP asked whether it can be done without uploading with via form? facing the same issue.

**Comment by mwilliamson** [comment]
You need to provide the document as an `ArrayBuffer`: Mammoth doesn't care whether it's gotten from an upload or by some other means.
