### ISSUE TITLE
how to get selected page to extract content from .docx & .doc document?

### ISSUE THREAD

**Issue by navaswd** [mwilliamson/mammoth.js#153]
If you're reporting a bug or requesting a feature, it's handy to have:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using

**Comment by navaswd** [comment]
Can you please help me?

**Comment by mwilliamson** [comment]
I'm afraid I'll need some more details to be able to help you. What are
you trying to do? What have you already tried?

**Comment by mwilliamson** [comment]
Closing since there's not much I can do without further information.
