### ISSUE TITLE
Custom StyleMap

### ISSUE THREAD

**Issue by cory4patriots** [mwilliamson/mammoth.js#154]
Is it possible in custom styleMap to give an image a class name?

`const options = {
  styleMap: "p[style-name='img'] => img.pull-right"
};`

Also is it possible to strip the base64 string from the image? 

Any Help would be nice

**Comment by mwilliamson** [comment]
What you've written will convert paragraphs with the style name "img" into `img` tags, which is presumably not what you want. If you want to add a class to all images, then the simplest thing to do would be to post-process the generated HTML. You can also [create your own image handler](https://github.com/mwilliamson/mammoth.js#custom-image-handlers).

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything to change, but feel free to shout.

**Comment by Arulrajmanickam** [comment]
Can you help regarding how to post process generated HTML?

**Comment by Jatinrajpal** [comment]
if there is a line break in docx file why it is not sjowing it in html file using mammoth?
