### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by gruberjl** [mwilliamson/mammoth.js#160]
Is anyone extracting videos from Word documents?

I create a basic docx with nothing but a YouTube video in it. It appears the video is being converted to an image, possibly by Word. Mammoth is returning the video as an image. I can't find a video tag or any indication it's a video using `transformDocument`

Here's my options:
```
const options = {
  transformDocument: (el) => {
    fs.writeFileSync(__dirname + '\\a.json', JSON.stringify(el, null, '\t'), 'utf8')
    return el
  }
}
```

Here's the output:

```
{
	"type": "document",
	"children": [
		{
			"type": "paragraph",
			"children": [
				{
					"type": "run",
					"children": [
						{
							"type": "image",
							"contentType": "image/jpeg"
						}
					],
					"styleId": null,
					"styleName": null,
					"isBold": false,
					"isUnderline": false,
					"isItalic": false,
					"isStrikethrough": false,
					"isSmallCaps": false,
					"verticalAlignment": "baseline",
					"font": null
				}
			],
			"styleId": null,
			"styleName": null,
			"numbering": null,
			"alignment": null,
			"indent": {
				"start": null,
				"end": null,
				"firstLine": null,
				"hanging": null
			}
		}
	],
	"notes": {
		"_notes": {}
	},
	"comments": []
}
```

**Comment by gruberjl** [comment]
In case anyone needs a quick/weird fix: I put the embed link into the alt text of the video image (within Word) then I used cheerio to replace the img with an iframe.

```
const convertVideos = (html) => {
  const $ = cheerio.load(html)
  $('img[alt*="youtu.be"], img[alt*="youtube.com"]').each((i, el) => {
    const path = $(el).attr('alt')
    $(el).replaceWith(`<iframe width="560" height="315" src="${path}" frameborder="0" allowfullscreen></iframe>`)
  })
  return $('body').html()
}
```

The above worked for me because I'm pre-compiling docx to a static html site for my blog (and I'm the only writer).

**Comment by mwilliamson** [comment]
Closing since I'd need an example document to look into this. If someone wants to provide a minimal example document, that'd be handy.
