### ISSUE TITLE
Feature Request: Preserve ordered list formatting

### ISSUE THREAD

**Issue by cclunie** [mwilliamson/mammoth.js#162]
Currently if you convert an ordered list that has different kinds of formatting:

```
1. First Item
2. Second Item
     a. Sub Item
     b. Sub Item
           i. Sub sub item
```

it will output as:

```
1. First Item
2. Second Item
     1. Sub Item
     2. Sub Item
           1. Sub sub item

```
Being able to automatically add style="list-style-type: lower-alpha;" or whatever formatting to the html would be extremely useful.

**Comment by mwilliamson** [comment]
The intent is that you use styles to format your HTML lists, and map the Word styles to CSS classes appropriate.
