### ISSUE TITLE
styles are not getting 100%

### ISSUE THREAD

**Issue by fareed7440** [mwilliamson/mammoth.js#163]
hey! i am using mammoth for getting the styles of docs file but mammoth did not get the 100% styles .

**Comment by naveedaheer** [comment]
+1

**Comment by mwilliamson** [comment]
By styles, do you mean ad-hoc formatting such as colours and fonts
applied to runs of text? If so, then Mammoth intentionally ignores such
formatting, and instead relies on the semantic information, such as
paragraph styles, to generate cleaner HTML.

If you're looking for a conversion that tries to copy the exact
formatting of the document, then Mammoth isn't the right tool.
