### ISSUE TITLE
Possible to run Word XML string through parser?

### ISSUE THREAD

**Issue by RyanV** [mwilliamson/mammoth.js#165]
When copying and pasting content from word into a browser contenteditable element, the event clipboard data includes the word XML as a string (`event.clipboardData.getData('text/html')`).  Is it possible to pass the this string through the parser?  It doesn't look like the exposed api has that functionality but I'm using webpack to build from source so if there is a specific module I should look at or use, or series of function calls from multiple modules that shouldn't be a problem.

**Comment by mwilliamson** [comment]
Presumably that string has already been converted to HTML? In which case, it's the wrong format for Mammoth: Mammoth requires the original document.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything Mammoth can do in this situation.
