### ISSUE TITLE
Wordpress plugin weird behavior with code/pre

### ISSUE THREAD

**Issue by rgiga** [mwilliamson/mammoth.js#166]
I've embedded style tag for style-named 'Code' via your online tool into word document. 

Style is pretty simple

p[style-name='Code'] => code > pre

which generated attached docx. 

When i run it through your online demo page i get expected result in a form of html 

`<code><pre> ... </pre></code>`

but when i import it into wordpress with your plugin, i get this weird contraption

`<p><code><code></code></code></p><pre>...</pre>` 

I've attached 2 images of debugging tool where you can see html tree.

[sample1 (7).docx](https://github.com/mwilliamson/mammoth.js/files/2282340/sample1.7.docx)

![mammoth_correct](https://user-images.githubusercontent.com/26546523/44022693-997e9ec8-9ee8-11e8-8fad-d92785832a98.jpg)
![mammoth_weird](https://user-images.githubusercontent.com/26546523/44022695-999e86d4-9ee8-11e8-8fca-c6fdf231cb4e.jpg)

**Comment by mwilliamson** [comment]
I haven't had a chance to try out your example myself, but I expect
this is because the WordPress editor is trying to clean up your
generated HTML. In particular, code elements should be inside pre
elements, not the other way round. I'd suggest changing your style
mapping to:

    p[style-name='Code'] => pre > code

**Comment by rgiga** [comment]
It's even worse .. now i get 

Code this:
<pre><code>function nsp_externalApiAjaxN() {
	  $nonce = $_POST['postCommentNonce'];</code></pre>
// check to see if the submitted nonce matches with the
// generated nonce we created earlier
if (!wp_verify_nonce($nonce, 'newstatpress-nsp_external-nonce')) {
die ( 'Busted!');
}
<pre><code></code></pre>
nsp_externalApiAjax();
}
<pre><code></code></pre>

before i had

Code this:

<code><code></code></code>
<pre>function nsp_externalApiAjaxN() {
	  $nonce = $_POST['postCommentNonce'];
	
	  // check to see if the submitted nonce matches with the
	  // generated nonce we created earlier
	  if (!wp_verify_nonce($nonce, 'newstatpress-nsp_external-nonce')) {
	    die ( 'Busted!');
	  }
	
	  nsp_externalApiAjax();
}</pre>

**Comment by mwilliamson** [comment]
Is the preview generating the correct HTML?

**Comment by rgiga** [comment]
Ok, i don't know what happened, but i can't replicate any of this anymore .. pre>code and code>pre work as they're supposed to, need to check with my colleagues if they did something, either update or .. dunno.

**Comment by mwilliamson** [comment]
I'm closing since it doesn't sound like a bug in Mammoth.
