### ISSUE TITLE
[BUG] Looks like Underline isnt working

### ISSUE THREAD

**Issue by ragnerrok** [mwilliamson/mammoth.js#170]
I'm on a Mac, High Sierra, using Chrome ver 69.0.3497.92.

Im running the demo page and it looks like Underline isn't working. I've applied underline to a word doc in multiple places and none of them carry over.

**Comment by mwilliamson** [comment]
Underlines are ignored by default, so if you want to do something with them, you'll need to use a style map.

https://github.com/mwilliamson/mammoth.js#underline

**Comment by ragnerrok** [comment]
OH! I feel super silly. Thanks!

**Comment by mwilliamson** [comment]
No worries!
