### ISSUE TITLE
Extraction of comment text

### ISSUE THREAD

**Issue by Michalwisniewski1** [mwilliamson/mammoth.js#177]
Firstly I'd like to say that mammoth.js library is awesome tool :) Unfortunately I have no idea how to use it to extract comments body (text) by its API. I've created options variable with body:

`   const options = {
                                        styleMap: [
                                            'comment-reference => sup'
                                        ]
                                    };`
It turned on support for comments rendering but I still can't extract comment content. I know that it should be possible to extract more data due existing this function in library code:

`bodyReader.readXmlElements(element.children)
            .map(function(body) {
                return documents.comment({
                    commentId: id,
                    body: body,
                    authorName: readOptionalAttribute("w:author"),
                    authorInitials: readOptionalAttribute("w:initials")
                });
            });`

Thank you for any help and best regards.

**Comment by mwilliamson** [comment]
Could you provide a full example of the code you're using, and a minimal example document?

**Comment by mwilliamson** [comment]
Oh, you mean you just want the comment text itself, without converting it to HTML? No, I'm afraid that's not possible (unless you want to generate the HTML with the comments, and then try to extract it from the HTML).
