### ISSUE TITLE
Support for horizontal rules

### ISSUE THREAD

**Issue by cbrownsey** [mwilliamson/mammoth.js#180]
Would it be possible to add support for the .docx horizontal rules?

Just turning this,

This is a thing
----
This is another thing

into this

    This is a thing
    <hr>
    This is another thing

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML that's currently produced, and the HTML that you'd expect to see?

**Comment by MrCamjames** [comment]
Heres the document
[Horizontal Rule.docx](https://github.com/mwilliamson/mammoth.js/files/2567998/Horizontal.Rule.docx)

Heres what I am getting
    <p>Testing Testing</p>
    <p>123</p>

And heres what I want to be getting
    <p>Testing Testing</p>
    <hr>
    <p>123</p>
