### ISSUE TITLE
Angular 7 installation/use

### ISSUE THREAD

**Issue by dotNetAthlete** [mwilliamson/mammoth.js#181]
https://www.npmjs.com/package/mammoth

How do I use this package in my angular 7 application ?
I have successfully installed it and it appears in my package.json:

{
  "name": "on-call-manager",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "browser": {
    "zlib": false
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.3",
    "@angular/cdk": "^7.0.3",
    "@angular/common": "^7.0.3",
    "@angular/compiler": "^7.0.3",
    "@angular/core": "^7.0.3",
    "@angular/forms": "^7.0.3",
    "@angular/http": "^7.0.3",
    "@angular/platform-browser": "^7.0.3",
    "@angular/platform-browser-dynamic": "^7.0.3",
    "@angular/router": "^7.0.3",
    "@ng-bootstrap/ng-bootstrap": "^4.0.0",
    "@ng-select/ng-select": "^2.12.0",
    "@ngx-pwa/local-storage": "^7.0.0",
    "angular-font-awesome": "^3.1.2",
    "blob-util": "^2.0.2",
    "bootstrap": "^4.1.3",
    "buffer": "^5.2.1",
    "compass-mixins": "^0.12.10",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "events": "^3.0.0",
    "font-awesome": "^4.7.0",
    "formidable": "^1.2.1",
    "guid-typescript": "^1.0.9",
    "jquery": "^3.3.1",
    "js-xlsx": "^0.8.22",
    "mammoth": "^1.4.7",
    "ng2-file-upload": "^1.3.0",
    "ng2-pdf-viewer": "^5.2.0",
    "popper.js": "^1.14.5",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "websocket-extensions": "^0.1.3",
    "ws": "^6.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.10.5",
    "@angular/cli": "^7.0.5",
    "@angular/compiler-cli": "^7.0.3",
    "@angular/language-service": "^7.0.3",
    "@types/jasmine": "^2.8.11",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^10.12.5",
    "codelyzer": "^4.5.0",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "^5.4.1",
    "ts-node": "^7.0.1",
    "tslint": "^5.11.0",
    "typescript": "^3.1.6",
    "webpack-dev-server": "^3.1.10"
  }
}

I wish to convert a .docx to use in my angular application.

**Comment by mwilliamson** [comment]
If you're using Mammoth in the browser, you probably want to use the browser build i.e. `mammoth.browser.js`, as included in the npm package.

**Comment by joellis13** [comment]
Hello @mwilliamson, I have the same problem as @GuitarHero1969.  I appreciate your response, but I'm a bit of a noob and just can't figure out how to import the package/module correctly.  Could you please expand on your response?  I can get it to work just within its own file on the backend, and assume there's some "import { ... } from 'mammoth'," but I just can't piece it together.  Thanks for your help!

**Comment by mwilliamson** [comment]
Rather than importing from `"mammoth"`, you'll want to import from the browser-specific file i.e. `mammoth/mammoth.browser`.
