### ISSUE TITLE
Hi, I want to convert all <p> with “font-size” greater than 18 to <h2>.

### ISSUE THREAD

**Issue by lmrwork** [mwilliamson/mammoth.js#186]
Hi, I want to convert all <p> with “font-size” greater than 18 to <h2>.
How can I write "custom-style-map"?

**Comment by mwilliamson** [comment]
Hello! This isn't supported in style maps. You'll either need to modify the original document to use styles instead of manual formatting, or use a document transform (although I don't think the font size is exposed, so that modification would probably need to be made first).
