### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by saxenakritika** [mwilliamson/mammoth.js#188]
Hello Sir,

I am new to node, so might be doing silly mistake.
I run "make setup" on terminal but i was not able to run it.
Can you please guide me.
![image](https://user-images.githubusercontent.com/29836436/52165652-86c96a00-2729-11e9-84ec-c5a9568a28b8.png)

**Comment by mwilliamson** [comment]
Try installing from npm instead:

    npm install mammoth
