### ISSUE TITLE
strong & bold  tags effect some parent node

### ISSUE THREAD

**Issue by Momaiz** [mwilliamson/mammoth.js#189]
Hello , Thank you for this plugin very useful for me :+1:

I'm using the plugin from this cdn
[mammoth](https://unpkg.com/mammoth@1.4.7/mammoth.browser.min.js
)

Here's example what i'm working on
[tes0.docx](https://github.com/mwilliamson/mammoth.js/files/2906196/tes0.docx)

The Result i got in this file 
[test0.zip](https://github.com/mwilliamson/mammoth.js/files/2906257/test0.zip)

And i expected result like
[_الوالدين - نسخة 1.zip](https://github.com/mwilliamson/mammoth.js/files/2906261/_.-.1.zip)

This Example generated from [freefileconvert.com](https://www.freefileconvert.com/file/A9rJnbMMDrG2)

I dont need full document only the body content

I'm Using this little code for help

`
(function() {
    document.getElementById("CapPostFile")
        .addEventListener("change", handleFileSelect, false);

    function handleFileSelect(event) {

        readFileInputEventAsArrayBuffer(event, function(arrayBuffer) {
            mammoth.convertToHtml({arrayBuffer: arrayBuffer}
                // , options
                )
                .then(displayResult)
                .done();
        });
    }

    function displayResult(result) {

        $('#CapPost').summernote( 'code' , result.value );

        /*
        var messageHtml = result.messages.map(function(message) {
            return '<li class="' + message.type + '">' + escapeHtml(message.message) + "</li>";
        }).join("");

        document.getElementById("messages").innerHTML = "<ul>" + messageHtml + "</ul>";
        */
    }

    function readFileInputEventAsArrayBuffer(event, callback) {
        var file = event.target.files[0];

        var reader = new FileReader();

        reader.onload = function(loadEvent) {
            var arrayBuffer = loadEvent.target.result;
            callback(arrayBuffer);
        };

        reader.readAsArrayBuffer(file);
    }

    function escapeHtml(value) {
        return value
            .replace(/&/g, '&amp;')
            .replace(/"/g, '&quot;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
    }
})();

`

I'm using Windows 7 , with chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by mwilliamson** [comment]
Could you post the expected and actual HTML, rather than providing zip files?

**Comment by mwilliamson** [comment]
Sorry for taking so long to look at this. The example is pretty large, so it's hard to tell exactly what the issue. Since this is pretty old, I'm closing this, but feel free to open another issue with a minimal example.
