### ISSUE TITLE
Multilevel list conversion issue

### ISSUE THREAD

**Issue by kszum** [mwilliamson/mammoth.js#191]
Hi,

I have problem coverting word document to HTML. It seems that lists get ignored during coversion ...

Currently output looks like this:

```
<p>
  TITLE
</p>
<p>
  HEADING
</p>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
<p>
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</p>
<p>
  HEADING
</p>
<p>
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
</p>
<p>
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
<p>
  Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
</p>
<p>
  Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
</p>
```

but expecting:

```
<p>TITLE</p>
<ol>
    <li>HEADING
        <ol>
            <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
        </ol>
    </li>
    <li> ... </li>
    <li> ... </li>
</ol>
```

and here is doc file:
[Mammoth Test.docx](https://github.com/mwilliamson/mammoth.js/files/2933618/Mammoth.Test.docx)

Thanks

**Comment by kszum** [comment]
However, this one works as expected ...
[mammoth.docx](https://github.com/mwilliamson/mammoth.js/files/2948258/mammoth.docx)

**Comment by robmarch2** [comment]
I just raised [a related issue](https://github.com/mwilliamson/java-mammoth/issues/13) over on the `java-mammoth` repo to do with top level lists and converting from `.doc` to `.docx` before passing into Mammoth, but we're also seeing this issue with nested lists too (on documents created as `.docx` originally as opposed to created as `.doc` and converted manually to `.docx`)

**Comment by mwilliamson** [comment]
@kszum I've just published 1.4.8 to npm. Could you check whether it resolve this issue for you?

**Comment by kszum** [comment]
@mwilliamson, I use Mammoth .docx converter wordpress plugin. What files do I need to update? Sorry for posting in wrong place.

**Comment by mwilliamson** [comment]
The WordPress plugin hasn't been updated yet. I'll update it when I get a chance. Trying out your original file that you attached seems to produce the desired result, so I'll close this issue for now.

**Comment by mwilliamson** [comment]
I've updated the WordPress plugin with the latest version of mammoth.js.
