### ISSUE TITLE
Could not find file in options or render it to the page?

### ISSUE THREAD

**Issue by ryanbucci5** [mwilliamson/mammoth.js#192]
Sorry it's my first time using mammoth, and I'm not quite getting it to work properly. 

Here is my code: 
`app.post('/', function(req, res){	
    // console.log(req.files.UploadBox);

    let uploadedFile = req.files.UploadBox;

    console.log(uploadedFile);

    
    let renderHtml = mammoth.convertToHtml({uploadedFile})
        .then(function(result) {
            var html = result.value; // The Generated HTML
            var messages = result.messages // Any messages, such as warnings during conversion
        })
    .done();

    res.render(renderHtml);
  });`

When I console log the uploadedFile, the file details come out like the file size, name, etc. 
Then when I get down to the Mammoth section, I keep getting errors. 

The error in the command terminal is, "Could not find file in options".  I've tried searching for this error or errors like it but am having difficulty pinpointing what the issue is. I know it's something super simple and I apologize for not knowing (very new to JS). 

Thanks in advance to anyone who can help, and I'm super excited to use this package. Thanks again!

**Comment by mwilliamson** [comment]
You need to pass an array buffer to `convertToHtml`. Assuming the variable `arrayBuffer` is an array buffer:

```javascript
mammoth.convertToHtml({arrayBuffer: arrayBuffer})
```

**Comment by mwilliamson** [comment]
You might find the browser demo helpful: https://github.com/mwilliamson/mammoth.js/blob/master/browser-demo/demo.js
