### ISSUE TITLE
type definition (d.ts) file 

### ISSUE THREAD

**Issue by serkanz** [mwilliamson/mammoth.js#193]
Hi folks,

In order to use mammoth in a Node project with Typescript it'd be good to have a type definition file which I couldn't find on https://definitelytyped.org/. Should I look somewhereelse?

Regards

**Comment by mwilliamson** [comment]
There aren't any type definition files that I'm aware of, but Mammoth has a reasonably small API so hopefully writing your own wouldn't be too tricky.

**Comment by NoelAbrahams** [comment]
@mwilliamson most packages now include TypeScript definitions. This has two benefits: 

* There is compile-time safety out of the box. Just writing `import * as mammoth from 'mammoth'` will cause TypeScript to look up and import the definitions.
* Should you deploy breaking changes then it is easy for users of your library to refactor.
* Bonus: Saves every single user of your library from expending effort on writing their own duplicated versions.

Here is a basic but working version of the definitions. Please consider packaging this.

```ts

/** A module for converting Microsoft Word .docx files to HTML or text. */
declare module 'mammoth' {

    type Input = {

        /** The path to the .docx file. */
        path?: string;

        /** The buffer containing the .docx file, if path is not specified. */
        buffer?: Buffer;
    };

    /** Conversion options. */
    type Options = {

        /** 
         *  Overrides for the default style map. 
         *  Examples:
         *      "b => em"
         *      "i => strong"
         */
        styleMap?: string[];

        /** To stop using the default style map. */
        includeDefaultStyleMap?: boolean;

        convertImage?: unknown;
    };

    /** The error or warning message returned from the processing operation. */
    type Message = {

        /** a string representing the type of the message, such as "warning" or "error" */
        type: 'warning' | 'error';

        /** a string containing the actual message */
        message: string;

        /** the thrown exception that caused this message, if any */
        error?: Error;
    };

    /** The result from the processing operation. */
    type Result = {

        /** The HTML result. */
        value: string;

        /** Error and warning messages if any. */
        messages: Message[];
    };

    namespace images {

        type Image = {

            read(type: string): Promise<Buffer>;
            contentType: string;
        };

        type Source = {
            src: string;
        };

        export function imgElement(callback: (image: Image) => Source | Promise<Source>): void;
    }

    /**
     * Converts an existing .docx file to HTML.
     * @param input An object containing the path or buffer.
     */
    export function convertToHtml(input: Input, options?: Options): Promise<Result>;

    /**
     * Converts an existing .docx file to plain texts.
     * @param input An object containing the path or buffer.
     */
    export function extractRawText(input: Input): Promise<Result>;
}
```

**Comment by mwilliamson** [comment]
I spent a little time looking at this, and the problem is that the types are slightly different in the browser and in node.js. While you can set the `browser` field in `package.json` to use different code for the two different platforms, there isn't an equivalent for type definitions. I haven't thought too much about the right way to solve this yet, but I'm reluctant to publish incorrect type definitions.

As quick comments on your suggested type definitions: you can be a bit more specific with the input type i.e.

```
type Input =
    | {path: string}
    | {buffer?: Buffer};
```

`imgElement` returns an image handler. It's probably best to treat that as an opaque type, which you can roughly simulate with branding e.g.

```
interface ImageHandler {
    __mammothImageHandler: true;
}

export function imgElement(callback: (image: Image) => Source | Promise<Source>): ImageHandler;

type Options = {
    ...
    convertImage?: ImageHandler;
    ...
}
```

The `read()` method on `Image` will only return a `Buffer` if no encoding is given. If an encoding is given, it returns a string. In other words, the type is:

```
(() => Promise<Buffer>) | ((encoding: string) => Promise<string>)
```

**Comment by zarghambetterfront** [comment]
@mwilliamson  any update regarding types being added to package ?

**Comment by mwilliamson** [comment]
TypeScript declarations have been added to 1.4.19.
