### ISSUE TITLE
Incorrect anchor conversion

### ISSUE THREAD

**Issue by kszum** [mwilliamson/mammoth.js#195]
Hello,

When I convert a link with:

`r[style-name='Hyperlink'] => a.text-dark.inline`

mammoth outputs:

`<a href="https://google.com"><a class="text-dark inline">https://google.com</a></a>`

[mammoth+link - mapped.docx](https://github.com/mwilliamson/mammoth.js/files/3194131/mammoth%2Blink.-.mapped.docx)

Is there any other way to add class name to a link?

p.s.
I'm using wordpress plugin

**Comment by mwilliamson** [comment]
The source document represents the run with a style of "Hyperlink" and the hyperlink itself as separate elements, so Mammoth's output reflects that. Your best bet is probably to map the run to a span instead of an anchor.
