### ISSUE TITLE
want to extract the font size from doc text

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#197]
Hi, 
How can I get the font size of a particular text or heading from docx file?
Thanks.

**Comment by mwilliamson** [comment]
Could you explain your use-case? Are you looking for the font size to be available during the conversion, or do you just want to extract the font size using Mammoth as a parser?

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything I can do without further information.

**Comment by sanjeev9540** [comment]
Hi sir, how can i get get exact font size when we import docx??
