### ISSUE TITLE
 Issues with List, heading and special characters

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#198]
Hi,
[demo_file.docx](https://github.com/mwilliamson/mammoth.js/files/3425892/demo_file.docx)
[conveted_html_source_file.txt](https://github.com/mwilliamson/mammoth.js/files/3425896/conveted_html_source_file.txt)
After converting from docx to html, I have listed some major problems/remarks after getting the conversion with respect to the original file; In html file:
1) Each text is aligned to right  in output
2) some non - alphanumeric symbols converted to some random symbols
3) After list if another heading begins, this heading is clubbed inside the list above
4) partially converting unordered list with list-style-type roman to numbers
5) If the page ends with list, then new heading from next page will be clubbed as a part of earlier list, 

There some other issues as well, I have attached the Original docx and converted html file. Please analyse it and help me to resolve these issues, Thank You!!

**Comment by mwilliamson** [comment]
If you could open a separate issue for each problem, and provide a separate minimal example document for each, that would help in working out the issues.
