### ISSUE TITLE
Problem_1: Font styles and Text alignment 

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#199]
Hello Sir, As per your suggestion in Issue #198, I am raising separate Issues,
I have noticed following changes regarding font size, and Text Alignment:
1) font style converted to normal
2) Format has changed in terms of position, text which was center aligned, striped to left for all text
Refer the attachments.
![Issue_1](https://user-images.githubusercontent.com/29540745/62449570-1c50bf80-b788-11e9-87f3-946807910b35.PNG)
![Issue_1_html](https://user-images.githubusercontent.com/29540745/62449580-21157380-b788-11e9-929f-56917041833f.PNG)

Please help me resolve this issue, Thanks

**Comment by mwilliamson** [comment]
Could you provide a minimal docx file and both the expected HTML and
actual HTML (as text) rather than as an image? Otherwise it's tricky
to reproduce the issue. Thanks.

**Comment by Dinesh-Mali** [comment]
yes sir,
I have already provided the original file and converted html source code in issue #198.
Please find the files there. All the problems are mentioned in that file. But for convenience I posted that individually.

**Comment by mwilliamson** [comment]
Sorry, I wasn't very clear: the original file contains all of the
issues together. I'm asking for a docx file for each issue. In other
words, each file should show one issue in isolation, otherwise it's
quite time consuming to work out what the relevant parts of the
original document are for each issue.

**Comment by Dinesh-Mali** [comment]
Ok, Sure.
Please give me some time I will provide docx file for each issue separately. 
Thanks.

**Comment by Dinesh-Mali** [comment]
[problem_1.txt](https://github.com/mwilliamson/mammoth.js/files/3470602/problem_1.txt)
Hello Sir,
As per you suggested, I have attached all the problems in individual docx file and related html source file.
PFA,
Problem_1:
[problem_1.docx](https://github.com/mwilliamson/mammoth.js/files/3470604/problem_1.docx)
[problem_1.txt](https://github.com/mwilliamson/mammoth.js/files/3470628/problem_1.txt)

Problem_2:
[problem_2.docx](https://github.com/mwilliamson/mammoth.js/files/3470605/problem_2.docx)
[problem_2.txt](https://github.com/mwilliamson/mammoth.js/files/3470607/problem_2.txt)

Problem_3:
[problem_3.docx](https://github.com/mwilliamson/mammoth.js/files/3470609/problem_3.docx)
[problem_3.txt](https://github.com/mwilliamson/mammoth.js/files/3470611/problem_3.txt)

Problem_4:
[problem_4.docx](https://github.com/mwilliamson/mammoth.js/files/3470614/problem_4.docx)
[problem_4.txt](https://github.com/mwilliamson/mammoth.js/files/3470615/problem_4.txt)

Problem_5:
[problem_5.docx](https://github.com/mwilliamson/mammoth.js/files/3470616/problem_5.docx)
[problem_5.txt](https://github.com/mwilliamson/mammoth.js/files/3470617/problem_5.txt)

Problem_6:
[problem_6.docx](https://github.com/mwilliamson/mammoth.js/files/3470619/problem_6.docx)
[problem_6.txt](https://github.com/mwilliamson/mammoth.js/files/3470620/problem_6.txt)

Problem_7:
[problem_7.docx](https://github.com/mwilliamson/mammoth.js/files/3470622/problem_7.docx)
[problem_7.txt](https://github.com/mwilliamson/mammoth.js/files/3470623/problem_7.txt)

Problem_8:
[problem_8.docx](https://github.com/mwilliamson/mammoth.js/files/3470624/problem_8.docx)
[problem_8.txt](https://github.com/mwilliamson/mammoth.js/files/3470625/problem_8.txt)

Problem_9:
[problem_9.docx](https://github.com/mwilliamson/mammoth.js/files/3470626/problem_9.docx)
[problem_9.txt](https://github.com/mwilliamson/mammoth.js/files/3470627/problem_9.txt)

Thanks.

**Comment by mwilliamson** [comment]
Mammoth is designed to map Word styles to the appropriate HTML and CSS classes, rather than copying the exact formatting of the original document. I'd suggest defining styles that have the styling you want, and then mapping those. If you're looking for a conversion that tries to copy the exact formatting of the document, then Mammoth isn't the right tool.

**Comment by chairuosen** [comment]
Just do it by ourself. I add a simple hook and it works . see https://github.com/chairuosen/mammoth.js recent activities.

usage demo:
```
const { value: html } = await mammoth.convertToHtml({path: outputPath}, {
    styleHook(el, pr){
      console.log('style hook', el.name)
      if(el.name === 'w:p'){
        const result = []

        const fontSizeEl = el.firstOrEmpty('w:r').firstOrEmpty('w:rPr').first('w:sz')
        if(fontSizeEl){
          const fontSizeVal = fontSizeEl.attributes['w:val']
          result.push(`font-size:${fontSizeVal/2}pt`)
        }

        const colorEl = el.firstOrEmpty('w:r').firstOrEmpty('w:rPr').first('w:color')
        if(colorEl){
          const colorVal = colorEl.attributes['w:val']
          result.push(`color:#${colorVal}`)
        }

        const boldEl = el.firstOrEmpty('w:r').firstOrEmpty('w:rPr').first('w:b')
        if(boldEl){
          const boldVal = boldEl.attributes['w:val']

          if(boldVal !== '0'){
            result.push(`font-weight:bold`)
          }else if(
            pr.first('w:pStyle')
            && pr.firstOrEmpty('w:pStyle').attributes['w:val']
            && pr.firstOrEmpty('w:pStyle').attributes['w:val'].indexOf('Heading') > -1
          ){
            result.push(`font-weight:normal`)
          }
        }

        const alignEl = el.firstOrEmpty('w:pPr').first('w:jc')
        if(alignEl){
          const alignVal = alignEl.attributes['w:val']
          result.push(`text-align:${alignVal}`)
        }


        const indentEl = el.firstOrEmpty('w:pPr').first('w:ind')
        if(indentEl){
          const indentVal = indentEl.attributes['w:firstLineChars']
          if(indentVal){
            result.push(`text-indent:${parseFloat(indentVal / 100).toFixed(0)}em`)
          }
        }

        const lineHeightEl =  el.firstOrEmpty('w:pPr').first('w:spacing')
        if(lineHeightEl){
          const lineHeightVal = lineHeightEl.attributes['w:line']
          const lineTypeVal = lineHeightEl.attributes['w:lineRule']
          if(lineHeightVal && lineTypeVal === 'auto'){
            const lineHeight = parseFloat(lineHeightVal / 240).toFixed(2)
            result.push(`line-height:${lineHeight}`)
          }else if(lineHeightVal && lineTypeVal === 'exact'){
            const lineHeight = parseFloat(lineHeightVal / 20).toFixed(2)
            result.push(`line-height:${lineHeight}pt`)
          }
        }

        return result.join(';') || ''
      }else{
        return ''
      }
    },
.......
```
