### ISSUE TITLE
Problem_2: Table border Issue

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#200]
Hello,
In this issue, the table content is retained, but the table border has eliminated.
PFA,
![Issue_2](https://user-images.githubusercontent.com/29540745/62449882-c7617900-b788-11e9-8deb-1793f183fc4a.PNG)
![Issue_2_html](https://user-images.githubusercontent.com/29540745/62449888-ccbec380-b788-11e9-8b83-fe9e38d12b3f.PNG)

**Comment by mwilliamson** [comment]
Do you want the borders on particular tables, or on all of them? If the latter, then I'd suggest that that's something you should control using CSS wherever you're ultimately using the generated HTML.

**Comment by Arulrajmanickam** [comment]
@Dinesh-Mali : Even I face the same issue. Table borders are not shown. 
I am not clear about how to control it using CSS.
Style mapping - I need more info on how to retrieve word styles and how to convert that to equivalent css styles. 
Say for eg. I want to align the heading to center. How can i do so with mammoth?

**Comment by mwilliamson** [comment]
The supported approach is to use a table style in the original Word document, and then use a style mapping to map that Word style to an appropriate CSS class.

**Comment by vamshicherala** [comment]
still the ans was not helpful

@mwilliamson can you tell us know how to retain all the table borders while converting tha docx to html using mammoth

**Comment by DikshaG001** [comment]
HI @Dinesh-Mali , did you find any solution to the above?

**Comment by vamshicherala** [comment]
no
