### ISSUE TITLE
Problem_4: List items 'Roman' type converted to partial 'Numerical' type list

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#202]
Hello,
When list consist nested list with different list items order, mammoth only partially converting these to numerical types.
PFA,
![Issue_4](https://user-images.githubusercontent.com/29540745/62450628-51f6a800-b78a-11e9-9185-3c661c81084b.PNG)
![Issue_4_html](https://user-images.githubusercontent.com/29540745/62450631-51f6a800-b78a-11e9-9d31-e61a7116c57a.PNG)

**Comment by mwilliamson** [comment]
From #199:

> Problem_4:
> [problem_4.docx](https://github.com/mwilliamson/mammoth.js/files/3470614/problem_4.docx)
> [problem_4.txt](https://github.com/mwilliamson/mammoth.js/files/3470615/problem_4.txt)

Some of the lines in the document you've provided are marked in Word as being items in a list: so far as I can tell, these are correctly converted to list items. The remaining items are ordinary paragraphs that have the numbering explicitly entered in as text, so Mammoth converts them to ordinary paragraphs. If you want them to be converted to list items, they'll need to be list items in the original document.
