### ISSUE TITLE
Problem_5: List item continuation issue

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#203]
Hello,
If the list is continued from page one to next page, then the remaining list items are considered to be a separate heading.
PFA,
![Issue_5](https://user-images.githubusercontent.com/29540745/62450831-b0238b00-b78a-11e9-9716-afd0c753cf92.PNG)
![Issue_5_html](https://user-images.githubusercontent.com/29540745/62450832-b0238b00-b78a-11e9-91ba-793c3c6a7541.PNG)

**Comment by mwilliamson** [comment]
To check I've understood: the issue is that the numbering restarts?
