### ISSUE TITLE
Problem_7:Image labels are treated as new lines

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#205]
Hello,
The image labels or titles are treated as new lines.
PFA,
![Issue_7](https://user-images.githubusercontent.com/29540745/62452695-58871e80-b78e-11e9-84e2-228ebf2c953e.PNG)
![Issue_7_html](https://user-images.githubusercontent.com/29540745/62452696-58871e80-b78e-11e9-9e72-c85430027ec9.PNG)

**Comment by mwilliamson** [comment]
Based on the example document posted in #199:

> Problem_8:
> [problem_8.docx](https://github.com/mwilliamson/mammoth.js/files/3470624/problem_8.docx)
> [problem_8.txt](https://github.com/mwilliamson/mammoth.js/files/3470625/problem_8.txt)

I'm not sure I see the problem: the output HTML looks as I'd expect. The text below each image is in a separate paragraph in the original document, so Mammoth maps them to separate paragraphs in the HTML.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything I can without more information.
