### ISSUE TITLE
Problem_8: headings are combined with the previous headings

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#206]
Hello,
Sometimes one of the heading get clubbed with the previous heading, This issue might happen with any headings irrespective of its occurrence, (Not only for headings  that are starting on new page )

Please guide and help me so that I can resolve these issues,
Thanks,
PFA,
![Issue_9](https://user-images.githubusercontent.com/29540745/62453036-1c07f280-b78f-11e9-9a3b-77538a084382.PNG)
![Issue_9_html](https://user-images.githubusercontent.com/29540745/62453037-1c07f280-b78f-11e9-8d48-6272c1dad4ef.PNG)

**Comment by mwilliamson** [comment]
> Problem_8:
> [problem_8.docx](https://github.com/mwilliamson/mammoth.js/files/3470624/problem_8.docx)
> [problem_8.txt](https://github.com/mwilliamson/mammoth.js/files/3470625/problem_8.txt)

Looking at the example document and output HTML you've provided, I'm not sure I see the issue. The output looks as I'd expect. Could you explain what HTML you'd expect to see?

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything I can without more information.
