### ISSUE TITLE
Problem_9: bold text items inside list are treated as new paragraphs

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#207]
Hello,
If list items consists bold text, then it is considered as new paragraph while extracting the tags.
Please help so that I can resolve the issues from Problem_1 to Problem_9.
Thanks,

PFA,
Original Doc:
![issue_with_list_items_converted](https://user-images.githubusercontent.com/29540745/62453383-da2b7c00-b78f-11e9-97f8-55b34bf5e343.PNG)

Doc after extracting all tags,
![issue_with_list_items_1](https://user-images.githubusercontent.com/29540745/62453423-eca5b580-b78f-11e9-952c-e126da8e96f1.PNG)

**Comment by mwilliamson** [comment]
From #199:

> Problem_9:
> [problem_9.docx](https://github.com/mwilliamson/mammoth.js/files/3470626/problem_9.docx)
> [problem_9.txt](https://github.com/mwilliamson/mammoth.js/files/3470627/problem_9.txt)

The example document doesn't seem to have bold items inside list items, and converts as I'd expect. Could you check that this is the right document for this issue?

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything I can without more information.
