### ISSUE TITLE
Targeting a word's style with style map

### ISSUE THREAD

**Issue by jkorff** [mwilliamson/mammoth.js#209]
I have a use case where an author assigned a style to one or more words and I like to catch these with a custom style  map.

After reading the docs and some issues here I could not find anything that this is supported. It would be great to be able to specify e.g.

`[style=name='HTMLCite'] => cite`

and Mammoth converts words with that style e.g.

`<p>... lorem ipsum <cite>dolor</cite> ahmet ...</p>`

I've tried the "Match any run" syntax unsuccessfully.
In the Word XML it appears as

`<w:r w:rsidRPr="00786BC9"><w:rPr><w:rStyle w:val="HTMLCite"/>...`

**Comment by mwilliamson** [comment]
If you're mapping a style for a run, then the style mapping would be:

```
r[style-name='HTMLCite'] => cite
```

Assuming that the style name is indeed `HTMLCite` (the value in the XML is the style ID, not the name, and two may be different). The messages produced by Mammoth should tell you the name of unmatched styles.

**Comment by jkorff** [comment]
Thank you Michael.

This is embarrassing – I have a typo in my code: There is an equal sign instead of a hyphen between "style" and "name". Fixing that fixed the issue. 

Thanks for looking into it!
