### ISSUE TITLE
Images/drawings in table cells

### ISSUE THREAD

**Issue by 8slashes** [mwilliamson/mammoth.js#211]
Hi, Michael. Thanks for providing us with this tool. I notice that images/drawings inside of table cells are ignored by default or by any image converter (that I've tested for so far). I'd be interested in adding this functionality if you could provide some insight on where to look.

I've been poking around in `lib/docx/body-reader.js`, mostly in the `readTableCell` function. I've tried passing the children through `xmlElementReaders['w:p']` but I haven't gotten it to work. My belief is as long as I can pass the table cell children into a function that will parse out the paragraph I can get any image/drawing in a table cell to be added to the document, thus image converter will see them and generate images for them.

Am I on the right path? Any insight would be appreciated. Thanks!

**Comment by mwilliamson** [comment]
Could you provide a minimal example document? Do you get any messages in the result?

From my possibly incorrect recollection, the children of table cells get parsed the same as the body of other container elements, so if images are contained in a table cell in the same way as other images that mammoth supports, then they should be included in the output.

**Comment by 8slashes** [comment]
I do get messages but they don't seem related to missing images/drawings. Here is my small example. [https://github.com/8slashes/mammoth-test](url)

I must apologize though. I believe the reason they aren't showing is because these particular "images" are actually charts. I just realized that what was going on based off the conversation on [https://github.com/mwilliamson/mammoth.js/issues/147#issuecomment-362697430](url)

Again, sorry for wasting your time. I should have read more thoroughly.
