### ISSUE TITLE
Could not find main document part. Are you sure this is a valid .docx file?

### ISSUE THREAD

**Issue by AlexMougenet** [mwilliamson/mammoth.js#212]
#### Issue description

I get an error when using mammoth.convertToHtml(...) in an Angular app with a working .docx file.

#### Steps to reproduce the issue

1. Create a basic Angular App, with mammoth installed
2. Add a .docx file in the assets folder (make sure you can access it)
3. Load the .docx file, convert it into an arraybuffer, and use mammoth.convertToHtml({arrayBuffer: file_arraybuffer});

#### What's the expected result?

- The .docx file is converted to HTML

#### What's the actual result?

- An error appears : `Could not find main document part. Are you sure this is a valid .docx file?`

#### Additional details / screenshot

Here is my code : 

```
this.http.get('assets/my-working-file_1.0.docx', { responseType: 'text' }).subscribe(file => {
      let file_arraybuffer = new TextEncoder().encode(file);
      mammoth.convertToHtml({arrayBuffer: file_arraybuffer}).then(function (resultObject) {
        console.log('mammoth result', resultObject.value);
      });
    });
```

I've already tried these different methods : 

```
let file_arraybuffer_1 = Buffer.from(btoa(unescape(encodeURIComponent(file))), "base64");

let file_arraybuffer_2 = this.base64ToArrayBuffer(btoa(unescape(encodeURIComponent(file))));

  base64ToArrayBuffer(base64) {
    var binary_string =  window.atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array( len );
    for (var i = 0; i < len; i++)        {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}
```

OS and version : macOS Mojave 10.14.5
Browser : Chrome 75.0.3770.142
Angular version : 7

Could you please help me to understand where the issue is coming from ?

**Comment by AlexMougenet** [comment]
I just tried with a freshly created .docx file and i get this new error : "Error: End of data reached (data length = 18832, asked index = 29769). Corrupted zip ?"

**Comment by mwilliamson** [comment]
I'm not familiar with Angular, but it seems like you can set `responseType` to `arraybuffer`, which would give the file in exactly the structure you need to pass to Mammoth.

**Comment by AlexMougenet** [comment]
Thank you, it's now working ! :)

**Comment by fahadsubzwari924** [comment]
> Thank you, it's now working ! :)



> I'm not familiar with Angular, but it seems like you can set `responseType` to `arraybuffer`, which would give the file in exactly the structure you need to pass to Mammoth.

But i am also getting this error on locally uploaded file preview in angular like this

       const reader = new FileReader();
       reader.readAsDataURL(inputFile);
       reader.onload = (_event) => {
           this.docUrl = reader.result;
        }
        
       <ngx-doc-viewer [url]="docUrl " viewer="mammoth" style="width:100%;height:60vh">
       </ngx-doc-viewer>
