### ISSUE TITLE
Style mapping

### ISSUE THREAD

**Issue by Arulrajmanickam** [mwilliamson/mammoth.js#213]
Style mapping - 
1. I need more info on how to retrieve docx styles and how to convert them to equivalent html tags/css styles(styles examples please). I have read over and over your mammoth documentation in npm and github. 
But style mapping is explained only for common docx styles.
 
2. Is post processing of generated html is allowed and if it is allowed how to do so?

3. How to fit an image in the docx to html in proper position and size?

4. How to generate borders for tables? 

 I am using chrome browser on windows os and using angular for front end.
  I am using mammoth.browser.js in angular.

**Comment by mwilliamson** [comment]
> Style mapping -
> 
>     1. I need more info on how to retrieve docx styles and how to convert them to equivalent html tags/css styles(styles examples please). I have read over and over your mammoth documentation in npm and github.
>        But style mapping is explained only for common docx styles.

The process is the same for the built-in styles and any custom styles you've written. If you've used styles that Mammoth doesn't recognise, their names will be included in the messages in the result.

>     2. Is post processing of generated html is allowed and if it is allowed how to do so?

The output is an HTML string, so you can do whatever you want with it.

>     3. How to fit an image in the docx to html in proper position and size?

I think this is covered by https://github.com/mwilliamson/mammoth.js/issues/187.

>     4. How to generate borders for tables?

For all tables or for a specific table? If the former, then you can use CSS to apply the borders to the table.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything specific to do here.
