### ISSUE TITLE
Style map

### ISSUE THREAD

**Issue by NichitaD** [mwilliamson/mammoth.js#219]
Hey,

Is there a way to extract the styles from the .docx document, or is there a complete style map, to cover everything, so that the document is displayed exactly as it is in Word?

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't copy the exact formatting of the original document, but instead maps Word styles to the appropriate HTML. The idea is that you'd semantically mark up the original document to generate cleaner HTML. If you need something that copies the exact formatting, then you'll need a different library.
