### ISSUE TITLE
Path must be a string without null bytes

### ISSUE THREAD

**Issue by guypeled1** [mwilliamson/mammoth.js#224]
i'm getting file content from s3 bucket. 
the answer gives me the file context body.
I'm getting this error. how can i solve this?

**Comment by guypeled1** [comment]
for example this is my context:
<Buffer 50 4b 03 04 14 00 08 08 08 00 4d 0e 9a 4f 00 00 00 00 00 00 00 00 00 00 00 00 12 00 00 00 77 6f 72 64 2f 6e 75 6d 62 65 72 69 6e 67 2e 78 6d 6c a5 93 ... >

**Comment by mwilliamson** [comment]
Could you provide example code and the full error, including the stack trace?

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything that can be done without more information.
