### ISSUE TITLE
Could not find file in options

### ISSUE THREAD

**Issue by guypeled1** [mwilliamson/mammoth.js#226]
Hi,
i'm getting this error. i don't know what am i doing wrong?
`
onSubmit({value}){
    const b = new FileReader();
    let fileInput:any =  document.querySelector('#fileInput');
   let blob = fileInput.files[0];
    convertToHtml({
      arrayBuffer: b.readAsArrayBuffer(blob)
    })
      .then(function(result) {
        console.log(result);
      })
      .done();
  }
`

thanks

**Comment by mwilliamson** [comment]
`readAsArrayBuffer` doesn't return an array buffer. You'll need to listen for a load even on the file reader to get the array buffer.

**Comment by guypeled1** [comment]
do you have an example how to use it in angular 7 app?

**Comment by mwilliamson** [comment]
I'm afraid I don't use Angular, but using it in the browser shouldn't depend on which framework you're using. As long as you can get an array buffer and pass that in, the conversion should work.

**Comment by guypeled1** [comment]
the problem had solved thanks
