### ISSUE TITLE
Problems with Headings in Lists

### ISSUE THREAD

**Issue by tripodsan** [mwilliamson/mammoth.js#228]
Parsing the following document does not reveal the numbering of the headings:

[list-heading-test.docx](https://github.com/mwilliamson/mammoth.js/files/4248278/list-heading-test.docx)

But opening it in word shows the numbers and the headings are both: headings and list:

![image](https://user-images.githubusercontent.com/917628/75219049-19c6bd80-57df-11ea-95bc-673d97967f47.png)

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

- node v10.18.0
- mammoth v1.4.9

**Comment by sebdec** [comment]
I reproduce this case too.
Actually it seems not possible to retrieve the list with mammoth if there is a style defined to the list item (normal, heading ...).

ex: list item is a heading
```
<w:p w14:paraId="668D915D" w14:textId="493E6181" w:rsidR="00C621A5" w:rsidRPr="00C621A5" w:rsidRDefault="00C621A5" w:rsidP="00C621A5">
      <w:pPr>
        <w:pStyle w:val="Heading1" />
        <w:numPr>
          <w:ilvl w:val="0" />
          <w:numId w:val="1" />
        </w:numPr>
      </w:pPr>
      <w:r>
        <w:t>Heading1</w:t>
      </w:r>
    </w:p>
```

returns the following html value:
```
<h1>Heading1</h1>
```

expected value:
```
<ol><li><h1>Heading1</h1></li></ol>
```

**Comment by mwilliamson** [comment]
I don't think there's a general way to handle this case i.e. it doesn't map cleanly to HTML, since having a single-element list with a heading in would be pretty unusual. I'd suggest using style maps to describe how you want your particular document to be converted.
