### ISSUE TITLE
Is it possible include inputbox, checkbox and listboxes from Word to HTML?

### ISSUE THREAD

**Issue by frantwo** [mwilliamson/mammoth.js#231]
Hello, 
I was thinking if it is planned that Mammoth will support the controls: inputbox, checkbox and listbox:
[Example.docx](https://github.com/mwilliamson/mammoth.js/files/4274961/Example.docx)

to get a html result as :
![image](https://user-images.githubusercontent.com/11053804/75670406-f4253280-5c7c-11ea-8e37-9429a56218c3.png)

Thank you very much for your time and support! 
Your tool is amazing!!!
BR!

**Comment by hangjob** [comment]
Hello, how did you solve this problem?

**Comment by hangjob** [comment]
@frantwo Hello, how did you solve this problem?

**Comment by frantwo** [comment]
Hello!
In truth, I was not able to make it work. I had many limitations with Mammoth and it was very complicated for my goal.
Instead, I used Word's Javascript API for what I wanted. And then we have developed in a backend a kind of html processing to be displayed in a frontend.
BR!
