### ISSUE TITLE
Jest tests failed when using mammoth

### ISSUE THREAD

**Issue by tegomass** [mwilliamson/mammoth.js#233]
Hi, 

Jest tests failed when importing mammoth in a file :

`Test suite failed to run

    TypeError: Cannot read property 'bind' of undefined

      1 | 
      2 | import React, { Component } from 'react';
    > 3 | import mammoth from 'mammoth';
        | ^
      4 | 
      5 | export default class extends Component {
      6 |     componentDidMount() {

      at Object.<anonymous> (node_modules/mammoth/lib/docx/files.js:40:47)
      at Object.<anonymous> (node_modules/mammoth/lib/docx/docx-reader.js:20:13)
      at Object.<anonymous> (node_modules/mammoth/lib/index.js:3:18)
`

**Comment by mwilliamson** [comment]
The line in question seems to be `fs.readFile.bind(fs)`. Are you running the tests in an environment where `fs.readFile` should be available?

**Comment by tegomass** [comment]
I can add `import fs from 'fs';` before importing mammoth, but it changes nothing... :(

**Comment by mwilliamson** [comment]
What environment are you running the tests in? Is `fs.readFile` available?

**Comment by tegomass** [comment]
I'm running Jest for React tests.
my test file just looks like this 👍 
`import React from 'react';
let fs = require('fs')
import App from '../../app/components/App';
import renderer from 'react-test-renderer';
`
it failed even if I haven't set any tests. Just by importing modules.

**Comment by mwilliamson** [comment]
If you're running the tests on node.js, then `fs.readFile` should be available. If you're running the tests on the browser, you should be using the browser version of Mammoth instead (`mammoth.browser.js`).

**Comment by tegomass** [comment]
Ok, if you don't see an issue on your side with Jest, it's probably I missconfigured something... I close this request. Thank you for your help 👍
