### ISSUE TITLE
Exposing text or paragraph font-size for parsing purposes

### ISSUE THREAD

**Issue by Overdrivr** [mwilliamson/mammoth.js#236]
I'm using mammoth to read and parse docx documents, so far this is the only library I've found that can decently parse docx files in NodeJS.

For an application, I'd like to extract and expose font-size of a `text` or a `paragraph` in addition to the already exposed styles.

I want to "normalize" styles detected within a document. Basically, if the document that was provided did not use Word styles but instead hardcoded font sizes, I need to be able to detect this and artificially re-associate a style.

Would you consider just exposing font styles in the API ? If yes could you give me a hint on how would this be achieved, so that I can open a PR ? Thank you.

**Comment by mwilliamson** [comment]
Font sizes applied to specific runs should be read during parsing on master, if you wouldn't mind taking a look?

**Comment by Overdrivr** [comment]
You're right, just tried it. Information is missing from npm latest but is correctly parsed using master latest. Thank you for your quick feedback, feel free to close the ticket if you feel nothing's more is to be done here!

**Comment by mwilliamson** [comment]
Great, thanks for trying it out.
