### ISSUE TITLE
Unable to Render DOCX file in react app.

### ISSUE THREAD

**Issue by sadashivm** [mwilliamson/mammoth.js#238]
Hello,
I tried to implement your plugin in my react app. But I'm getting below error

![image](https://user-images.githubusercontent.com/10355473/81179753-b5d32900-8fc7-11ea-85fd-cf1c591a590d.png)

**_Below is my react code._**

`import React, {useEffect, useState} from 'react';`
`import mammoth from 'mammoth';`

`const DocViewer = () => {`
`const [data, setData] = useState(null);`

`useEffect(()=> {`
`  mammoth.convertToHtml({ path: 'https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx' })`
`      .then(function (result) {`
`         setData(result.value);`
`        console.log('message ', result.messages);`
`  })`
`  .done();`
`}, []);`
`  return (`
`    <>`
`      {data}`
`    </>`
`  );`
`}`

`export default DocViewer;`

My react version is
` "react": "^16.8.6",`
`"react-dom": "^16.8.6",`
`"react-scripts": "3.0.1",`

Can you please tell me why it is not working?

And also I'm getting warning message like

![image](https://user-images.githubusercontent.com/10355473/81181687-722dee80-8fca-11ea-8056-97f0fc918ba9.png)

![image](https://user-images.githubusercontent.com/10355473/81181735-85d95500-8fca-11ea-82b0-1d1cbf4e5c9b.png)

I also created a typescript file in below folder

**node_modules/mammoth/mammoth.d.ts**

Still, I'm getting a warning message.

**Comment by mwilliamson** [comment]
JavaScript running in the browser doesn't have direct access to the filesystem. You'll need to pass in the document as an ArrayBuffer.

**Comment by sadashivm** [comment]
Thanks for responding. 
I request to you can you please tell how to pass in the document as an ArrayBuffer with an example?
