### ISSUE TITLE
No paragraphs in tables

### ISSUE THREAD

**Issue by WernMich** [mwilliamson/mammoth.js#240]
Hello,

I can not find a solution for following issue:

MS Word creates paragraphs in table elements which I want to remove. Could anyone help me please how to realize this?

So:
```
<w:tc>
<w:tcPr>
<w:tcW w:w="1129" w:type="dxa"/>
</w:tcPr>
<w:p w14:paraId="11188381" w14:textId="7C4BC5C3" w:rsidR="00AD4BC3" w:rsidRDefault="00AD4BC3" w:rsidP="00AD4BC3">
<w:r>
<w:t>Mobile</w:t>
</w:r>
</w:p>
</w:tc>
```

Should result to:
`<td>Mobile</td>` 

If this is possible with a style map I would very much appreciate the correct mapping string.

Best regards,
Michael

**Comment by WernMich** [comment]
Sorry, I reflected on this issue and should use another approach.

**Comment by WernMich** [comment]
CSS could solve my issue too

**Comment by DuardoN** [comment]
@WernMich what approach do you use?

**Comment by WernMich** [comment]
@DuardoN I built my site with Gatsby.js using styled components. The issue I had was because of CSS, so I changed my component which displays the Word content. The paragraph is still created by mammoth.js but not "visible" anymore.

**Comment by DuardoN** [comment]
@WernMich interesting. Thanks for sharing, maybe I follow this approach.
