### ISSUE TITLE
Deleted new-line still appeared when "Track Changes" is enabled

### ISSUE THREAD

**Issue by rlimpraz** [mwilliamson/mammoth.js#243]
Step to reproduce:
1. Create an empty document.
2. Type two lines of text: "Test\nTest"
3. Turn on "Track Changes".
4. Delete "new-line" at the end of the first line to bring up the second line and append it the the first line. The text now becomes "TestTest".
5. Convert the document with Mammoth.

Expect: One single paragraph: &lt;p&gt;TestTest&lt;/p&gt;
Actual: There are 2 paragraphs:  &lt;p&gt;Test&lt;/p&gt;&lt;p&gt;Test&lt;/p&gt;

Platform:
MacOs High Sierra 10.13.6
node 12.12.0
[sample.docx](https://github.com/mwilliamson/mammoth.js/files/4700582/sample.docx)

I looked into the document.xml and saw w:rsidDel attribute at the w:p element instead of w:del. May be this is how MS Word marks the new-line as deleted.

**Comment by mwilliamson** [comment]
Thanks for the report, this should be fixed in the latest version.
