### ISSUE TITLE
Lists are wrapped in extra layers of lists, leading to many bullets as a prefix

### ISSUE THREAD

**Issue by siraj-samsudeen** [mwilliamson/mammoth.js#251]
Please find the test.docx which contains 2 types of lists. If you see the attached PDF (which is a printed version of the html generated by mammoth), you can see the extra layers of bullets added. 

* the operating system and version - Mac OS Catalina 10.15.6
* I ran mammoth test.docx test.html in iTerm Terminal
[test.docx](https://github.com/mwilliamson/mammoth.js/files/5185898/test.docx)
[test-output.pdf](https://github.com/mwilliamson/mammoth.js/files/5185897/test-output.pdf)

**Comment by mwilliamson** [comment]
In the original document, the items in the bullet list are marked up as being fourth-level, so Mammoth generates the list items as a fourth-level list. The simplest fix is to make sure that the bullets are marked up as top-level lists in the original document.

**Comment by siraj-samsudeen** [comment]
Hi Michael, thanks a lot for the immediate response. This is the first insight I have had in weeks to help me understand why this problem happens. I could not see that it is a fourth-level list. Where/How do I see it?

**Comment by mwilliamson** [comment]
I'm afraid I don't have a copy of Word to hand at the moment, but from [Microsoft's documentation](https://support.microsoft.com/en-us/office/change-bullet-indents-5ed8b9a0-d44c-4e9a-81b3-47c234e980d3):

> Change the indent for one bullet
> 
> 1. Click next to the text for the bullet you want to change.
>
> 1. On the Home tab, in the Paragraph group, select the arrow next to Multilevel List, and then select Change List Level.
> 
> 1. Select the level where you want the bullet. Each level has a different bullet style.

**Comment by siraj-samsudeen** [comment]
Thank you soooo much Michael. This was very helpful. We will now work on
fixing the problem in the source document.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything to change in Mammoth for this.
