### ISSUE TITLE
Unrecognised run style

### ISSUE THREAD

**Issue by constantinrosu** [mwilliamson/mammoth.js#255]
Hello,
I have a document ( [sample.docx](https://github.com/mwilliamson/mammoth.js/files/5327432/sample.docx) ) that when I am trying to convert it to HTML I am getting "Unrecognised run style" messages.
Here is the full list of warning messages:

![image](https://user-images.githubusercontent.com/25232548/95081228-ed363500-0721-11eb-942e-c232271851ca.png)

And here is how the document looks like:

![image](https://user-images.githubusercontent.com/25232548/95081633-7e0d1080-0722-11eb-8bab-8ee7fa689207.png)

The expected result is the HTML with proper H1-H6 formating.
I am using the latest version (v1.4.13) and for tesing I was using the demo page ( browser-demo\index.html).

Other details:
Win 10, Node(v12.18.1), Chrome(latest version)

**Comment by mwilliamson** [comment]
It looks like you've applied the headings as a run style rather than a paragraph style. To get the headings to appear as the appropriate elements, you'll need to change the original document to use the heading paragraph styles.

**Comment by constantinrosu** [comment]
Thank you for your feedback.

Yes, that is right. 
The Headings are used as run styles, but the document is a simulation of what some users are using. 
Telling them to update all their documents to use proper formatting is not an option due to the amount of documents.
So I was thinking if there is a way to make this work with mammoth. I tried to use custom Styles, but with no luck because also custom styles are applied on paragraph styles not on run styles.
I am still trying to find a solution.

**Comment by mwilliamson** [comment]
Another option would be to write a document transform that looks for paragraphs where all (or most) of the runs have the heading run style, and then assign the heading paragraph style to such paragraphs.

**Comment by mwilliamson** [comment]
Closing since I think document transforms can handle this case.

**Comment by boeckMt** [comment]
> Thank you for your feedback.
> 
> Yes, that is right. 
> The Headings are used as run styles, but the document is a simulation of what some users are using. 
> Telling them to update all their documents to use proper formatting is not an option due to the amount of documents.
> So I was thinking if there is a way to make this work with mammoth. I tried to use custom Styles, but with no luck because also custom styles are applied on paragraph styles not on run styles.
> I am still trying to find a solution.

I also have the same Issue getting

```bash
Unrecognised paragraph style: 'Title' (Style ID: Titel)
Unrecognised run style: 'Überschrift 2 Zchn' (Style ID: berschrift1Zchn)
```


I could fix them with a style-map

```txt
p[style-name='Title'] => h1
r[style-name='Überschrift 2 Zchn'] => h2
```
