### ISSUE TITLE
Use convertToHtml when the path is an external url

### ISSUE THREAD

**Issue by anrolmar** [mwilliamson/mammoth.js#257]
NodeJS v12.18.3
Language: Typescript

Could you tell me if I could use `mammoth.convertToHtml() `when the `path` is an external URL?

When I've used a link like `https://xxxxxx/yyyyy/zzzzz.docx"`, I get the error:

`ENOENT: no such file or directory, open 'https://xxxxxx/yyyyy/zzzzz.docx'"`

**Comment by mwilliamson** [comment]
On node.js, you can either pass the document as a local file using `path`, or as a buffer. In other words, you'll have to download the file.
