### ISSUE TITLE
Can we run it via PHP exec()?

### ISSUE THREAD

**Issue by fritexvz** [mwilliamson/mammoth.js#258]
I cannot figure it out either with declaration of own style-map how to add "class" or "id" to the HTML output? (so I can later modify it as needed)

Moreover, is there a way to "get" the horizontal alignment for the paragraph or heading from docx file?

For example I have paragraph with text-align center.

How to get it from docx and output on HTML?

<w:pPr>
<w:jc w:val="left"/>
</w:pPr>

<w:pPr>
<w:jc w:val="right"/>
</w:pPr>

<w:pPr>
<w:jc w:val="both"/>
</w:pPr>

<w:pPr>
<w:jc w:val="end"/>
</w:pPr>

In CSS later we can do it with:
text-align: right;
text-align: center;
text-align: justify; 

Is there a way to append a class name or id attribute to the specific HTML element (for example paragraph) which has it's own name ("Centered" - based on "Paragraph" style) in docx file, so we can through CSS style it later?

**Comment by fritexvz** [comment]
If we have document.xml like:
<w:pPr><w:jc w:val="center"/></w:pPr>
> <xml>...
<w:document>...
<w:body><w:p w:rsidR="0040560A" w:rsidRDefault="008C351B" w:rsidP="008C351B">**<w:pPr><w:jc w:val="center"/></w:pPr>**<w:bookmarkStart w:id="0" w:name="_GoBack"/><w:r><w:t>This is centered text</w:t></w:r><w:bookmarkEnd w:id="0"/></w:p><w:sectPr w:rsidR="0040560A"><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1417" w:right="1417" w:bottom="1417" w:left="1417" w:header="708" w:footer="708" w:gutter="0"/><w:cols w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>

Something like:
```
function readParagraphTextAlign(element) {
        return {
            left: element.attributes["w:left"],
            right: element.attributes["w:right"],
            center: element.attributes["w:center"]
        };
    }
```

**Comment by fritexvz** [comment]
Got it!

custom map like:
> p[style-name='Left'] => p.left
> p[style-name='Center'] => p.center
> p[style-name='Right'] => p.right

When I use your tool https://mike.zwobble.org/projects/mammoth/embed-style-map/, it adds the class attribute with the correct name to the output HTML.
Later on I can style them with CSS on the page.

Is there any other way to embed it via CLI command line when running on linux like:

> mammoth path/to/file.docx /output/path/to/output_file.html

**Comment by fritexvz** [comment]
Regarding the CLI and custom style-map embed:

> mammoth document.docx output.html --style-map=custom-style-map

--style-map=custom-style-map

Is the "custom-style-map" file and path to it? Can it be for example:

> /var/www/path/to/my-custom-style-map

**Comment by fritexvz** [comment]
Got it working!

**Comment by fritexvz** [comment]
Can that command be run from PHP exec()?, for example:
```
<?php
exec('mammoth /path/to/document.docx /path/to/output.html --style-map=/path/to/my_styles.map');
?>
```

Should I install the mammoth in the same file/directory?
What about CHMOD 777?
Do I have to add export HOME=/tmp/ && command?, like:

```
<?php
exec('export HOME=/tmp/ && mammoth /path/to/document.docx /path/to/output.html --style-map=/path/to/my_styles.map');
?>
```

Or maybe not the home, but the path for the output.html?

**Comment by mwilliamson** [comment]
I'm not sure exactly how `exec` in PHP works, but if you want to run Mammoth as a subprocess, the safest thing to do would probably be to refer to the full path. So, for instance, if the executable is installed at `/opt/mammoth/node_modules/.bin/mammoth`, you'd need to include that full path in your command.
