### ISSUE TITLE
Hope to keep all the styles of docx more perfect

### ISSUE THREAD

**Issue by yoyomule** [mwilliamson/mammoth.js#263]
Mammoth's converted html ignores some details, which makes it incompletely consistent with the original docx document. If I want to use it to make the docx document (including the table) as consistent as possible after the conversion, can it be done? I have been looking for such an open source solution, but it is not easy at the moment.

**Comment by mwilliamson** [comment]
Mammoth is designed to work with semantically marked up documents, for instance by mapping styles in the document to the appropriate CSS style. If you're looking for something to copy the exact formatting, I'm afraid that Mammoth isn't the right tool.
