### ISSUE TITLE
Can we display QRcode using mammoth

### ISSUE THREAD

**Issue by SureshKumar-Java** [mwilliamson/mammoth.js#264]
In my our work, I need to preview .docx file.
.docx file containts QRcode in one of the corner.

Is it possible to preview QRCode using Mammoth.

I am using Angular 6 in my project.

**Comment by mwilliamson** [comment]
If the QR code is contained as an image, then Mammoth should normally be able to include it, although there are likely ways of including images that Mammoth doesn't support. I'd say try it and see!
