### ISSUE TITLE
extractRawText strips tabs from psuedo-numbered list

### ISSUE THREAD

**Issue by miltonhowe** [mwilliamson/mammoth.js#265]
My documents consist of a heading, subheading and a numbered list, definition style, in this case questions and answers, but it could be anything.

The numbering is sometimes done using Word paragraph numbering formatting, and sometimes is done ad hoc with numbers and tabs.

The problem is that the tabs between the point numbers and the text in the input document are being stripped and no whitespace appears between the number and the text.
Input document looks like this:
```
TITLE

Blurb

1	Point one

		explanation 1
								
2	Point two

		explanation 2
```
output:
```
TITLE



Blurb



1Point one



explanation 1



2Point two



explanation 2
```
Using mammoth.browser.js in Angular 11 application.
Browser is Chrome Version 87.0.4280.141 (Official Build) (64-bit), also tested Brave
O/S Ubuntu 20.04, also tested 20.10

I also tried using convertToHtml, and it seems to have preserved the white space I need between the numbers and the text. However my preference is to use extractRawText as the HTML markup is extraneous and would need to be stripped out itself. I am eventually creating JSON.

**Comment by mwilliamson** [comment]
Could you provide a minimal example document?

**Comment by miltonhowe** [comment]
Thank you for your response.
Here is an example as requested.
[swallowed-tabs.docx](https://github.com/mwilliamson/mammoth.js/files/5840044/swallowed-tabs.docx)

**Comment by mwilliamson** [comment]
Thanks for the report, this should be addressed in master now.
