### ISSUE TITLE
Table Cell Styles

### ISSUE THREAD

**Issue by rovo79** [mwilliamson/mammoth.js#268]
In Word, when there is a Table, the user applies a Style to the data in the cell. In the Mammoth conversion, the style class is applied to a P element inside the Table TD cell. Is it possible to apply this class to the parent TD instead of the P element inside?

Currently doing this:
```
<table>
  <tr>
    <td><p class="underline">Eve</p></td>
    <td><p class="underline">Jackson</p></td> 
    <td><p class="underline">94</p></td>
  </tr>
</table>
```

Is it possible to do this:
```
<table>
    <tr>
      <td class="underline">Eve</td>
      <td class="underline">Jackson</td> 
      <td class="underline">94</td>
    </tr>
  </table>
```

**Comment by mwilliamson** [comment]
No, there's no way to do this at the moment. My suggestion would be to apply a post-processing step i.e. look for `td` elements that contain a single `p` element, and collapse them to a `td`.

**Comment by rovo79** [comment]
Greatly appreciate the clarity on that capability! 

Would a post-processing step be along the lines of me running my own JS against the table to make the adjustment?

**Comment by mwilliamson** [comment]
Yes, there are libraries you can use that can parse and manipulate HTML. If you're in the browser, you could alternatively use the DOM.

**Comment by mwilliamson** [comment]
Closing since I post-processing is hopefully a sufficient solution.

**Comment by rovo79** [comment]
> Yes, there are libraries you can use that can parse and manipulate HTML. If you're in the browser, you could alternatively use the DOM.

Do you know of any example libraries that allow CLI usage? I've been searching, but haven't found any except HTML TIDY, but it is limited in what it offers.
