### ISSUE TITLE
issue with convertToHtml() and mathtype Word

### ISSUE THREAD

**Issue by nguyenlam6292** [mwilliamson/mammoth.js#269]
Hi mammoth team,
I'm thankyou for your this library.
But I have a issue, I convert to hml from docx contain Mathjax. 
Example:    \(\frac{1}{f} = \frac{2}{{3{d_1}}} = \frac{2}{{3.20}} = \frac{1}{{30}} \Rightarrow f = 30cm\)
But, function return error "Unrecognised run style: 'MTConvertedEquation' (Style ID: MTConvertedEquation)".
Please help me for issue.
Many thank for your help!

**Comment by nguyenlam6292** [comment]
Please help me @mwilliamson

**Comment by mwilliamson** [comment]
Hello! I believe this is a duplicate of #83, so I'm closing this issue.
