### ISSUE TITLE
Error with issue with SPACE 

### ISSUE THREAD

**Issue by nguyenlam6292** [mwilliamson/mammoth.js#271]
I have a issue with import docx contain space.
I used function convertToHtml(). example:
foo            bar
After convert, this result:  <p>foo       bar</p>
But, when i show to broswer:              foo bar
I know normal space and non-breaking space is different. 
Can you help me to convertToHtml() to will result:   <p>foo &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bar</p>
Thankyou very much!

**Comment by nguyenlam6292** [comment]
@mwilliamson pleas help me. Many thank.

**Comment by mwilliamson** [comment]
Your best bet is either to put non-breaking spaces into the original document, which will then get converted to non-breaking spaces in the output, or to post-process the HTML to replace any runs of multiple spaces to a run of multiple non-breaking spaces.
