### ISSUE TITLE
Support HYPERLINK \l fields

### ISSUE THREAD

**Issue by grakz** [mwilliamson/mammoth.js#272]
- Create a new Word file
- Add a Heading 1 with Lorem ipsum
- Add a table of contents (this adds a hidden bookmark)
- Delete the table of contents
- Delete the heading (the hidden bookmark stays)
- Add two "Lorem ipsum dolor" paragraphs.
- Insert a bookmark in the second paragraph.
- Insert a link to the bookmark on the first word (Lorem) of the first paragraph.
- Insert a second link to the same bookmark on the third word (dolor) of the first paragraph.

When you convert with Mammoth.js the first link disappears, the second one works fine. All internal links that include the first word of a paragraph will just disappear.

**Comment by grakz** [comment]
Here you can see an example Word file that produces the issue:

[mammoth_js_issue_272.docx](https://github.com/mwilliamson/mammoth.js/files/6163148/mammoth_js_issue_272.docx)

**Comment by grakz** [comment]
This is the resulting html from the example word file:

`<p><a id="_Hlk66914645"></a>Second <a href="#short">words</a> of paragraphs seem to be fine. </p><p>First words of paragraphs cannot be internal links.</p><p><a id="short"></a>***</p><p>Jump is in the stars</p><p></p>`

Not the link on the first word is missing.

**Comment by grakz** [comment]
Actually, if you follow the steps to reproduce in the issue description, it works fine, it seems to be a side effect of the presence of the hidden anchor at the start of the example Word document.

**Comment by grakz** [comment]
Looking at the representation in document.xml, it seems that Word itself is actually encoding the link completely differently if its the first word of a paragraph:

`
<w:body>
		<w:p w14:paraId="4CA0DA06" w14:textId="15CF8FB2" w:rsidR="009261FB" w:rsidRDefault="009A0016" w:rsidP="009261FB">
			<w:bookmarkStart w:id="0" w:name="_Hlk66914645"/>
			<w:r>
				<w:t xml:space="preserve">Second </w:t>
			</w:r>
			<w:hyperlink w:anchor="short" w:history="1">
				<w:r>
					<w:rPr>
						<w:rStyle w:val="Hyperlink"/>							
					</w:rPr>
					<w:t>words</w:t>
				</w:r>
			</w:hyperlink>
			<w:r>
				<w:t xml:space="preserve"> of paragraphs</w:t>
			</w:r>
			<w:r w:rsidR="009261FB">
				<w:t xml:space="preserve"> </w:t>
			</w:r>
			<w:r>
				<w:t>seem to be fine</w:t>
			</w:r>
			<w:r w:rsidR="00EC4CAA">
				<w:t>.</w:t>
			</w:r>
			<w:r w:rsidR="009261FB">
				<w:t xml:space="preserve"> </w:t>
			</w:r>
		</w:p>
		<w:bookmarkEnd w:id="0"/>
		<w:p w14:paraId="51D8FCA8" w14:textId="2DB50D64" w:rsidR="009261FB" w:rsidRDefault="009261FB" w:rsidP="009261FB">
			<w:r>
				<w:fldChar w:fldCharType="begin"/>					
			</w:r>
			<w:r>
				<w:instrText xml:space="preserve"> HYPERLINK  \l "short" </w:instrText>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="separate"/>					
			</w:r>
			<w:r w:rsidR="009A0016">
				<w:rPr>
					<w:rStyle w:val="Hyperlink"/>						
				</w:rPr>
				<w:t>First</w:t>
			</w:r>
			<w:r>
				<w:fldChar w:fldCharType="end"/>					
			</w:r>
			<w:r>
				<w:t xml:space="preserve"> </w:t>
			</w:r>
			<w:r w:rsidR="009A0016">
				<w:t>words of paragraphs cannot be internal links</w:t>
			</w:r>
			<w:r w:rsidR="00EC4CAA">
				<w:t>.</w:t>
			</w:r>
		</w:p>
               (...)
</w:body>
`

**Comment by mwilliamson** [comment]
This should be supported in master now.

**Comment by grakz** [comment]
Thank you!
