### ISSUE TITLE
docx to markdown, innerHTML to react-markdown-editor-lite. tables not working.

### ISSUE THREAD

**Issue by xcondor** [mwilliamson/mammoth.js#273]
I have set styleMap:
`
styleMap: [
        "p[style-name='Date'] => h2.date:fresh",        
        "b => ",
        "p[style-name='Head'] => h1.header:fresh",
        "p[style-name='Hyperlink'] => a.source:fresh",
        "sdtContent => !"
      ]

this.readFileInputEventAsArrayBuffer(event, function(arrayBuffer) {
        mammoth.convertToMarkdown({arrayBuffer: arrayBuffer}, options)
            .then(_this.displayResult)
            .done();
  });
`
docx to markdown, the tables displayed p tag.   I used react-markdown-editor-lite
It's in textarea. 
![image](https://user-images.githubusercontent.com/3349113/114399811-e9ed9b80-9bd3-11eb-9658-cdb2446ba64a.png)

It's in editor preview
![image](https://user-images.githubusercontent.com/3349113/114399910-038ee300-9bd4-11eb-9d2a-76e499cdab21.png)

word content:
![image](https://user-images.githubusercontent.com/3349113/114400233-57013100-9bd4-11eb-9c71-db0cc515b3dc.png)

**Comment by mwilliamson** [comment]
Markdown support is deprecated. I'd suggest using Mammoth to convert to HTML and then using another tool to convert the HTML into Markdown.

**Comment by xcondor** [comment]
OK， thanks ！ I will to do it.
