### ISSUE TITLE
How to set many image use convertImage 

### ISSUE THREAD

**Issue by xcondor** [mwilliamson/mammoth.js#274]
I have parsed my document using Mammoth. 
Some pictures in the document have been converted to base64 format. 
I uploaded the pictures after conversion using base64ToBlob. 
But in the convertImage method, How can I replace the src of multiple images?

THANKS!

**Comment by mwilliamson** [comment]
Sorry, I'm not sure I understand your question. `convertImage` only handles one image at a time, so you can't use it to replace the `src` attribute of multiple images at once.

**Comment by xcondor** [comment]
In the parsing process, there are too many pictures of the parsing content.  You mean you can only replace one at a time, but there are multiple pictures in the article, do I need a loop to execute the convertImage method?

**Comment by mwilliamson** [comment]
`convertImage` is called by Mammoth for each image, rather than being a function that you would normally call yourself, so there shouldn't be a need to put it inside a loop.

**Comment by xcondor** [comment]
Thanks, I have been finished it.  I use a promise method to return the url to execute, and let it pass the picture and assign the value in turn.
