### ISSUE TITLE
To Confirm: Is convertToMarkdown deprecated?

### ISSUE THREAD

**Issue by NL33** [mwilliamson/mammoth.js#275]
Thanks for this awesome project? I just tested it out in an electron app, and it seems like `convertToMarkdown` works fine. However, the `readme` here says that markdown support is deprecated. 

So, just to confirm: Is support for `convertToMarkdown` deprecated?

**Comment by mwilliamson** [comment]
Yes, `convertToMarkdown` is deprecated.

**Comment by NL33** [comment]
Thanks for the fast reply.
