### ISSUE TITLE
"Arbitrary Code Execution" vulnerability and Buffer() is deprecated

### ISSUE THREAD

**Issue by NL33** [mwilliamson/mammoth.js#276]
(Note: I mention two issues here. I thought that would be better so as not to crowd the issues reporting. But I can separate these into two different reported issues if you prefer.)

**Versions:**
mammoth: ^1.4.16
node: 14.16.1
npm: 6.14.12
electron: 12.0.2

**Issue Summary:**

I am putting together an electron app, and Mammoth is working great in testing, but I am having these two issues:

**1.** After running `$ npm install mammoth ` npm reports `3 high severity vulnerabilities`:
```
Vulnerability: Arbitrary Code Execution (High)
Package: underscore
Patched in: >=1.12.1
Dependency of: mammoth
More info: https://npmjs.com/advisories/1674
Path: 3 paths:
mammoth > lop > duck > underscore
mammoth > lop > underscore
mammoth > underscore
```

Running `$ npm audit fix` does not fix these vulnerabilities. 

Is there a fix available?
***

**2.** Running mammoth code in an electron renderer process produces this warning:

`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Example code that produces this warning:
 
renderer.js:
```
var mammoth = require("mammoth")

convertWord()

function convertWord(){
    mammoth.convertToHtml({path: 'cool-file.docx'}).then(function(result){
      console.log(result.value)   //works fine
      console.log(result.messages) //no messages 
   })
}
```

If I run the same mammoth code in the main process, I do not get this warning.

Is there something I can do to run the code in the renderer and remove this warning?

**Comment by NL33** [comment]
Thanks for the info. 

--Can I remove the underscore function that causes the vulnerability? Just want to be sure it won't cause issues in production.

--The buffer warning only seems to appear in the renderer, not main process. Does that give clues as to what's going on?

**Comment by mwilliamson** [comment]
> Thanks for the info.
> 
> --Can I remove the underscore function that causes the vulnerability? Just want to be sure it won't cause issues in production.

That shouldn't be an issue in principle.

> --The buffer warning only seems to appear in the renderer, not main process. Does that give clues as to what's going on?

I'm not familiar with how Electron works, so I'm afraid I don't have particular insight to give.

**Comment by NL33** [comment]
Ok. Thanks for the info.

**Comment by kensnyder** [comment]
@mwilliamson Would you be willing to accept a PR that replaces underscore with lodash equivalents? I know it is more than a find and replace because some functions have slightly different names and behaviors.

In my case, the npm audit results are ultimately something I have to address; either by a PR or a fork:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/102264/118526840-e337d400-b6fd-11eb-98d2-8eac37e70769.png">

Using npm-check-updates (ncu) I can see there are a lot of old dependencies. 

<img width="247" alt="image" src="https://user-images.githubusercontent.com/102264/118527158-3f025d00-b6fe-11eb-81e9-92ec1f1d7872.png">

If you are open to larger PRs, I would be willing to dive in and see what code changes would be necessary to update those.

**Comment by mwilliamson** [comment]
The latest version should have an updated version of underscore without the vulnerability. I don't think the other dependencies affect production, so shouldn't be an immediate issue.

**Comment by kensnyder** [comment]
Ah. Your comment led me to find `npm audit --production` which indeed has 0 vulnerabilities. Thanks!

![image](https://user-images.githubusercontent.com/102264/118534331-57767580-b706-11eb-9f3a-9dbd9fb60ba7.png)

**Comment by mwilliamson** [comment]
Closing since the code that's actually used in production has no vulnerabilities according to npm audit.
