### ISSUE TITLE
Unrecognised paragraph style: 'List Paragraph'

### ISSUE THREAD

**Issue by drawmoon** [mwilliamson/mammoth.js#277]
When I used the `mammoth.convertToHtml` method to convert a word document to html, an error occurred, causing the conversion to fail, error message: **Unrecognised paragraph style: 'List Paragraph' (Style ID: a3)**

**Word content is as follows:**

![图片](https://user-images.githubusercontent.com/41671372/118476883-a6410100-b740-11eb-929d-4e73c11a7a1b.png)

**Sample File**

[sequence.docx](https://github.com/mwilliamson/mammoth.js/files/6492991/sequence.docx)

**Version**
system: windows 10 and centos 7
nodejs: 14.16.1
mammoth: 1.4.16

Thanks!!!

**Comment by mwilliamson** [comment]
How did the conversion fail? Did it not produce any HTML, or did the generated HTML differ from what you expected?

**Comment by drawmoon** [comment]
Oh, the error made me think it failed. In fact, it can generate html. 

Thank you very much for your reply
