### ISSUE TITLE
Preformatted Text

### ISSUE THREAD

**Issue by atdd-bdd** [mwilliamson/mammoth.js#279]
I have a Preformatted style in Word.   I apply it to code samples.    I would like it to be converted to the Wordpress Preformatted  style.      

What happens now is that it is not recognized.   That's okay, I can handle doing a little reformatting in Wordpress.   But all the extra spaces are taken out.   There are lots of these.    

I like your conversion program.   But this issue is keeping me from using it for many of my blog posts.    

An example.   This snippet was Preformatted in Word.   The vertical bars lined up.   But all the extra spaces got taken out:

 Scenario: Transfer money to another account

Given customers have accounts

| Customer | Balance |

| Sam | $100 |

| Bill | $50 |

**Comment by mwilliamson** [comment]
You can use a style mapping to map the Word style to an HTML `pre` element, or any other element that preserves whitespace with the styles on your target page. The README has more details on how to set up style maps.

**Comment by mwilliamson** [comment]
Closing since I think the question's been answered.
