### ISSUE TITLE
Best way to improve performance for converting multiple documents?

### ISSUE THREAD

**Issue by NL33** [mwilliamson/mammoth.js#280]
**Versions**

mammoth: "^1.4.17"
electron:  "^12.0.2"
node: "14.16.1
mac OS: 11.1

**Issue**

I am using `mammothjs` in an electron app to convert multiple Microsoft word docs. Once the word docs start to get longer (say, 30 pages+) and there start to be a number of them (say, 20+), I am noticing a large slow down in performance. 

For example: as a test, analyzing 25 word docs, each of 50 page length (81kb each in word form), takes 30 seconds+.

I'm hoping to make things as performant as possible. Is there a strategy to do that?

**Example Code**

Current Setup: I'm hoping to run the conversion of each word doc with mammoth in parallel, but I also need some way to know when mammoth has completed for all docs. This is how I am doing this as of now:

```
startFunction()

function startFunction(){
    wordPathArray = [$ARRAY OF THE PATHS FOR ALL WORD DOCS TO BE CONVERTED$]

    let promises = []
    for (let i = 0; i < wordPathArray.length; i++) {
        promises.push(mammothFunction(wordPathArray[i]))
     }

    Promise.all(promises).then(function (result) {
        console.log('Completed!')
    })
}

function mammothFunction(wordPath) {
    return new Promise((resolve, reject) => {
        mammoth.convertToHtml({ path: wordPath }).then(function (result) {
            let convertedDoc = result.value
           resolve(convertedDoc)
        })
    })
}

```

This all works, except for performance does not seem great. Is there a more performent way to do this?

**Comment by mwilliamson** [comment]
Nope, that's the way to use the API, so short of optimising the library itself, I don't think there's much you can do.

**Comment by NL33** [comment]
Ok. Thanks for your reply.

**Comment by mwilliamson** [comment]
Closing for now since I think the question's been answered.

**Comment by NL33** [comment]
Yes. Thanks for your help.
