### ISSUE TITLE
Unrecognised paragraph style

### ISSUE THREAD

**Issue by anonymousant** [mwilliamson/mammoth.js#282]
I'm getting a bunch of 'Unrecognised paragraph style' warnings when I try to parse a docx file using mammothjs. I'm using it in an Electron (Node) environment on Windows 10.

I've a had a look in the styles.xml (in the docx zip that is) and all the styles that are 'unidentified' seem to be present. I'm also a little confused about how the warning message does seem to correctly identify the 'Style ID' of the supposedly 'unidentified style'.

My code looks like this:

```
var options = {
    styleMap: [
        "p[style-name='Title'] => h1.act-title:fresh",
        "p[style-name='toc 1'] => p.toc1:fresh",
        "p[style-name='toc 2'] => p.toc2:fresh",
        ]
}
mammoth.convertToHtml({path: this.legislation_path, options});
.then((result)=>{
        target_div.innerHTML = result.value;
        console.log(result.messages);
}
.done();
```
These give the following warning messages:

```
Unrecognised paragraph style: 'Title' (Style ID: Title)
Unrecognised paragraph style: 'toc 1' (Style ID: TOC1)
Unrecognised paragraph style: 'toc 2' (Style ID: TOC2)
```

To be clear, the warning messages appear whether or not I include a style map.

It would really help to learn why some styles aren't recognized. At the moment I'm not even sure if these 'unrecognised paragraph style' messages are related to my failing style map.

Except for this issue, the html output is looking fine.

Any clues?

**Comment by anonymousant** [comment]
Uhhhhhh sorry... Was just a syntax error.

I wrote:

```mammoth.convertToHtml({path: this.legislation_path, options});```

When I should have written:

```mammoth.convertToHtml({path: this.legislation_path}, options);```

I'll just leave this here in case it helps anyone. 

Woops :(

**Comment by DanieleSidoti** [comment]
Sorry, but I'm reopening this thread because I have the same problem, here is my code:

`await mammoth
      .convertToHtml({ path: docxPath }, options)
      .then(async (result) => {
        // Ottieni l'HTML dal risultato di Mammoth

        console.log('result', result);
        
      })
      .catch((error) => {
        console.error('Errore durante la conversione:', error);
      });`

result returns me these warnings:

`messages: [
    {
      type: 'warning',
      message: "Did not understand this style mapping, so ignored it: p[style-name='TextCenter'] => p:fresh { text-align: center; line-height: 2px; }\n" +
        'Error was at character number 38: Expected end but got whitespace'
    },
    {
      type: 'warning',
      message: "Did not understand this style mapping, so ignored it: p[style-name='TextJustify'] => p:fresh { text-align: justify; line-height: 2px; }\n" +
        'Error was at character number 39: Expected end but got whitespace'
    },
    {
      type: 'warning',
      message: "Unrecognised paragraph style: 'TextCenter' (Style ID: TextCenter)"
    },
    {
      type: 'warning',
      message: "Unrecognised paragraph style: 'Normale1' (Style ID: Normale1)"
    },
    {
      type: 'warning',
      message: "Unrecognised paragraph style: 'TextJustify' (Style ID: TextJustify)"
    },
    {
      type: 'warning',
      message: "Unrecognised paragraph style: 'Testo predefinito' (Style ID: Testopredefinito)"
    },
    {
      type: 'warning',
      message: "Unrecognised paragraph style: 'ElencoPuntatoSecondoLivello' (Style ID: ElencoPuntatoSecondoLivello)"
    }
  ]`

if I pass "options" blank obviously the first two warnings do not exist.

Can anyone help me?
Thank you very much
