### ISSUE TITLE
Is there a way to have the html *not* be condensed?

### ISSUE THREAD

**Issue by NL33** [mwilliamson/mammoth.js#283]
Hi There. Right now, when converting a word doc to html with `mammothjs`, the html code that results is "condensed"--by which I mean there are no spaces or line breaks between tags. So, while normally formatted html code has line breaks and spaces, the mammoth html result does not. (sorry for restating an obvious point--just trying to set out the issue I am after in a simple way.)

**Example "non-condensed" html:**
```
<p>Here is a new line of text</p>
<p>
   <strong>Here is some bold text</strong>
</p>
<table>
     <tr>
         <td>
            <p>Column 1</p>
         </td>
...
```

**How mammoth shows this code:**

`<p>Here is a new line of text</p><p><strong>Here is some bold text</strong></p><table><tr> <td><p>Column 1</p></td>...`

I understand a benefit of this is smaller file sizes, but the condensed format is making it harder for me to do some parsing. 

Is there a way to have the html code output NOT be condensed? (like in the example "non-condensed" html above.)  I can get there in VS code if, when in the document, I select "format document" from the VS code options, but I would need a way to do this programmatically.

I have tried the following:

```
 var options = {
        styleMap: [
            "p[stylename = 'p'] => pre: separator('\n')"
        ]
 };

 mammoth.convertToHtml({ path: filePath }, options).then(function (result) {
       ...
 }
```

But this has not worked (it has not changed any of the formatting).

**Comment by mwilliamson** [comment]
I'd suggest using another library to parse and pretty print the generated HTML.

**Comment by NL33** [comment]
Ok. Thanks.

**Comment by alcabon** [comment]
Hi, 

Mammoth.js is a really great tool with a sophisticated code.

A workaround is to make the blank lines visible with "pilcrows" or "paragraph marks"  ( ¶ ) that you remove when you get the condensed html code.  This pilcrows can be added with a simple Word macro but it is possible in mammoth.js directly. 

It is a workaround and there are pilcrows added inside tables but it is not blocking. All the cases are not covered probably.

`
    function convertParagraph(element, messages, options) {
        return htmlPathForParagraph(element, messages).wrap(function() {
            var content = convertElements(element.children, messages, options);
            if (ignoreEmptyParagraphs) {
                return content;
            } else {
                console.log('content:' + JSON.stringify(content));

                //blank line with tabs and spaces: [{"type":"text","value":"\t"},{"type":"text","value":"   "},{"type":"text","value":"\t"},{"type":"text","value":"   "},{"type":"text","value":"\t"}]
                // page break: [{"type":"element","tag":{"tagName":"strong","tagNames":{"strong":true},"attributes":{},"fresh":false},"children":[]}

                let blank = true;
                if (content.length > 0) {
                    for (let o of content) {
                       if (o.type == 'text') { let v = o.value.trim(); if (v != '' && v != '\t') blank = false; }
                       else if (o.type == 'element') { if (o.children.length > 0) blank = false; }  
                       else blank = false;
                    }
                }  
                if (content.length ==0  || blank) {
                     return [Html.forceWrite].concat(Html.text("¶"));
                }
                return [Html.forceWrite].concat(content);
            }
        });
    }`
