### ISSUE TITLE
Add 1 newline (not 2) with extractRawText?

### ISSUE THREAD

**Issue by NL33** [mwilliamson/mammoth.js#284]
If you use `mammoth.extractRawText(input)`, it adds two newlines after each paragraph, per the `readme`. 

Is it possible to customize this so that only one newline (not two) is added instead?

**Comment by mwilliamson** [comment]
Not at the moment, no.

**Comment by mwilliamson** [comment]
Closing since customisation is unlikely to be added the raw text extraction.
