### ISSUE TITLE
Can't find end of central directory : is this a zip file ?

### ISSUE THREAD

**Issue by zhanlinhan** [mwilliamson/mammoth.js#285]
![image](https://user-images.githubusercontent.com/17825602/124087787-f2dc6380-da84-11eb-83b0-b21591095590.png)

Is there any guys know how to resolve this issuse?

有没有大佬知道怎么这个咋搞啊～～help～

**Comment by zhanlinhan** [comment]
![image](https://user-images.githubusercontent.com/17825602/124089250-4f8c4e00-da86-11eb-8a0d-55a1c32e7a2c.png)

**Comment by mwilliamson** [comment]
It looks like you're passing in a `Uint8Array`, whereas Mammoth expects an `ArrayBuffer`.

**Comment by zhanlinhan** [comment]
> It looks like you're passing in a `Uint8Array`, whereas Mammoth expects an `ArrayBuffer`.

look at my methods2, It`s `ArrayBuffer` , when I using methods2, it`s throw the same error

and I just changed `Uint8Array` to `ArrayBuffer`, it does`t work

**Comment by NL33** [comment]
> Can't find end of central directory : is this a zip file ?

FYI: I get this error when mammoth tries to operate on a doc that has the "docx" extension, but is not an actual word doc. 

For me, this happens when mammoth tries to work on the separate, hidden file that word creates when I open a word doc. So:
When I open a word doc, like `cool-doc.docx`, word creates a separate file in the same folder, `$~ool.doc.docx`. That separate file is hidden, but I can view it on mac with `shift+command+.` If I am running mammoth on a loop of different documents, and one of those `$_...` docs gets included, I get this error.

**Comment by mwilliamson** [comment]
> > It looks like you're passing in a `Uint8Array`, whereas Mammoth expects an `ArrayBuffer`.
> 
> look at my methods2, It's `ArrayBuffer` , when I using methods2, it throws the same error
> 
> and I just changed `Uint8Array` to `ArrayBuffer`, it does't work

If you mean that you're calling `new ArrayBuffer(xhr.response)`, then I don't think that's quite right either -- `xhr.response` should, if I've followed your code correctly, already be an `ArrayBuffer`. I'd suggest making sure that array buffer is actually a zip, perhaps by using JSZip directly.

**Comment by zhanlinhan** [comment]
> > > It looks like you're passing in a `Uint8Array`, whereas Mammoth expects an `ArrayBuffer`.
> > 
> > 
> > look at my methods2, It's `ArrayBuffer` , when I using methods2, it throws the same error
> > and I just changed `Uint8Array` to `ArrayBuffer`, it does't work
> 
> If you mean that you're calling `new ArrayBuffer(xhr.response)`, then I don't think that's quite right either -- `xhr.response` should, if I've followed your code correctly, already be an `ArrayBuffer`. I'd suggest making sure that array buffer is actually a zip, perhaps by using JSZip directly.

Thanks for replay. I just solved this issue
in my first scrrenshot, I used a local file address, but when I use a input tag and set it's type to `file` to choose a local document file, I get a success

![image](https://user-images.githubusercontent.com/17825602/124531516-43ffa500-de41-11eb-8ebb-7b1a16a2fa8a.png)
![image](https://user-images.githubusercontent.com/17825602/124531712-a789d280-de41-11eb-81a1-6c382f27a4a5.png)

**Comment by zhanlinhan** [comment]
resolved
已解决～

**Comment by zhanlinhan** [comment]
您好：   您的邮件我已收到，我会尽快阅读并回复您！

**Comment by Guardwu2015** [comment]
![企业微信截图_16563213519836](https://user-images.githubusercontent.com/15966814/175905271-4568609e-786c-45e4-9e77-efdbfe17bc9d.png)
我是这样使用的时候报错了

**Comment by Guardwu2015** [comment]
if (binaryData && documentType?.indexOf("Word") !== -1) {
            const blob = new Blob([binaryData], {
                type: "application/octet-stream",
            });
            const reader = new FileReader();
            reader.readAsArrayBuffer(blob);
            reader.onload = (e) => {
                const buffer = e?.target?.result;

                mammoth
                    .convertToHtml({ arrayBuffer: buffer })
                    .then((result: any) => {
                        console.log("result", result);
                    })
                    .done();
            };
        }
        我是这样调用的时候报错了

**Comment by Guardwu2015** [comment]
问一下，大佬读取的是word的二进制文件吗



在 2022-06-27 17:38:33，"zhanlinhan" ***@***.***> 写道：

var files = this.wordFile || null;
if (!files) return;
var file = files;
var reader = new FileReader();
reader.onloadend = () => {
var arrayBuffer = reader.result;
mammoth
.convertToHtml({ arrayBuffer: arrayBuffer })
.then((resultObject) => {
this.vHtml = resultObject.value;
console.log(resultObject.value);
});
};
reader.readAsArrayBuffer(file);

这是我能正常预览的方法，一年前的东西了 我也忘得差不多了 你参考一下吧

**Comment by zhanlinhan** [comment]
> 问一下，大佬读取的是word的二进制文件吗 在 2022-06-27 17:38:33，"zhanlinhan" ***@***.***> 写道： var files = this.wordFile || null; if (!files) return; var file = files; var reader = new FileReader(); reader.onloadend = () => { var arrayBuffer = reader.result; mammoth .convertToHtml({ arrayBuffer: arrayBuffer }) .then((resultObject) => { this.vHtml = resultObject.value; console.log(resultObject.value); }); }; reader.readAsArrayBuffer(file); 这是我能正常预览的方法，一年前的东西了 我也忘得差不多了 你参考一下吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我用的elementUI的上传组件，before-upload里获取的文件本身赋值给this.wordFile

**Comment by Guardwu2015** [comment]
了解了，我现在是从一个dxf文件中读取的word文档的二进制数据，想得到html结构，还是会报错，可能走不通



在 2022-06-28 11:17:06，"zhanlinhan" ***@***.***> 写道：

问一下，大佬读取的是word的二进制文件吗 在 2022-06-27 17:38:33，"zhanlinhan" @.> 写道： var files = this.wordFile || null; if (!files) return; var file = files; var reader = new FileReader(); reader.onloadend = () => { var arrayBuffer = reader.result; mammoth .convertToHtml({ arrayBuffer: arrayBuffer }) .then((resultObject) => { this.vHtml = resultObject.value; console.log(resultObject.value); }); }; reader.readAsArrayBuffer(file); 这是我能正常预览的方法，一年前的东西了 我也忘得差不多了 你参考一下吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

我用的elementUI的上传组件，before-upload里获取的文件本身赋值给this.wordFile

**Comment by Guardwu2015** [comment]
收到，谢谢哈



在 2022-06-27 17:38:33，"zhanlinhan" ***@***.***> 写道：

var files = this.wordFile || null;
if (!files) return;
var file = files;
var reader = new FileReader();
reader.onloadend = () => {
var arrayBuffer = reader.result;
mammoth
.convertToHtml({ arrayBuffer: arrayBuffer })
.then((resultObject) => {
this.vHtml = resultObject.value;
console.log(resultObject.value);
});
};
reader.readAsArrayBuffer(file);

这是我能正常预览的方法，一年前的东西了 我也忘得差不多了 你参考一下吧

**Comment by zhanlinhan** [comment]
您好：   您的邮件我已收到，我会尽快阅读并回复您！
