### ISSUE TITLE
Convert tab-space  to three &nbsp; in HTML result

### ISSUE THREAD

**Issue by russkiy78** [mwilliamson/mammoth.js#286]
It would be good if mammoth could convert  tab-space (I mean symbol, which insered then you press a "tab" button on keyboard)  in docx file to something in HTML result. 

Is there a conversion style for it?

**Comment by mwilliamson** [comment]
Tabs are converted to tab characters in the HTML output.

> Is there a conversion style for it?

No, so I'd suggest you could post-process the HTML if you need to replace the tabs with something else.
