### ISSUE TITLE
Why you loved 'make' to manage js project?

### ISSUE THREAD

**Issue by cossbow** [mwilliamson/mammoth.js#288]
If you're reporting a bug or requesting a feature, please include:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using

**Comment by mwilliamson** [comment]
it does the job!
