### ISSUE TITLE
make: *** No rule to make target `setup'.  Stop.

### ISSUE THREAD

**Issue by bokster** [mwilliamson/mammoth.js#293]
This is probably an issue for a newbie. When I ran 'make setup' in terminal to try out mammoth is to use the web demo,  I got ``*** No rule to make target `setup'.  Stop.``

Then, when I open `browser-demo/index.html` in a web browser and uploaded a  .docx file, nothing happens.

When did I do wrong?

**Comment by mwilliamson** [comment]
I've no idea, I'm afraid.

If you create a minimal makefile with a `setup` target that does something simple like echoing a message, can you run it with `make setup`?

**Comment by mwilliamson** [comment]
Closing since I'm not sure there's anything I can do without more information.
