### ISSUE TITLE
Error: Could not find file in options when converting a document 

### ISSUE THREAD

**Issue by TheShinyBacon** [mwilliamson/mammoth.js#295]
Hello !
Sorry to bother, i'm probably doing something wrong but I get this error when converting a docx from an arraybuffer

I'm using angular 10 and I convert the file via the file-to-array-buffer module
the array buffer seems okay since it's the same size as the file

What am I trying to do ? 
Converting a docx to html in a webpage using an html input file element to select the file

Thank you in advance for your help

**here is my function :**
```
convertDocument(event):void{
      if (this.fileToUpload!=null){
          fileToArrayBuffer(this.fileToUpload).then((data) => {
          console.log(data);
          
           convertToHtml({ ArrayBuffer : data})
            .then(function(result){
            var html = result.value; // The generated HTML 
            console.log(html);
            var messages = result.messages; // Any messages, such as warnings during conversion 
        })
        .done();
        })
    }
  }
```

**Stack :** 

> ERROR Error: Could not find file in options
>     at Object.openZip (mammoth.browser.js:108)
>     at convert (mammoth.browser.js:2442)
>     at convertToHtml (mammoth.browser.js:2430)
>     at editfiche.component.ts:105
>     at ZoneDelegate.invoke (zone-evergreen.js:364)
>     at Object.onInvoke (core.js:27495)
>     at ZoneDelegate.invoke (zone-evergreen.js:363)
>     at Zone.run (zone-evergreen.js:123)
>     at zone-evergreen.js:857
>     at ZoneDelegate.invokeTask (zone-evergreen.js:399)
>     at Object.onInvokeTask (core.js:27483)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:398)
>     at Zone.runTask (zone-evergreen.js:167)
>     at drainMicroTaskQueue (zone-evergreen.js:569)
>

**Comment by mwilliamson** [comment]
You'll need to pass the array buffer in using the `arrayBuffer` property, not `ArrayBuffer` i.e. `convertToHtml({ arrayBuffer : data})`

**Comment by TheShinyBacon** [comment]
Thank you very much !!
I feel so stupid right now....
