### ISSUE TITLE
Read styles from styles.xml file

### ISSUE THREAD

**Issue by ravinduramesh** [mwilliamson/mammoth.js#297]
I tried to convert the attached docx file but the style tree contains null values. The reason is all the styles are in the styles.xml file. Is it possible to read styles.xml file and retrieve styles from it for content in document.xml?

[mammoth style issue.docx](https://github.com/mwilliamson/mammoth.js/files/7427740/mammoth.style.issue.docx)

**Comment by mwilliamson** [comment]
Closing since Mammoth appears to be working correctly, but do say if you think I'm mistaken.
