### ISSUE TITLE
How can we use a style tag for a table.

### ISSUE THREAD

**Issue by ssudhak** [mwilliamson/mammoth.js#299]
Hi,

I am facing an issue with the tables. Incase if we need to catch an table with a style defined, how we can we do that.

Say if i need to catch 'body-st' table styles and move it to a div. Can we write like this. I tried it, but not working
table[style-name='body-st'] => div.body-st > table:fresh

If i remove the style from the table, here it works
table => div.body-st > table:fresh

But in my word doc, i have many styles like 'body-st' and each of the tables coming in that should go to respective div containers. Hope its clear.

Let me know if i need to provide more details. This issue looks same as my requirement - https://github.com/mwilliamson/python-mammoth/issues/46

**Comment by mwilliamson** [comment]
It sounds like the name of the style is failing to match. Are you sure that's the name of the style, rather than the ID?

If you have a minimal example document, I can take a look, but otherwise there's probably not much I can do to help.

**Comment by ssudhak** [comment]
Yeah that can be an issue, not sure if i am confused with style and ID. Attaching a same here
[cp-test.docx](https://github.com/mwilliamson/mammoth.js/files/7540657/cp-test.docx)
.
Tried creating a new style 'isi-table', but that also not working.

Couple of examples that i have used here.
p[style-name='body-isi'] => div."""+isi_body+""" > p:fresh
table[style-name='isi-table'] => div."""+isi_body+""" > table:fresh

**Comment by mwilliamson** [comment]
In your example, the table has the style "Table Grid". You'd either need to match that style (if that's the style you want), or create a new table style called "isi-table" and apply it to the relevant table.

**Comment by ssudhak** [comment]
Hi @mwilliamson , I have defined a new style "isi-table". Please see the screenshot. Hope I am referring the correct one.
<img width="1109" alt="Screen Shot 2021-11-15 at 4 27 55 PM 1" src="https://user-images.githubusercontent.com/7603029/141856665-f6bc9ece-b86e-490d-b772-3398e0671e45.png">

Let me know if you are not able to see the same.

**Comment by mwilliamson** [comment]
isi-table is a paragraph style, not a table style.

**Comment by ssudhak** [comment]
@mwilliamson thanks a lot that helps. Really appreciate your help on this.
