### ISSUE TITLE
Handle w:tab

### ISSUE THREAD

**Issue by jgrund** [mwilliamson/mammoth.js#3]
Thanks for this module, I am finding it very useful.

Right now w:tab is not handled and shows up as an error when parsing.

Add a w:tab property to  xmlElementReaders in document-xml-reader.js.

**Comment by nguyenlam6292** [comment]
I imported file word with "tab", and use convertToHtml(). But, response "tab" show "\t", I want show 1 tab = 4 space.
Please help me for issue, I'm using version 1.4.15.
Thank you!
