### ISSUE TITLE
support add id attribute for images

### ISSUE THREAD

**Issue by gowelaine** [mwilliamson/mammoth.js#310]
Hi,
Is it possible to add attribute id or class on img tag during the ImageConverter process?
So it's easy to identify each image after converter is done. for instance,

[image id="image-vangogh" src="/img/html/vangogh.jpg" alt="Van Gogh, Self-portrait"]
Right now it seems only alt and src can be generated.

**Comment by mwilliamson** [comment]
If I remember correctly, any attributes (including IDs and classes) you return from the function passed into `imgElement` will be included in the HTML output.
