### ISSUE TITLE
Mammoth not covreting correctly

### ISSUE THREAD

**Issue by gadji9** [mwilliamson/mammoth.js#311]
My document: 
[Invoice - Tarif Odin Dolznik (1).docx](https://github.com/mwilliamson/mammoth.js/files/7997467/Invoice.-.Tarif.Odin.Dolznik.1.docx)
ect

And i expected the same as document but got: 
![exp](https://user-images.githubusercontent.com/78681462/152412948-1a25295f-4124-4a30-b015-145d32249247.PNG)

All offsets and colours disapeared. 

Using mammoth ^1.4.19

node: v14.4.0

**Comment by mwilliamson** [comment]
Mammoth is designed to convert the semantic information in the document into HTML, for instance by converting Word styles into an appropriate HTML element and CSS class. If you're looking for a tool that copies the exact formatting, such as colour, then Mammoth isn't the right tool for the job.
