### ISSUE TITLE
Cancellable handle

### ISSUE THREAD

**Issue by chiptoe** [mwilliamson/mammoth.js#312]
Idea:
Consider we want to start converting 2nd document and cancel converting prev document.
```
var handle = mammoth.convertToHtml(opts, callback)
setTimeout(() => handle.cancel(), 900)
```
Callback is called with cancelled param, immediately when cancel() is called before finish.
Cancel should cause internally skiping all subsequent procesessing - iterations/tranformations/parsing/img loadings,etc.

This relates to fact that promise in JS is not really cancellable.
This is similar to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort
Or is there other way I can implement this behavior?

**Comment by mwilliamson** [comment]
I'm not sure there's a good way of implementing this without quite extensive changes to how Mammoth is written, so it's unlikely to be supported. Sorry!

**Comment by huangjixin1997** [comment]
Here's the method works in my code, you can consider whether to use it after testing.

`mammoth.js` depends on ` bluebird`, [Bluebird](http://bluebirdjs.com/docs) is a fully featured promise library.
`bluebird ` has a [cancel api](http://bluebirdjs.com/docs/api/cancel.html). The cancellation feature is by **default turned off**.
You can add the following to [line 3 of the file (`lib/promises.js`)](https://github.com/mwilliamson/mammoth.js/blob/master/lib/promises.js#L3) or line 2632 of the file `mammoth.browser.js` to enable it:
```javascript
var _ = require('underscore')
var bluebird = require('bluebird/js/release/promise')()
// Add the following line to enable cancellation
bluebird.config({ cancellation: true })

exports.defer = defer
exports.when = bluebird.resolve
exports.resolve = bluebird.resolve
exports.all = bluebird.all
.....
```

Now you can cancel.
```js
const handle = mammoth.convertToHtml(input, opts)

// ...
// do something

handle.cancel()
```

**Cancelling a promise simply means that its handler callbacks will not be called.**
[.cancel()](http://bluebirdjs.com/docs/api/cancel.html) is synchronous.
For details, see http://bluebirdjs.com/docs/api/cancellation.html#what-about-promises-that-have-multiple-consumers

Similarly, `bluebird ` has a [timeout api](http://bluebirdjs.com/docs/api/timeout.html), You can also test it.
