### ISSUE TITLE
Add transformDocument to Options type

### ISSUE THREAD

**Issue by vladblindu** [mwilliamson/mammoth.js#315]
If you're reporting a bug or requesting a feature, please include:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using

**Comment by vladblindu** [comment]
This is a really small issue. 
Options lacks "transformDocument" as key in the index.d.ts type definition file, typescript keeps complaining about it. It's one line of code:

```
interface Options {
    styleMap?: string | Array<string>;
    includeEmbeddedStyleMap?: boolean;
    includeDefaultStyleMap?: boolean;
    convertImage?: ImageConverter;
    ignoreEmptyParagraphs?: boolean;
    idPrefix?: string;
  + transformDocument?: Function
}
```

This is the [permalink](https://github.com/mwilliamson/mammoth.js/blob/fc1647e93b9ed151eb123e87f443fd2b3229cd83/lib/index.d.ts#L26)

Thank you for your time and great work.

**Comment by mwilliamson** [comment]
This is now supported in `master`.
