### ISSUE TITLE
mammoth.js with react-scripts 5 not working

### ISSUE THREAD

**Issue by GhostyJade** [mwilliamson/mammoth.js#316]
Hi, I'm trying to update my project dependency from react-scripts 4 to 5.
On project startup, react-scripts throws me errors about not finding some polyfills that were exported in webpack 4 but not anymore in v5.
In specific, lop (declared in your package.json), throws an error about util, docx-reader (in [/lib/docx/docx-reader.js](https://github.com/mwilliamson/mammoth.js/blob/master/lib/docx/docx-reader.js)) about missing path module and html-writer.js (in [/lib/writers/html-writer.js](https://github.com/mwilliamson/mammoth.js/blob/master/lib/writers/html-writer.js)) about missing util module too

There are any plans to support react-scripts 5 or should I consider to try ways to fix this issue myself?

Thanks in advance.

I'm running node 16.4.2 on Windows 11, the latest version of mammoth.js and the latest version of react packages (react, react-dom and react-scripts)

**Comment by mwilliamson** [comment]
You should be able to use the `mammoth.browser` module, which includes all of the dependencies bundled into a single file.

**Comment by GhostyJade** [comment]
Is it available on npm?

**Comment by mwilliamson** [comment]
Yes, it's in the mammoth package.

**Comment by GhostyJade** [comment]
Thanks so much, it works!

For anyone seeing this issue, I've imported mammoth as
``` javascript
import mammoth from 'mammoth/mammoth.browser';
```
and all the issues are gone.
