### ISSUE TITLE
No types for "convertToMarkdown"  method

### ISSUE THREAD

**Issue by Ranjankumar666** [mwilliamson/mammoth.js#322]
Here is a code snippet on the Vscode. I am using node 16.13.1 on Windows 10

![image](https://user-images.githubusercontent.com/54644479/166305498-c65eddf0-ee1e-49be-b31d-365c49a429dd.png)

**Comment by mwilliamson** [comment]
This is intentional: Markdown support is deprecated. I've updated the docs specifically for `convertToMarkdown` to more clearly indicate this.
