### ISSUE TITLE
在vite搭建的vue项目中使用时，会报错

### ISSUE THREAD

**Issue by weizx-coder** [mwilliamson/mammoth.js#324]
Cannot read properties of undefined (reading 'prototype') at sax.js

**Comment by mwilliamson** [comment]
Could you post minimal reproduction steps?

**Comment by weizx-coder** [comment]
a vite project does not support 'require', Sax JS uses require, which will cause an error

**Comment by mwilliamson** [comment]
You can either:
* use the `mammoth.browser` module, which is mammoth and its dependencies bundled into a single file for use in the browser, or
* configure your tooling to resolve `require` calls, such as through the use of a plugin

**Comment by weizx-coder** [comment]
please delete this issue, thinks!
