### ISSUE TITLE
Blockquote tag not supported by default

### ISSUE THREAD

**Issue by anthonyrubin** [mwilliamson/mammoth.js#335]
I am attempting to convert a docx file to HTML via `convert_to_html`. The docx file has a block quote section but upon conversion to HTML, this blockquote section is simply captured between paragraph tags `<p>` as opposed to blockquote tags `<blockquote>`. How can we get this working correctly? 

[test.docx](https://github.com/mwilliamson/mammoth.js/files/9254539/test.docx)

**Comment by mwilliamson** [comment]
You'll need to mark up the blockquote section as a blockquote by assigning it an appropriate paragraph style in Word. You can then configure Mammoth to map that paragraph style to the appropriate.

For instance, if you have a "Blockquote" paragraph style in Word, then you can use the style map:

```
p[style-name='Blockquote'] => blockquote > p:fresh
```
