### ISSUE TITLE
Can mammoth specify a block's language?

### ISSUE THREAD

**Issue by berserkwarwolf** [mwilliamson/mammoth.js#344]
Let's say I have all of my content in english, but I have a fragment in french. Is there a way to convert a word style to html that specifies the following?:

Input:
Word "Paragraph" style: I had a really bad time.
Word "French" style: C'est la vie.

Output:

```
<p>I had a really bad time.</p><br>
<p html lang="fr">C'est la vie.</p>
```

**Comment by mwilliamson** [comment]
Mammoth doesn't currently support arbitrary attributes on the generated tags. Your best bet would be to map to a class, and then use a post processing step to convert tags with that class to have the right attributes.

**Comment by mwilliamson** [comment]
Mammoth now supports attributes on HTML paths on style mappings, which I think covers this use case. For instance:

```
p[style-name='French'] => p[lang='fr']
```
