### ISSUE TITLE
ignoreEmptyParagraphs effect in order to keep line and page breaks?

### ISSUE THREAD

**Issue by alcabon** [mwilliamson/mammoth.js#345]
Hi,

Mammoth.js helps us a lot. Great tool very useful.

The html code that results is "condensed"--by which I mean there are no spaces or line breaks between tags even by using ignoreEmptyParagraphs : false ( https://github.com/mwilliamson/mammoth.js/issues/283 )

What is the real effect of ignoreEmptyParagraphs for html?

In order to keep the line breaks, a workaround is to make the blank lines visible like below with "pilcrows" or "paragraph marks" ( ¶ ) that you remove when you get the condensed html code. These pilcrows can be added with a simple Word macro but it is possible in mammoth.js directly.

It is a workaround and there are pilcrows added inside tables but it is not blocking. All the cases are not covered probably.

Thanks very much

Best regards

```
function convertParagraph(element, messages, options) { 
  return htmlPathForParagraph(element, messages).wrap(function() { 
        var content = convertElements(element.children, messages, options); 
       if (ignoreEmptyParagraphs) { 
            return content; 
       } else { 
          console.log('content:' + JSON.stringify(content)); 
//blank line: [{"type":"text","value":"\t"},{"type":"text","value":"   "},{"type":"text","value":"\t"},{"type":"text","value":"   "}] 
// page break: [{"type":"element","tag":{"tagName":"strong","tagNames":{"strong":true},"attributes":{},"fresh":false},"children":[]} 
            let blank = true;
            if (content.length > 0) {
                for (let o of content) {
                   if (o.type == 'text') { let v = o.value.trim(); if (v != '' && v != '\t') blank = false; }
                   else if (o.type == 'element') { if (o.children.length > 0) blank = false; }
                   else blank = false;
                }
            }
            if (content.length ==0  || blank) {
                 return [Html.forceWrite].concat(Html.text("¶"));
            }
            return [Html.forceWrite].concat(content);
        }
    });
}
```

**Comment by alcabon** [comment]
function convertParagraph(element, messages, options) {
    return htmlPathForParagraph(element, messages).wrap(function() {
        var content = convertElements(element.children, messages, options);
        if (ignoreEmptyParagraphs) {
            return content;
        } else {
            console.log('content:' + JSON.stringify(content));
            //blank line: [{"type":"text","value":"\t"},{"type":"text","value":"   "},{"type":"text","value":"\t"},{"type":"text","value":"   "},{"type":"text","value":"\t"}]
            // page break: [{"type":"element","tag":{"tagName":"strong","tagNames":{"strong":true},"attributes":{},"fresh":false},"children":[]}
            let blank = true;
            if (content.length > 0) {
                for (let o of content) {
                   if (o.type == 'text') { let v = o.value.trim(); if (v != '' && v != '\t') blank = false; }
                   else if (o.type == 'element') { if (o.children.length > 0) blank = false; }  
                   else blank = false;
                }
            }  
            if (content.length ==0  || blank) {
                 return [Html.forceWrite].concat(Html.text("¶"));
            }
            return [Html.forceWrite].concat(content);
        }
    });
}

**Comment by mwilliamson** [comment]
Could you post a minimal example document, the expected HTML, and the actual HTML that Mammoth currently produces?

**Comment by alcabon** [comment]
In fact, it is the empty lines that contain only banks and tabulations ( trim removes all ) that should be kept with only the new lines but not a single new line if there are multiple ones.

Could that be possible with "ignoreEmptyParagraphs : false" for html ?

(display options for Word)
![image](https://user-images.githubusercontent.com/22136342/200539212-1a5a9bf3-94ad-4bb6-bb1a-383943776ff0.png)

Thanks for your help

**Comment by alcabon** [comment]
The problem is the difference between : <br /> and <p>   </p> or <p></p> in HTML.

In docx, there are not really "empty paragraphs" and there are also "paragraphs with not visible characters" like tabulations and spaces.

Empty paragraphs in docx have always a style like headings or bold, etc so it is not the simple <br /> of html that mammoth.js produces but there are line feeds (CRLF) for the plain text.

For mammoth.js , at the end, we could get the html below and I replace <h2>¶</h2> or <p>¶</p> with <br />

<div style="color: #091C62;">
<h2>¶</h2>
<h2>¶</h2>
<h2>Title 1</h2>
<p>My first paragraph.</p>
<p>¶</p>
<p>¶</p>
<p>My second paragraph.</p>
<p>¶</p>
<p>¶</p>
<p>Next line</p>
<p>¶</p>
</div>

**Comment by mwilliamson** [comment]
I'm not sure I understand why you need the pilcrow -- why not just replace `<p></p> with `<br />`?

**Comment by mwilliamson** [comment]
Closing since I think there's already sufficient support for handling empty paragraphs.
