### ISSUE TITLE
Empty paragraphs are ignored although ignoreEmptyParagraphs=false ?

### ISSUE THREAD

**Issue by MarMun** [mwilliamson/mammoth.js#347]
If I convert a `docx` with this content:
```
P with text

P with text
```
I don't get any empty paragraphs.

Expected html output (has empty 'p' tag):
```
<p>P with text</p><p></p><p>P with text</p>
```
Actual html output (without empty 'p' tag):
```
<p>P with text</p><p>P with text</p>
```

`ignoreEmptyParagraphs` is set to `false`:
```
async function convert (file) {
  console.log(`-- ${file} --`)

  const { value, messages  } = await mammoth
    .convertToHtml({
      path: file,
      ignoreEmptyParagraphs: false
    })

  console.log(messages)
  console.log(value)
}
```
As far as I can tell,  `word/document.xml` includes the empty paragraph as expected:
![Screenshot from 2022-11-29 11-31-26](https://user-images.githubusercontent.com/5682504/204506775-72e808f1-c486-4e11-b6fb-3a59cb8f33c4.png)

[Please see reproduction repository here](https://github.com/MarMun/mammothNoEmptyPTags).
(Includes two simple DOCX files: one generated via Google Docs and the other via Libre Office Write)
 
node version: 16.18.1

**Comment by mwilliamson** [comment]
Options are passed as the second argument to `convertToHtml`. For instance:

```
mammoth.convertToHtml({path: file},  {ignoreEmptyParagraphs: false})
```
