### ISSUE TITLE
Image position inside a Textbox

### ISSUE THREAD

**Issue by Seybi-ea** [mwilliamson/mammoth.js#349]
In my document I have an image inside a text box, how can I get the exact position of text and image? now it is treated text and image separately. also did I get any grouping information of text and image?

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML you'd expect to get, and the HTML you're actually getting?

**Comment by Seybi-ea** [comment]
Hi my sample document is here,
[sample.docx](https://github.com/mwilliamson/mammoth.js/files/10312817/sample.docx)
sorry there is a mistake in my  previous question actually image is not inside the textbox  its outside. in my document image, textbox and shape are grouped, is there any way to identify the position of image and text box inside the group? ie. left, center or right

**Comment by mwilliamson** [comment]
I'm still not sure what HTML you're expecting to get?

Having said that, it's quite likely that Mammoth won't do what you want -- it's not designed to exactly replicate the layout and format of the source document, and instead tries to map semantically meaningful elements.

**Comment by mwilliamson** [comment]
Closing since I suspect this is asking for the sort of precise positioning that Mammoth doesn't support.
