### ISSUE TITLE
hyperlinks to "places in this document"/in-text anchors are ignored

### ISSUE THREAD

**Issue by alubbe** [mwilliamson/mammoth.js#35]
Mammoth reads out normal links just fine:
```xml
<w:hyperlink r:id="rId8" w:history="1">
  <w:r w:rsidRPr="00F36DC1">
    <w:rPr>
      <w:rStyle w:val="Hyperlink"/>
    </w:rPr>
    <w:t>www.someurl.com</w:t>
  </w:r>
</w:hyperlink>
```
becomes
```html
<a href="www.someurl.com">www.someurl.com</a>
```

But if the document links to an anchor ("places in this in document" from the link tab) instead, it gets ignored entirely:
```xml
<w:hyperlink w:anchor="_Main_Heading" w:history="1">
  <w:r w:rsidRPr="00C57019">
    <w:rPr>
      <w:rStyle w:val="Hyperlink"/>
    </w:rPr>
    <w:t>Click Me</w:t>
  </w:r>
</w:hyperlink>
...
<w:bookmarkStart w:id="1" w:name="_Main_Heading"/>
<w:bookmarkEnd w:id="1"/>
```
becomes
```html
<p>Click me</p>
```

Instead, you would probably want
```html
<p><a href="#_Main_Heading">Click Me</a></p>
...
<span id="_Main_Heading"></span>
```

Is this something you have on your roadmap/how can I help to get this feature in? :)

**Comment by mwilliamson** [comment]
Hello! I only work on Mammoth as a side-project, so there's nothing quite as elaborate as a roadmap. I generally add features on-request provided that they're reasonably straightforward (and it looks like this should be -- no promises though!), but I might not have a chance to take a look for a week or two. I'm also happy to accept pull requests so long as they match the coding style and come with tests. Happy to answer questions and to help if you want to take a crack, but certainly no obligation on your part.

**Comment by alubbe** [comment]
well if you point me in the right direction as to which file to look at, I'll give it a try :)

**Comment by mwilliamson** [comment]
Hmm, you'd probably need to change the way that the files are read in `lib/docx/document-xml-reader.js`, and adjust `lib/documents.js` so that it can store internal hyperlinks and bookmarks. Once that's done, `lib/document-to-html.js` can be updated to generate the right HTML.

Tests can be found in correspondingly named test files under `tests`.

Hope that helps!

**Comment by mwilliamson** [comment]
Hyperlinks to bookmarks in the same document are now support.
