### ISSUE TITLE
why .doc file is not supported

### ISSUE THREAD

**Issue by Donhv** [mwilliamson/mammoth.js#350]
I have question, why we dont support .doc file?

**Comment by berserkwarwolf** [comment]
Because it's not xml, only docx files have xml that Mammoth can work with. Use Open Office instead.

**Comment by Donhv** [comment]
> Open Office

what open office you mean? I only have base64 string of doc file.

**Comment by mwilliamson** [comment]
It's a different format to docx, and out of the scope of this library I'm afraid.
