### ISSUE TITLE
Error when trying to open docx made in non-english version of word

### ISSUE THREAD

**Issue by skfrost19** [mwilliamson/mammoth.js#354]
I tried opening a file with Norwegian names for paragraph styles and got this error.…
![221653871-26dc3301-6472-48cc-8aea-d328ce2bc888](https://user-images.githubusercontent.com/62276725/222919730-4fa80992-bd04-4a17-b9ab-fed15168804e.png)

**Comment by mwilliamson** [comment]
I don't think this is anything to do with the language of the document -- there just isn't a mapping for "Title", and it's not entirely obvious what the default should be seeing as "Heading 1" is mapped to `h1`. In any case, I'd suggest adding a style mapping to get rid of the warning.

**Comment by skfrost19** [comment]
Thanks will do.
