### ISSUE TITLE
[Question] Is there a way to convert HTML to DOCX?

### ISSUE THREAD

**Issue by shreyventure** [mwilliamson/mammoth.js#356]
I know how docx files are, and we need to unzip it in order to hunt for it's contents. But now that we have the content converted to html, can we have a function in mammoth.js that converts it back to docx? (If the question is silly, I apologize in advance)

**Comment by mwilliamson** [comment]
I'm afraid that Mammoth only supports going from docx to HTML, not the opposite direction.

**Comment by shreyventure** [comment]
> I'm afraid that Mammoth only supports going from docx to HTML, not the opposite direction.

That's sad to know. 😢
