### ISSUE TITLE
Dev and test files included in published package

### ISSUE THREAD

**Issue by Fdawgs** [mwilliamson/mammoth.js#358]
Unpacked, the mammoth package weighs in at 2.18MB.

This could be reduced by 417.3kB (~19%) by adding the following folders and files to `.npmignore`:
- `.github/`
- `tests/`
- `.eslintrc.json`

The contents of these folders and files are only used for CI/CD and tests, so nothing used by the published package itself.

**Comment by mwilliamson** [comment]
Interestingly, I've had the opposite request on other packages, that is, to include tests, on other packages, especially from downstream maintainers.

Presumably for node.js use cases, including the browser distribution is the biggest source of inefficiency?

Is there a general convention for whether to include tests and similar in npm packages?

**Comment by Fdawgs** [comment]
Thanks for the response @mwilliamson, it's all down to personal preference it seems!

I was primarily looking at reducing dependency sizes as part of the [Greener NHS programme](https://www.england.nhs.uk/greenernhs/).

Ignoring unused files could speed up installations, lower bandwidth usage, improve reliability on spotty connections, and leave more room on the hard drive. Registries and mirrors would also benefit; reduced resources likely means lower energy consumption and lower costs.

Users could use [yarn's autoclean CLI](https://classic.yarnpkg.com/lang/en/docs/cli/autoclean/) to remove the unused files, but the files have already been downloaded and bandwidth wasted at this point.
