### ISSUE TITLE
 在vue3+vite+ts项目中引入mammoth会报这样的错误 Introducing mammoth in the Vue3+vite+ts project will result in an error like this

### ISSUE THREAD

**Issue by jiaqihu-supreme** [mwilliamson/mammoth.js#359]
![mammoth](https://user-images.githubusercontent.com/54058083/236389092-47939772-07d9-4169-afdc-30e287382f36.jpg)

**Comment by mwilliamson** [comment]
Are you importing `mammoth` or `mammoth/mammoth.browser`? If the former, you'll need to ensure your bundler has appropriate polyfills set up.

**Comment by jiaqihu-supreme** [comment]
Thank you for your reply

I installed stream using NPM in the project and configured util in vite.config.ts

resolve: {

     alias: {

        "@": path.resolve(__dirname, "./src"),

         util: 'rollup-plugin-node-polyfills/polyfills/util',

      }
 }

Solved this problem

**Comment by mwilliamson** [comment]
I'm glad you solved it.
