### ISSUE TITLE
有几率解析错误，

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [mwilliamson/mammoth.js#361]
function collapseAlternateContent(node) {
    if (node.type === "element") {
        if (node.name === "mc:AlternateContent") {
            if (node.first("mc:Fallback")) {
                return node.first("mc:Fallback").children
            }
        }
        if (node.children) {
            node.children = _.flatten(node.children.map(collapseAlternateContent, true));
            return [node];
        }
    } else {
        return [node];
    }
}

如果没有找到mc:Fallback，则源代码会报错

**Comment by liuhuapiaoyuan** [comment]
this is a bug fixed code

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML you're expecting to see, and the HTML you're actually seeing?

**Comment by liuhuapiaoyuan** [comment]
My point is that there might be such a bug, so I made a simple adjustment to the code to prevent errors.
if the element doesn't have mc:Fallback , your code will throw exception . so I suggest that you modify the parsing code.

**Comment by mwilliamson** [comment]
If you haven't encountered this issue in the wild, I'm going to close this. Mammoth could be more tolerant of weird documents, but it's not a particularly high priority unless there are specific examples that are failing.
