### ISSUE TITLE
Can convert with password file？

### ISSUE THREAD

**Issue by ltinerary** [mwilliamson/mammoth.js#363]
[hh.docx](https://github.com/mwilliamson/mammoth.js/files/11542655/hh.docx)

Here is the file I used.

This file requires a password to access

However, there is no prompt for a password and I get a error:

 **Uncaught Error: Can't find end of central directory : is this a zip file ?** 

![image](https://github.com/mwilliamson/mammoth.js/assets/79144923/e9f2473c-59dc-4110-8056-1f001fb506b4)

Microsoft Edge:113.0.1774.50

**Comment by mwilliamson** [comment]
I'm afraid Mammoth doesn't support password-protected documents.
