### ISSUE TITLE
[Bug] There is no css style!

### ISSUE THREAD

**Issue by trcat** [mwilliamson/mammoth.js#366]
when i use it, it can works, but without css style!

My docx file looks like this:

![image](https://github.com/mwilliamson/mammoth.js/assets/23648263/9518fb61-6b35-4ef5-8030-79a34e0ef6d1)

But the result looks like this:

![image](https://github.com/mwilliamson/mammoth.js/assets/23648263/f81225e9-566a-476d-9d8f-4fe078581104)

color is not red.

I used it with vue, code split look like this:

```vue
/**
 * josnFile,resoonse is the file 
 * /
 mammoth
            .convertToHtml({ arrayBuffer: jsonFile.response }, { includeDefaultStyleMap: true })
            .then((result) => {
              const docEl = document.createElement('div')
              docEl.className = 'document-container'
              docEl.innerHTML = result.value
              this.$refs.docx.innerHTML = docEl.outerHTML
            })
            .catch((a) => {
              console.log('alexei: something went wrong', a)
            })
            .done()

```

**Comment by trcat** [comment]
Okay, I understand. Thank you very much

**Comment by Roxi-3906** [comment]
Is there could be a manually control function to take over the generate process🤔, so there's a possibility to handle the generated HTML element's inline style.

**Comment by kbqdev** [comment]
> Okay, I understand. Thank you very much

Do you find solution for this case ?
