### ISSUE TITLE
Border missing

### ISSUE THREAD

**Issue by 18207278668** [mwilliamson/mammoth.js#368]
The table in Word converted HTML is missing borders. How can we solve this problem

**Comment by mwilliamson** [comment]
You'll need to apply a style to the table in the source document, and then use a style mapping to map that document table style to the appropriate HTML element and CSS class.

**Comment by ardy20** [comment]
Hi How can I widen/adjust the area of grey box (borders) that appears in html output
Also, Is there any way to run the tool in Windows 10?
