### ISSUE TITLE
Interface changes since upgrading to 1.6.0

### ISSUE THREAD

**Issue by robin-garnham** [mwilliamson/mammoth.js#370]
Since upgrading from 1.5.1 to 1.6.0 I had to change the interactions with the library from Buffer to ArrayBuffer.
It's working fine with the below code, but Typescript flags an issue because it's expecting buffer to be type Buffer

Passing in arrayBuffer as the parameter name doesn't work as it throws an error about being unable to find a file in the unzip step.

`export async function generateHtmlFromDocx(arrayBuffer: ArrayBuffer) {
    const { value: html } = await mammoth.convertToHtml({
        buffer: arrayBuffer,
    });
    return html;
}`

**Comment by mwilliamson** [comment]
Are you on node.js or in the browser? Assuming you're on node.js, since you mention using `Buffer`, why did you have to change from using `Buffer` to `ArrayBuffer`?

**Comment by robin-garnham** [comment]
Yes, using NodeJS.

When I upgraded versions, I had to start using `ArrayBuffer` for it work again

My use of the library helps me to implement the feature I requested here: https://github.com/mwilliamson/mammoth.js/issues/355

**Comment by mwilliamson** [comment]
What happens when you use a `Buffer`?

**Comment by mwilliamson** [comment]
Closing due to insufficient information.
