### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by tianliuj** [mwilliamson/mammoth.js#374]
If you're reporting a bug or requesting a feature, please include:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using

react项目中使用mammoth报错：Unhandled rejection TypeError: Cannot read properties of undefined (reading 'children')
版本：
"react": "^16.13.1"
"typescript": "^3.8.3",
"mammoth": "^1.6.0",

只有部分word会报这个错，大部分是正常的，请问大家有遇到这个问题吗？

**Comment by mwilliamson** [comment]
Could you provide an example document? Without one, this is tricky to debug.

**Comment by mwilliamson** [comment]
Closing due to lack of information.
