### ISSUE TITLE
Uncaught SyntaxError: redeclaration of var getTextContent

### ISSUE THREAD

**Issue by AngusParsonson** [mwilliamson/mammoth.js#375]
- Running on macos, react project using vite
- `npm run dev` works, but doing `npm run build` causes the following error when I try to `import { convertToHtml } from "mammoth";`

`Uncaught SyntaxError: redeclaration of var getTextContent`

- node v20.5.0

**Comment by mwilliamson** [comment]
Could you post the full stack trace?

**Comment by AngusParsonson** [comment]
Hey @mwilliamson, thanks for getting back to me. 

I got around this by using `mammoth/mammoth.browser` instead, I then created a typings.d.ts file with `declare module "mammoth/mammoth.browser";` (I'm using TypeScript).

**Comment by mwilliamson** [comment]
I'm glad you got it sorted.
