### ISSUE TITLE
Use Style Map with Style IDs instead of Style Names ?

### ISSUE THREAD

**Issue by berserkwarwolf** [mwilliamson/mammoth.js#376]
Feature request:
Add an option for the style map to use style IDs instead of style names.

Context:
Right now, the style map syntax requires a style name.
The problem is, that a style name in a word document can change, while it's style ID will persist within the docx xml code.

My use case:
Being able to use style maps with style IDs would enable me to use DOCX templates with style names in several languages, but style IDs will be identical between languages. This would allow me to use one CSS to style all languages.

Also, if I ever want to convert HTML+CSS to DOCX with another tool, being able to retain style IDs would enable me to round trip (edit the word document in ms word, then back to mammoth, repeat loop.)

**Comment by mwilliamson** [comment]
This is already supported, for instance:

```
p.Heading1 => h1
```
