### ISSUE TITLE
Cannot install 0.3.14

### ISSUE THREAD

**Issue by Pinny3** [mwilliamson/mammoth.js#38]
Dear,

I always get an error message like this

npm ERR! fetch failed http://registry.npmjs.org/jszip/-/jszip-2.2.2.tgz

if I try to do an npm install with

[...]
"mammoth": "^0.3.14",
[...]

Can you please investigate and fix?

Regards,

Christian

**Comment by mwilliamson** [comment]
Can you successfully install jszip 2.2.2 using npm directly? If not, what happens if you try to grab that URL using CURL or a browser?

What versions of node and npm are you using?

**Comment by Pinny3** [comment]
I can't install jazip-2.2.2 directly. The file seems to be corrupt.

╰─$ npm install jszip@2.2.2
npm ERR! fetch failed http://registry.npmjs.org/jszip/-/jszip-2.2.2.tgz

I've just downloaded it via Chrome and get a corrupted file.

When I try to get it with wget I got the following error:

╰─$ wget http://registry.npmjs.org/jszip/-/jszip-2.2.2.tgz
--2015-01-27 10:45:05--  http://registry.npmjs.org/jszip/-/jszip-2.2.2.tgz
Resolving httpproxy.tchibo-intranet.de (httpproxy.tchibo-intranet.de)... 10.124.129.66
Connecting to httpproxy.tchibo-intranet.de (httpproxy.tchibo-intranet.de)|10.124.129.66|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 750835 (733K) [application/octet-stream]
Saving to: ‘jszip-2.2.2.tgz.4’

82% [=====================================================================>                ] 619,763     --.-K/s   in 0.06s   

2015-01-27 10:45:05 (9.26 MB/s) - Read error at byte 619763/750835 (Connection reset by peer). Retrying.

So the question is if you can change the dependency for jszip to another version, since I can download other versions without any problems. For example, the current version 2.4.0 can be downloaded without any problems:

╰─$ npm install jszip                                                                                                      8 ↵
jszip@2.4.0 node_modules/jszip
└── pako@0.2.5

**Comment by mwilliamson** [comment]
I'll try updating jszip when I get a chance. Having said that, it looks like you're using a proxy -- is it possible that's causing the issue?

**Comment by Pinny3** [comment]
The proxy is not the problem, since other versions of jszip can be installed without any problems. Also, on a MacBook without any proxies, jszip 2.2.2 is not downloadable.

**Comment by mwilliamson** [comment]
I've updated jzip to 2.4.0, but I'd suggest you also file a bug with jszip or npm, since you should be able to grab 2.2.2 (and indeed, I can without an issue).
