### ISSUE TITLE
i have this error

### ISSUE THREAD

**Issue by shubhamtanthetaa** [mwilliamson/mammoth.js#380]
Compiled with problems:
×
ERROR in ./node_modules/mammoth/lib/docx/docx-reader.js 3:11-26
Module not found: Error: Can't resolve 'path' in 'D:\docx\node_modules\mammoth\lib\docx'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

**Comment by mwilliamson** [comment]
The node.js `path` module is used internally. If you want to use Mammoth in the browser, you'll either need to include a polyfill (as the above describes), or to use `mammoth/mammoth.browser` instead.

**Comment by shubhamtanthetaa** [comment]
yes it works thank @mwilliamson
