### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by galaczi** [mwilliamson/mammoth.js#382]
I am getting TypeError: Cannot read properties of undefined (reading 'children'). There is already a closed, unresolved issue with the same title.

Example document: https://bit.ly/3r9IxM7

I am running on Ubuntu, Nodejs v19.0.0

**Comment by mwilliamson** [comment]
Based on the extension, that looks like a `.doc` file, which isn't supported.

**Comment by galaczi** [comment]
My mistake.
