### ISSUE TITLE
Text alignment not transferred

### ISSUE THREAD

**Issue by canis-lupus03** [mwilliamson/mammoth.js#384]
Hello, 

I don't know whether this is possible, but I am searching for a way to retain text alignment when moving my text from google docs to the wordpress editor. I was hoping this plugin would do so, but it doesn't. All text is left-aligned, even if the source, in both gdocs and docx is centre or right aligned. 

Screenshots of results attached. I'm using Firefox on Win 10, I haven't tried in another browser. 

Thank you, 

Lily
![Screenshot 2023-11-19 at 13-39-33 Add a New Post ‹ House Draculesti — WordPress](https://github.com/mwilliamson/mammoth.js/assets/145503503/21419b89-35aa-496a-8915-21fe1cbdb186)
![Screenshot Test docx in libreoffice writer](https://github.com/mwilliamson/mammoth.js/assets/145503503/e4b148c3-07ba-417a-8a65-fe7c6d022e65)
![Screenshot 2023-11-19 at 13-37-13 Test - Google Docs](https://github.com/mwilliamson/mammoth.js/assets/145503503/7184b4dd-a468-4b6b-980b-037c3f4c77b3)

**Comment by mwilliamson** [comment]
Mammoth is designed to work on the styles in the document rather than the exact formatting. In this case, the approach would be to use a paragraph style that applies the desired alignment, and use a style map to map the paragraph style in the source document to a CSS class that applies the appropriate alignment.

**Comment by canis-lupus03** [comment]
Thank you for your reply and explaining why it's not transferring! If I ever feel inclined to expand my technical horizons, I'll give your solution a try.
