### ISSUE TITLE
no css style

### ISSUE THREAD

**Issue by qqlcx5** [mwilliamson/mammoth.js#385]
"I want to implement a feature to help many teachers save work time. I am a front-end developer and I'm not very familiar with this field. I would greatly appreciate it if any experts could guide me when they have time.

I have a complete meeting minutes document in .docx format, which has specific styles at the beginning and end. I want to split it into individual .docx files for each topic, with the styles at the beginning and end of each topic remaining unchanged."

How should I implement this feature? Can you recommend any plugins, libraries, or implementation steps and ideas? Thank you very much.

![image](https://github.com/mwilliamson/mammoth.js/assets/31888710/b5938ef2-35f3-4d77-a19a-3819201a99d9)

**Comment by mwilliamson** [comment]
Mammoth is for converting docx files to HTML, so I think this is out of scope. Good luck with your feature!
