### ISSUE TITLE
Remove Images & Hyperlinks

### ISSUE THREAD

**Issue by PatrickZimmerer** [mwilliamson/mammoth.js#387]
Is there currently a way to convert from docx => markdown and filter out all Images & Hyperlinks, I tried so many things and got back to converting docx => text => markdown which is not really effective and loses all formatting

**Comment by mwilliamson** [comment]
Your best bet is probably to convert to HTML, remove the images and hyperlinks, and then convert to Markdown.

**Comment by PatrickZimmerer** [comment]
I ended up converting it to markdown and filtered out the elements with a regex but thanks for your response :)
