### ISSUE TITLE
How can I use string as an input?

### ISSUE THREAD

**Issue by Bajena** [mwilliamson/mammoth.js#388]
Hi!

I'd like to use mammoth for converting pasted MS word document's text to HTML in realtime. Is there a way to:
- Use `convertToHtml` synchronously (not using the promise)
- Pass document's body as an input instead of a file name

Thanks for help :)

**Comment by mwilliamson** [comment]
>     * Use `convertToHtml` synchronously (not using the promise)

`convertToHtml` is asynchronous: there is no synchronous version.

>     * Pass document's body as an input instead of a file name

[The different ways of passing data in are described in the docs](https://github.com/mwilliamson/mammoth.js#mammothconverttohtmlinput-options): you can pass in an array buffer or node buffer, depending on whether you're in the browser or on node.

**Comment by Bajena** [comment]
Alrighty, thanks for answers 👍
