### ISSUE TITLE
miss character while convert docx file

### ISSUE THREAD

**Issue by huongtran84** [mwilliamson/mammoth.js#391]
word file:
 
<img width="509" alt="Screenshot 2024-03-05 at 20 53 17" src="https://github.com/mwilliamson/mammoth.js/assets/4927097/53b37c51-10de-4a61-9465-a7ab507598cb">
after convert:
    <p>3. Các kiến nghị <em>(nếu có)</em>: </p>
    <ul>
        <li>
            <ul>
                <li>
                    <ul>
                        <li> Đơn vị sử dụng phải tuận thủ nghiêm túc các tiêu chuẩn, quy định an toàn sử dụng thiết bị
                            và thực hiện đầy đủ các chế độ bảo dưỡng, sửa chữa định kỳ thiết bị.</li>
                        <li> Định kỳ sát hạch, kiểm tra kiến thức an toàn đối với người vận hành thiết bị.</li>
                        <li> Tuyệt đối không để thiết bị hoạt động quá tải trọng cho phép được ghi trên giấy chứng nhận
                            kiểm định. </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>

it is missing "+" character on each line.
how to fix this?

**Comment by mwilliamson** [comment]
Based on the image provided, it seems like the "+" is the bullet for each nested list item. In that case, you should be able to apply an appropriate CSS style to those nested list items to change the bullet in the HTML.
