### ISSUE TITLE
Formatting issue while converting from docx to HTML

### ISSUE THREAD

**Issue by sahilgupta098** [mwilliamson/mammoth.js#392]
I am trying to convert docx file into HTML and use that html to display on web in edit mode in which i was successful but there were some formatting issues and some images were not being displayed.
I am using this on LWC(lightning web components) which is a web based framework introduced by Salesforce .
The doc file I have attached .
[New Executive Resume Template (2) (1).docx](https://github.com/mwilliamson/mammoth.js/files/14664739/New.Executive.Resume.Template.2.1.docx)

The output I want :
![Screenshot (21)](https://github.com/mwilliamson/mammoth.js/assets/42268072/92c91654-a097-4ee0-9e45-cd4f8362e6aa)
The output I am getting : 
![Screenshot Capture - 2024-03-20 - 15-54-13](https://github.com/mwilliamson/mammoth.js/assets/42268072/73f2f6fb-b494-4dbb-84ca-fd520d419a21)

**Comment by rajendraprasadyk** [comment]
let options = {
         styleMap: [
             "p[style-name='center'] => center",
             "p[style-name='Heading 1'] => p:fresh > h1:fresh",
             "p[style-name='Heading 2'] => p:fresh > h2:fresh",
             "p[style-name='Heading 3'] => p:fresh > h3:fresh",
             "p[style-name='Heading 4'] => p:fresh > h4:fresh",
             "p[style-name='Heading 5'] => p:fresh > h5:fresh",
             "p[style-name='Heading 6'] => p:fresh > h6:fresh",
             "p[style-name='Code Block'] => pre:separator('\n')",
             "p[style-name='Aside Heading'] => div.aside > h2:fresh",
             "p[style-name='Aside Text'] => div.aside > p:fresh",
            
             "u => u",
             "p[style-name='Numbering'] => div.aside > h2:fresh",
         ],
         convertImage: mammoth.images.imgElement(function (image) {
             return image.read("base64").then(function (imageBuffer) {
                 return { src: "data:" + image.contentType + ";base64," + imageBuffer };
             });
         }),
         ignoreEmptyParagraphs: false
     };

     
     const result = await mammoth.convertToHtml({ buffer: file.data }, options);
     let html = result.value;

**Comment by mwilliamson** [comment]
Based on your screenshots, I'd say this is broadly working as intended. Mammoth isn't intended to copy the exact formatting of the source document, and instead maps styles onto the appropriate HTML elements and CSS classes. If you're looking for a high-fidelity translation, I'm afraid Mammoth isn't the right tool.
