### ISSUE TITLE
The image is not displayed according to the size and position of Word

### ISSUE THREAD

**Issue by web-whj** [mwilliamson/mammoth.js#396]
Hello, I have encountered an issue where the size and position of the parsed HTML image do not match Word. Word has two images on a single line, and the parsed HTML has one image per line. The image size is the size of the original image. Can I know which parameters need to be configured to make the image size and position consistent with Word? Looking forward to your reply! Thank you very much!

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML you'd expect to get, the HTML you're actually getting?
