### ISSUE TITLE
Module not found: Error: Can't resolve 'path' in 'my-react-app\node_modules\mammoth\lib\docx'

### ISSUE THREAD

**Issue by dineshpithiya-virtusa** [mwilliamson/mammoth.js#398]
I am using react js latest version 18.2.0. I installed "mammoth": "^1.7.1" version.
Then after I tried to import and run code but it's return error like shared.
`import * as mammoth from 'mammoth';
const result = await mammoth.convertToHtml({ arrayBuffer: e.target.result });
`

Is there any compatibility issue? or it's not design to work with react js or something else I don't understand .

please help me to know what exactly issue here?

**Comment by mwilliamson** [comment]
You'll either need to use a polyfill for the `path` module in whatever bundler you're using, or use the `mammoth.browser` module that includes all of the dependencies, including an appropriate polyfill.

**Comment by mwilliamson** [comment]
Closing since the above should resolve the issue, but feel free to shout if you're still having issues.
