### ISSUE TITLE
error in custom style map adding attribute to an element in html path

### ISSUE THREAD

**Issue by bonn-jaredbuttars** [mwilliamson/mammoth.js#399]
The following map works, properly adding the class to the output HTML element:
`p:ordered-roman-list(1) => ol.roman > li:fresh`

If I change the css map to an attribute:
`p:ordered-roman-list(1) => ol[type='i'] > li:fresh`

I get the following two messages:

* Did not understand this style mapping, so ignored it: p:ordered-roman-list(1) => ol[type='i'] > li:fresh Error was at character number 30: Expected end but got open-square-bracket
* Unrecognised paragraph style: 'List Paragraph' (Style ID: ListParagraph)

I'm not sure if I wrote the map incorrectly or if there is a bug. Attached is the docx I'm trying to convert.
[Simple.docx](https://github.com/mwilliamson/mammoth.js/files/15210273/Simple.docx)

* Using mammoth browser
* Edge 124.0.2478.67
* Same issue occurs in Chrome and Firefox

**Comment by mwilliamson** [comment]
That's odd: neither of those should work since `:ordered-roman-list` isn't supported syntax so far as I remember. Could you double check you don't get any error messages from the first style map? What version of mammoth are you using, and how did you install it?

**Comment by bonn-jaredbuttars** [comment]
I was able to successfully add  isLetter, isRoman, isDecimal and isBullet to the list properties in style-reader.js and titled their types as ordered-letter-list, ordered-roman-list, ordered-decimal-list and unordered-list.

It works really well other than adding the attributes. a decimal list is determined by css so adding the class to that one works perfectly. Just need to be able to add the type attribute to the others - the docs suggest that it's possible:

```
To add an attribute, use square brackets similarly to a CSS attribute selector:
p[lang='fr']
```

The docs also show how to add a css class which works:

```
To give an element a CSS class, append a dot followed by the name of the class:
h1.section-title
```

version is 1.7.1

**Comment by mwilliamson** [comment]
If you've modified Mammoth, I'm afraid I can't say what's wrong without seeing the modifications you've made.

**Comment by bonn-jaredbuttars** [comment]
I understand. In this case, are the docs wrong and it doesn't support including attributes in an element path?

**Comment by mwilliamson** [comment]
Unless there's a bug I'm unaware of, attributes should be supported in HTML paths.

**Comment by bonn-jaredbuttars** [comment]
Okay. It would be awesome to have support for the following docx ordered list numFmt values:

lowerLetter
upperLetter
lowerRoman
upperRoman
decimal

Thank you for this project.

**Comment by mwilliamson** [comment]
I think that's covered by #167, so I'll close this issue as a duplicate.
