### ISSUE TITLE
using filepicker.io as a frontend to mammoth?

### ISSUE THREAD

**Issue by BobWalsh** [mwilliamson/mammoth.js#40]
If I wanted to pass mammoth.js a URL like "https://www.filepicker.io/api/file/ZE0lWtiRRmOHiiFs3EKd", can I do that directly? Or do I have to open the file then stream it to mammoth via:

```
function handleFileSelect(event) {
        readFileInputEventAsArrayBuffer(event, function(arrayBuffer) {
            mammoth.convertToHtml({arrayBuffer: arrayBuffer})
                .then(displayResult)
                .done();
        });
    }

```

**Comment by mwilliamson** [comment]
Hello! Mammoth doesn't support HTTP(S), so you'll have to download the
file before passing it to Mammoth.


On Fri, Feb 20, 2015, at 01:45 AM, Bob Walsh wrote:
> If I wanted to pass mammoth.js a URL like
> "https://www.filepicker.io/api/file/ZE0lWtiRRmOHiiFs3EKd", can I do
> that directly? Or do I have to open the file then stream it to
> mammoth via:


> function handleFileSelect(event) {
        readFileInputEventAsArrayBuffer(event, function(arrayBuffer) {
        mammoth.convertToHtml({arrayBuffer: arrayBuffer})
        .then(displayResult) .done(); }); }

>
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/mwilliamson/mammoth.js/issues/40

**Comment by mwilliamson** [comment]
Closing since I don't there's anything else to add, but feel free to reopen if I'm mistaken!
