### ISSUE TITLE
Release notes / changelog

### ISSUE THREAD

**Issue by tommoor** [mwilliamson/mammoth.js#403]
Hi, it seems that no releases have been published on GitHub since 2016 – there's also no `CHANGELOG.md`, so I'm wondering what is the best way to find out what is changing between releases?

**Comment by mwilliamson** [comment]
[`NEWS`](https://github.com/mwilliamson/mammoth.js/blob/master/NEWS) contains details on each release, if that helps?

**Comment by tommoor** [comment]
That seems helpful! Thoughts on changing this to CHANGELOG like most OSS projects?

**Comment by mwilliamson** [comment]
If I was starting the project today I would, but at this point I'll probably just keep it as it is.

**Comment by tommoor** [comment]
I mean, it's literally just renaming a file? But your project – thanks for the response.
