### ISSUE TITLE
Any way to programmatically identify blocks of text with missing formatting?

### ISSUE THREAD

**Issue by pcraig3** [mwilliamson/mammoth.js#404]
Hi there,

First of all, excellent library. I am very pleased with it and would like to recognize all the hard work you've put in.

I have a question around missing style maps.

Basically, I am creating an application that allows people to upload Word documents and convert them to HTML (go figure). I can't anticipate all the Word files that are coming in, so we will see files uploaded with formatting that we aren't familiar with yet. Some of the documents that come in are 50-80 pages long and if there are styles that aren't known in my style map, so I throw a warning message up when unrecognized formatting shows up. Here's an example of a warning message for a uploaded document that has formatting that isn't known to my style map.

<img width="546" alt="Screenshot 2024-05-17 at 7 35 05 PM" src="https://github.com/mwilliamson/mammoth.js/assets/2454380/50396646-5691-4c45-81a9-76cb032841cf">

When I get a warning message like this, I see the types of formatting that are missing but I don't know _where_ they reside in the doc. I would like to be able to print the content that has this formatting so that I can quickly find it in the document. Is this possible?

**Comment by mwilliamson** [comment]
This isn't currently supported, no. You might be able to do something with document transforms to change the output in a way that a post-processing step could use to find paragraphs and runs with particular styles, but that would likely be a bit of a hack.

**Comment by pcraig3** [comment]
All good! I will do my best to look for a workaround.
