### ISSUE TITLE
Cannot get imageConvert to work

### ISSUE THREAD

**Issue by garyns** [mwilliamson/mammoth.js#41]
Hi,

I'm trying to get a custom image converter working, but it does not seem to get called. I'm trying to write the image out to a file. If I also change the return src to be "dataxxxxxxxx", the resulting output still just shows "data:"

Here is my code. Any thoughts would be appreciated.

        var options = {
            path: dir + "/sig.docx",
            
            convertImage: mammoth.images.inline(function(element) {
              return element.read("base64").then(function(imageBuffer) {
                
                fs.writeFile(dir + "/image.jpg", imageBuffer, function(err) {
                    if(err) {
                        console.log(err);
                    } else {
                        console.log("The file was saved!");
                    }
                }); 
                
                return {
                    src: "dataxxxxxxx:" + element.contentType + ";base64," + imageBuffer
                };
              });
            })
        };        
        
        mammoth.convertToHtml(options).....

Thanks
Gary.

**Comment by mwilliamson** [comment]
Hmm. from a quick read it seem as though that code should work. What happens if you try using the CLI to output to a directory? (The CLI uses the same API to put images into a directory, so should help down narrow down where the problem is.)

What version of node and mammoth.js are you using, and on what platform? If you run the tests (`npm install && npm test` on a clone of the repository), do they pass?

**Comment by garyns** [comment]
Thank you for the fast response!

I've done a bit more experimenting and reading the API, and found that the following works (ie when I separate out the input and options.)

mammoth.convertToHtml({path: dir + "/sig.docx"}, options)

So, all is good now thanks.

Regards,
Gary.

**Comment by oninross** [comment]
Hi, I want to reopen this issue.  Its doing the task of converting the docs to html and the images as well.  However, the image is broken(?).  I have uploaded the image below.  As you can see, its not loading properly

![image](https://user-images.githubusercontent.com/2233813/30531245-50018400-9c90-11e7-9459-05f3c58dd1d0.jpg)

**Comment by mwilliamson** [comment]
Mammoth should just be writing the image out unchanged from the
original file. If you unzip the document, does the image that gets
extracted have the same problem?

**Comment by oninross** [comment]
What was happening was that it was converting the images to base64 and doing it inline, which is great!  But I believe we would like to have an option as well to save the images as a file and put it in the directory.  I dont think its advisable to base64 all images of a word doc

**Comment by mwilliamson** [comment]
You can do this using your own image converter. Take a look at the one
the CLI uses for an example.

https://github.com/mwilliamson/mammoth.js/blob/eaefb859906c56e44c6a0ae4efeb407cf92a8e7d/lib/main.js#L27
