### ISSUE TITLE
 convertToHtml no response in project using qiankun

### ISSUE THREAD

**Issue by shyYang** [mwilliamson/mammoth.js#411]
```const arrayBuffer = await file.arrayBuffer();

const result = await mammoth.convertToHtml({ arrayBuffer }) // blocking

const html = result.value

node 16.14.0

**Comment by mwilliamson** [comment]
I'm afraid there isn't enough information here for me to be able to provide any help. If you could provide more details on what you're doing and what problems you're seeing, I might be able to help.

**Comment by shyYang** [comment]
I found that it was caused by  [`async()` of `jszip`](https://github.com/mwilliamson/mammoth.js/blob/9176454470138777bd16769c2e8a97128af7761c/lib/zipfile.js#L15)，I downgraded the version to 1.4.16 that not used `async(`) and my code can run normally
