### ISSUE TITLE
Adjustment of the area of grey box

### ISSUE THREAD

**Issue by ardy20** [mwilliamson/mammoth.js#412]
Hi How can I widen/adjust the area of grey box (borders) that appears in output html file. It is too narrow and can be widen.
Also, Is there any way to run the tool in Windows 10?

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, the HTML you're currently getting, and the HTML you'd expect?

So far as I know, the tool should work using node.js on Windows 10.

**Comment by mwilliamson** [comment]
I'm afraid I've never heard of mammoth.plus, so I can't help you there.

If you install node.js and then install mammoth.js as a node module using npm, you should be able to use mammoth.js on the command line. If you search around for instructions on how to install node.js and use npm on Windows, then those instructions should be applicable to mammoth.js.

**Comment by mwilliamson** [comment]
I'm afraid I can't do much without an example document, so I'm closing due to lack of information.
