### ISSUE TITLE
BUG: Formatted List Imported as Paragraph

### ISSUE THREAD

**Issue by jan-schweiger** [mwilliamson/mammoth.js#414]
We would like to use Mammoth to offer a Word-Import for our technical file management platform. Unfortunately, we encountered a strange bug when testing some real-world Word files.

### Bug Description:
Here are two docx files, one with a formatted ordered list and one with a formatted unordered list:
1. [Test List.docx](https://github.com/user-attachments/files/16731707/Test.List.docx)
2. [Test List 2.docx](https://github.com/user-attachments/files/16731710/Test.List.2.docx)

Strangely, both lists are converted into paragraphs by Mammoth:
```
<p style="text-align: left">Part I</p><p style="text-align: left">Part II</p><p></p><p></p>
```

Regardless the reason, this definitely should not happen, as lists are a fundamental part of a Word document and thus should be converted correctly.

### Environment:
- Mammoth.js version 1.8.0
- Node.JS

### Support:
I know that my personal support of 100 dollars / issue is not really much. I really hope that Mammoth is soon stable enough for production. Then I can apply for a bigger sponsorship for Mammoth in my company.

**Comment by mwilliamson** [comment]
Could you provide an example of how you're invoking Mammoth? I've just tried your example documents, and for the first document I get:

```
<ol><li>Part I</li><li>Part II</li></ol>
```

and for the second:

```
<ul><li>Part I</li><li>Part II</li></ul>
```

**Comment by jan-schweiger** [comment]
You are right @mwilliamson. The issue is really caused by my setup. I implemented the following code for adding text-alignment.

When I remove the transform function from the options it works.

```
const transformParagraph = element => {
  const styleName = element.styleName ? element.styleName.toLowerCase() : "";
  if (styleName.includes('heading') || styleName.includes('list'))
    return element;

  if (element.alignment === "left")
    return {...element, styleName: "align-left" };
  else if (element.alignment === "center")
    return {...element, styleName: "align-center" };
  else if (element.alignment === "right")
    return {...element, styleName: "align-right" };
  else if (element.alignment === "both")
    return {...element, styleName: "align-justify" };

  return element;
}

const transformElement = element => {
        if (element.children) {
		const children = element.children.map(transformElement);
		element = {...element, children: children};
	}

	if (element.type === "paragraph")
		element = transformParagraph(element);
	return element;
}

const options = {
    includeEmbeddedStyleMap: true,
    transformDocument: transformElement,
    ignoreEmptyParagraphs: false,
    styleMap: [
      "u => u",
      "p[style-name='align-left'] => p[style='text-align: left']:fresh",
      "p[style-name='align-center'] => p[style='text-align: center']:fresh",
      "p[style-name='align-right'] => p[style='text-align: right']:fresh",
      "p[style-name='align-justify'] => p[style='text-align: justify']:fresh",
    ]
}

await mammoth.convertToHtml({ buffer }, options);
```

My guess is that I need to adjust the condition:
`if (styleName.includes('heading') || styleName.includes('list'))`

Thanks a lot for your help!

**Comment by jan-schweiger** [comment]
I now know why my code doesn't work. The lists have a style name in this docx `standard locker`.

```
const transformParagraph = element => {
  const styleName = element.styleName ? element.styleName.toLowerCase() : "";
  console.log(styleName);  // prints 'standard locker'
...
```

The question now is how I can rewrite me logic to fix it. Unfortunately, I cannot hard code `standard locker` as the styleName might be different for another docx.

My solution is simply returning the element if the alignment is "left". This fixes the bug for now. 
```
if (element.alignment === "left")
    return element;
```

Do you agree with this solution or do you think another approach would be right @mwilliamson?

**Comment by jan-schweiger** [comment]
In my opinion the following styleMap entry shouldn't even trigger, as this is a list element and not a paragraph.
```
      "p[style-name='align-left'] => p[style='text-align: left']:fresh",
```

**Comment by mwilliamson** [comment]
All list items are paragraphs in Word documents, so Mammoth treats them as such. If you want, you can define a style mapping for all lists with higher precedence (i.e. earlier in the style map) that will be used before other style mappings for paragraphs that potentially match.

**Comment by jan-schweiger** [comment]
Thank you a lot for your help @mwilliamson.

As element.type doesn't have a list type, I used element.numbering to identify if the element is a list item or not. Is this the correct way of identifying a list in a transform function?

```
const transformElement = element => {
    if (element.children) {
        const children = element.children.map(transformElement);
        element = {...element, children: children};
    }

if (element.type === "paragraph" && !element.numbering)  //  <--- Checking if its a list
     element = transformParagraph(element);
```

**Comment by jan-schweiger** [comment]
https://liberapay.com/mwilliamson/donate only supports recurring donations. Do you offer some methods for one-time donations as well @mwilliamson?

**Comment by jan-schweiger** [comment]
Ok, as advised on the Liberapay website, I initiated a £80 recurring payment and canceled it after the first transaction. I got a receipt so I think it worked. Please tell me if something went wrong.

Thanks a lot for your valuable support!!

**Comment by mwilliamson** [comment]
Thanks for the donation! It hasn't appeared yet, but I imagine it will do shortly. In case it's useful for future reference, Ko-fi can be used for one-off donations: https://ko-fi.com/mwilliamson

> As element.type doesn't have a list type, I used element.numbering to identify if the element is a list item or not. Is this the correct way of identifying a list in a transform function?

If I remember correctly, the numbering set on the paragraph object is the numbering that's been explicitly set for that paragraph in Word, meaning it won't be set if the numbering for a paragraph has been applied via a paragraph style only (which might be what you want, depending on your use case).

**Comment by jan-schweiger** [comment]
Great @mwilliamson, the donation wasn't charged from my account yet. I will wait until Tuesday next week. If it doesn't appear I will use https://ko-fi.com/mwilliamson and redo it.

Thanks again for you help.

**Comment by jan-schweiger** [comment]
The donation was charged from my bank account. If it hasn't worked, please let me know.
