### ISSUE TITLE
[Error] Error: Could not find file in options

### ISSUE THREAD

**Issue by elNapoli** [mwilliamson/mammoth.js#416]
Hello,

I'm trying to integrate Mammoth into my Supabase Edge function, but I haven't been successful. Here's the flow I'm using:

I'm sending a file from my website using formData to the Edge function. Both the upload and receipt of the file are successful.
I convert the file to an arrayBuffer and attempt to pass it to Mammoth, but I get the following error: **"[Error] Error: Could not find file in options".**

```javascript
app.post('/', async (c) => {
  const formData = await c.req.formData()
  const file = formData.get('file') as File
  const arrayBuffer = await file.arrayBuffer()
  const options = {
    styleMap: [
      'p[style-name=\'Section Title\'] => h1:fresh',
      'p[style-name=\'Subsection Title\'] => h2:fresh',
    ],
  }
  const response = await mammoth.convertToHtml({ arrayBuffer: arrayBuffer }, options)
  console.log(arrayBuffer)
  console.log(response)
  return new Response(JSON.stringify({}))
})
``` 

I've tried several solutions, but the issue persists. I'm not sure if the problem lies with the Mammoth library, the implementation, or if Deno server simply doesn't support Mammoth.

```javascript
const response = await mammoth.convertToHtml({ arrayBuffer: arrayBuffer })
``` 

```javascript
const response = await mammoth.convertToHtml({ arrayBuffer })
``` 

```javascript
const response = await mammoth.convertToHtml( arrayBuffer )
``` 
Best regards.

**Comment by mwilliamson** [comment]
Since you're not in a browser environment, you need to pass in a buffer, not an array buffer:

```
const response = await mammoth.convertToHtml({ buffer })
```

**Comment by mwilliamson** [comment]
Closing since this is hopefully resolved!
