### ISSUE TITLE
word files are not keeping the original format using mammoth viewer in angular 14

### ISSUE THREAD

**Issue by DikshaG001** [mwilliamson/mammoth.js#418]
Bug:

We are using  ngx-doc-viewer with viewer as  'mammoth viewer' in which formatting for tables and fonts are not being retained.The word files are not keeping the original format.The table content is there, but the table border are not shown. Also, Text highlight and font of the text in the word doc is not retained. I tried few workarounds using styleMap but it didn't work. 
I tried this:
but getting error while importing mammoth as Uncaught ReferenceError: process is not defined

<img width="1688" alt="Screenshot 2024-09-02 at 7 45 25 PM" src="https://github.com/user-attachments/assets/829e3c20-5c29-4d41-9f93-cc980d4ef22c">

const options = {
                styleMap: [
                    "u => em",
                    "table => table",
                    "tr => tr",
                    "td => td",
                    "th => th",
                    "td[style-name='Table Border'] => td:border",
                    "th[style-name='Table Border'] => th:border"
                ]
            };
    
            mammoth.convertToHtml({path: this.docURL}, options)
                .then(result => {
                    // Handle the result HTML as needed
                    console.log(result.value); // This is the HTML string
                })
                .catch(err => {
                    console.error(err);
                });
                
                
                This is the document i am using :
                
[DWSample1-DOC.docx](https://github.com/user-attachments/files/16838571/DWSample1-DOC.docx)

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the operating system and version
* if running in the browser:
  * the browser and version. -> Google Chrome Version 128.0.6613.86
  * whether you get the same issue in other browsers
* if running on node.js, the version you're using. --> V14

**Comment by DikshaG001** [comment]
i do want to retain Table borders for that i am trying to import mammoth library , but the whole page itself isn't loading and giving the above error.

**Comment by mwilliamson** [comment]
That's happening because you an invalid style map, and the code path for reporting invalid style maps used to require the util module. To fix it, you can either:
* Fix the style map
* Polyfill the util module
* Update lop to 0.4.2 which removes the dependency on the util module

**Comment by mwilliamson** [comment]
Closing in the absence of further information, hopefully the above has resolved the issue for you!
