### ISSUE TITLE
Convert Google Docs URL to HTML

### ISSUE THREAD

**Issue by itbk95** [mwilliamson/mammoth.js#420]
I currently have a link to a docx file from a Google Docs URL (for example: https://docs.google.com/document/d/{doc_id}/edit?usp=sharing), which is shared and can be viewed by anyone. 

Is there a way for me to simply input the link for conversion instead of having to download the docx file?

**Comment by mwilliamson** [comment]
Mammoth doesn't support this, but I assume Google's APIs allow the document to be exported as a docx, which can then be passed to Mammoth.
