### ISSUE TITLE
[support]  Added support for line centering, text background color, text color, text size 

### ISSUE THREAD

**Issue by waterbang** [mwilliamson/mammoth.js#427]
The implementation process mainly refers to jioho's [article](https://juejin.cn/post/7096120901837520932#heading-14)

The changes here are not ready to be submitted for PR, because this is not the result of my labor.

You can replace mammoth with the following packages for support.

```bash
npm i w2h
```

fork address:https://github.com/dweb-channel/mammoth.js

**Comment by mwilliamson** [comment]
Mammoth tries to preserve semantic information rather than attempting to exactly copy the formatting of the original document, so I think these changes are out of scope.

**Comment by waterbang** [comment]
That’s it, thank you for your reply
