### ISSUE TITLE
Custom-style-map doesn't affect built-in 'Quick Styles'

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#43]
I have the following in a text file:
```
p[style-name='Test Style'] => div.aside > h2:fresh
p[style-name='Test Style2'] => div.aside > p:fresh
p[style-name='Emphasis'] => div.aside > p:fresh
```
I'm running this from the command line using the '--style-map' flag pointed at the above file.  The first two style rules take affect as expected.  The third rule does nothing.  The same goes for any of the built-in (pre-defined) Quick Styles in Word.

**Comment by mwilliamson** [comment]
If Mammoth fails to map a style, it should leave a message to that effect. Do you get any such messages?

As I recall, the built-in styles are slightly odd in that they are all lowercase, despite being displayed in the UI as titlecase. In other words, the following might work:

```
p[style-name='emphasis'] => div.aside > p:fresh
```

**Comment by MCTaylor17** [comment]
Thank you for the quick response.  You are correct about case-sensitivity, but only for the various heading levels.  I looked at the XML and it looks like the Quick Styles I was having trouble with were w:type="character" rather than "paragraph".  This is solved by using `r[style-name='Emphasis']` rather than `p[style-name='Emphasis']`.

Here's a summary of my findings for the pre-defined Quick Styles in MS Word:
```
p-type:
Title
Subtitle
No Spacing
Quote
Intense Quote
List Paragraph
```
```
p-type & lowercase:
heading 1
heading 2
heading 3
heading 4
heading 5
heading 6
```
```
r-type:
Subtle Emphasis
Emphasis
Intense Emphasis
Strong
Subtle Reference
Intense Reference
Book Title
```

**Comment by mwilliamson** [comment]
Ah, I didn't realise that "Emphasis" was a character style. Glad you got it sorted.

> On the subject of case sensitivity, would it be difficult to make the style-maps case-insensitive?

It wouldn't be difficult, but I considered doing so before, and the fact that I didn't suggests that there was a snag. I *think* the reason is that style names are, in fact, case sensitive: it's possible to define two distinct styles with names that differ only in case (which makes Words mangling of the built-in names even more inconvenient). Having said that, I'm not sure why anybody would want to do this, so this might be an edge case worth ignoring for the sake of ease of use.

**Comment by MCTaylor17** [comment]
I notice that sax has a lowercase arg, but I think it only applies in "loose" mode.
 
**Sax documentation:** *lowercase - Boolean. If true, then lowercase tag names and attribute names in loose mode, rather than uppercasing them.*

It appears you're running it in "strict" mode which may be the snag you're referring to.
```
// Currently
var parser = sax.parser(true, {xmlns: true, position: false});
```
```
// Proposed
var parser = sax.parser(false, {xmlns: true, position: false, lowercase: true});
```
I'm not sure if that breaks anything.  My experience with XML is limited to basic parsing with Cheerio.js and SimpleXML (PHP).

Anyhow, it's worth noting the README.md makes several references to `p[style-name='Heading 1']`.  As mentioned in my previous comment, all of the heading levels appear to require lowercase to take affect.

**Comment by mwilliamson** [comment]
The style name is an attribute value, so I don't think configuring sax will make any difference: it's a question of how mammoth.js treats the value in its own code (and rightly so: the XML parser shouldn't change the casing of attribute values).

Thanks for the pointer about the examples in the README.

**Comment by MCTaylor17** [comment]
No worries.  Thank you for sharing this tool.  It's great!

**Comment by mwilliamson** [comment]
As of 0.3.18, style names are now case-insensitive. Thanks for the kind words!

**Comment by MCTaylor17** [comment]
Nicely done!
