### ISSUE TITLE
Cannot call method 'asUint8Array' of null

### ISSUE THREAD

**Issue by Z3roCoder** [mwilliamson/mammoth.js#45]
Always getting this error, no idea what I am doing wrong.

Installed it via "npm install mammoth -g"

Running it like "mammoth myWord.docx myHtml.html"

**Comment by mwilliamson** [comment]
Hello! I'll need a little more information to find out what's going on:

* What input file are you using?

* Does it work with an empty file created by Microsoft word?

* What stack trace do you get, if any?

* What version of node are you using?

* What OS and version are you on?

**Comment by mwilliamson** [comment]
Closing since issue #46 implies this has been resolved, and there's too little information to do any further investigation.
