### ISSUE TITLE
Empty "line breaks" are being ignored

### ISSUE THREAD

**Issue by JohnMcLear** [mwilliamson/mammoth.js#47]
I have a docx that has additional white space between line 1 and 2.  These spaces are lost during import..  Analysis of the document shows..

```
Line number 0
{ type: 'paragraph',
  children:
   [ { type: 'run',
       children: [Object],
       styleId: null,
       styleName: null,
       isBold: false,
       isUnderline: false,
       isItalic: false,
       verticalAlignment: 'baseline' } ],
  styleId: 'NormalWeb',
  styleName: 'Normal (Web)',
  numbering: null,
  alignment: 'both' }
{ type: 'run',
  children:
   [ { type: 'text',
       value: 'Lorem ipr id.' } ],
  styleId: null,
  styleName: null,
  isBold: false,
  isUnderline: false,
  isItalic: false,
  verticalAlignment: 'baseline' }
==========================


Line number 1
{ type: 'paragraph',
  children: [],
  styleId: 'NormalWeb',
  styleName: 'Normal (Web)',
  numbering: null,
  alignment: 'both' }
undefined
==========================

Line number 2
{ type: 'paragraph',
  children:
   [ { type: 'run',
       children: [Object],
       styleId: null,
       styleName: null,
       isBold: false,
       isUnderline: false,
       isItalic: false,
       verticalAlignment: 'baseline' } ],
  styleId: 'NormalWeb',
  styleName: 'Normal (Web)',
  numbering: null,
  alignment: 'both' }
{ type: 'run',   children:
   [ { type: 'text',
       value: 'Vestibulum nec iaculis sapien. Nunc malesuada convallis hendrerit. Maecenas et rutrum risus. Fusce ac tem
pus massa. Phasellus et quam feugiat, ultricies turpis et, accumsan odio. Class aptent taciti sociosqu ad litora torquen
t per conubia nostra, per inceptos himenaeos. Vivamus euismod vitae turpis eu auctor. Nam interdum nunc a purus pretium,
 vel maximus sapien volutpat. Aliquam nec metus quis nibh vulputate placerat sit amet a tellus. Ut luctus et nibh eu tin
cidunt. Aliquam ut nibh facilisis, vestibulum nisi sagittis, scelerisque erat. Nunc blandit purus neque, sit amet ornare
 sapien aliquet non. Vestibulum sapien turpis, tincidunt nec suscipit ut, dapibus nec eros.' } ],
  styleId: null,
  styleName: null,
  isBold: false,
  isUnderline: false,
  isItalic: false,
  verticalAlignment: 'baseline' }
==========================


Line number 3
{ type: 'paragraph',
  children: [],
  styleId: 'NormalWeb',
  styleName: 'Normal (Web)',
  numbering: null,
  alignment: 'both' }
undefined
==========================


Line number 4
{ type: 'paragraph',
  children:
   [ { type: 'run',
       children: [Object],
       styleId: null,
       styleName: null,
       isBold: false,
       isUnderline: false,
       isItalic: false,
       verticalAlignment: 'baseline' } ],
  styleId: 'NormalWeb',
  styleName: 'Normal (Web)',
  numbering: null,
  alignment: 'both' }
{ type: 'run',
  children:
   [ { type: 'text',
       value: 'Nulla blandit

```

Note the "undefined", something doesn't look right ;)

**Comment by mwilliamson** [comment]
If I've understood this correctly, then this is intentional behaviour: Mammoth will strip out empty paragraphs. Are you expected the empty paragraphs to be retained?

**Comment by JohnMcLear** [comment]
I guess it doesn't need to be default behaviour but it is the behaviour my client expects so we could put it under a flag?

**Comment by mwilliamson** [comment]
Sounds good. Something like `stripEmptyParagraphs: false`?

**Comment by JohnMcLear** [comment]
Yea or ``preserveParagraphs: true``

**Comment by blairq** [comment]
this worked for me :

            function transformElement(element) {
              if (element.children) {
                  if (element.children.length ==0 ){  //detect whitespace
                    element.children.push({
                    type: "text",
                    value: String.fromCharCode(20)    //insert not-so-well-tought whitespace paragraph
                    });
                  }
                  element.children.forEach(transformElement);
              };  
            }

**Comment by JohnMcLear** [comment]
@mwilliamson do you want me to contribute a PR for this?

**Comment by mwilliamson** [comment]
A pull request would be welcome, although I reckon there's a cleaner way to handle this case than a document transform. The best I've coming up with so far is:

* you can explicitly define on a style mapping whether to preserve empty paragraphs

* by passing `stripEmptyParagraphs: false` or whatever, paragraph mappings default to preserving empty paragraphs rather than stripping them if the choice is not explicitly set in the style mapping.

I should hopefully have time to take a look this weekend.

**Comment by JohnMcLear** [comment]
Okie's i will sit tight then.  I'm not in a rush and I'd rather it was done properly :)

On 15 May 2015 20:33, Michael Williamson <notifications@github.com> wrote:

A pull request would be welcome, although I reckon there's a cleaner way to handle this case than a document transform. The best I've coming up with so far is:

  *   you can explicitly define on a style mapping whether to preserve empty paragraphs

  *   by passing stripEmptyParagraphs: false or whatever, paragraph mappings default to preserving empty paragraphs rather than stripping them if the choice is not explicitly set in the style mapping.

I should hopefully have time to take a look this weekend.

**Comment by mwilliamson** [comment]
I've uploaded 0.3.19 to npm, which has a `ignoreEmptyParagraphs` option that default to `true`. Could you let me know if setting it to `false` works for you?

**Comment by JohnMcLear** [comment]
```


  var options = {
    styleMap: [
      "p[style-name='center'] => center",
      "p[style-name='Heading 1'] => p:fresh > h1:fresh",
      "p[style-name='Heading 2'] => p:fresh > h2:fresh",
      "p[style-name='Heading 3'] => p:fresh > h3:fresh",
      "p[style-name='Heading 4'] => p:fresh > h4:fresh",
      "p[style-name='Heading 5'] => p:fresh > h5:fresh",
      "p[style-name='Heading 6'] => p:fresh > h6:fresh"
    ],
    transformDocument: transformElement,
    ignoreEmptyParagraphs: false
  };
```
Would be correct syntax yes?

**Comment by mwilliamson** [comment]
Yup, that should do the trick.

**Comment by JohnMcLear** [comment]
Excellent, will test over the next 48 hours and let you know.,

**Comment by JohnMcLear** [comment]
Confirmed working :) Great job!  Thanks!

**Comment by mwilliamson** [comment]
Glad to hear it, thanks for confirming!

**Comment by VaibhavGupta982** [comment]
I am trying to convert Doc to HTML through mammoth java Lib. but it removes the spacing BW two paragraph. I found some suggestions "var options = {
    styleMap: [
      "p[style-name='center'] => center",
      "p[style-name='Heading 1'] => p:fresh > h1:fresh",
      "p[style-name='Heading 2'] => p:fresh > h2:fresh",
      "p[style-name='Heading 3'] => p:fresh > h3:fresh",
      "p[style-name='Heading 4'] => p:fresh > h4:fresh",
      "p[style-name='Heading 5'] => p:fresh > h5:fresh",
      "p[style-name='Heading 6'] => p:fresh > h6:fresh"
    ],
    transformDocument: transformElement,
    ignoreEmptyParagraphs: false
  }; "  and "DocumentConverter converter = new DocumentConverter().preserveEmptyParagraphs();"
to maintain the spaceing. but it is not working. can someone suggest me if I am doing something wrong.

![IMG-eab356043d4630e86bd757dd1dd28791-V](https://user-images.githubusercontent.com/51715975/120302780-d7e2cc00-c2eb-11eb-8eb0-874fb67f2ab6.jpg)

This is docx. 


![IMG-2ba3a043cd195639bd885156fa497c9e-V](https://user-images.githubusercontent.com/51715975/120302829-e204ca80-c2eb-11eb-81e5-1c4601e094d5.jpg)

This is html.
