### ISSUE TITLE
TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by jaceyshome** [mwilliamson/mammoth.js#48]
Hi Michael,

There is an error message showing up when I try to convert word 2013 doc to html :

  *TypeError: Cannot read property 'attributes' of undefined* 

on line var name = styleElement.first("w:name").attributes["w:val"]  

inside the function readStyleElement( ), of lib/style-reader.js, [line-number: 39].

As the return of the statement *styleElement.first("w:name")*  is undefined.

I guess the reason is the doc contains quite a lot of custom defined styles without naming. (The doc I used contains lots of images, custom styles and comments and so on.)

The way I fixed it is to make the style to 'Normal' if the element style is undefined:

var name;
try {
   name = styleElement.first("w:name").attributes["w:val"];
 }
catch(err){
   name = 'Normal';
}

Not sure whether this is the ideal solution.

**Comment by mwilliamson** [comment]
I normally prefer a check that prevents the error in the first place, so something like:

```javascript
function styleName(styleElement) {
    var nameElement = styleElement.first("w:name");
    return nameElement ? nameElement.attributes["w:val"] : null;
```

Also, I reckon the style name should be null by default. If you fancy submitting a pull request with the change and appropriate tests, that would be great, otherwise I'll take a look when I get a chance.

**Comment by jaceyshome** [comment]
Sure, I will do it once I get a chance. Thanks for the mommoth.js, it helps
a lot! I no longer need to copy and paste 100 pages of content line by line
to html.

**Comment by mwilliamson** [comment]
Thanks for the kind words! Always glad to hear that it's saving people time, I know from experience how tedious copying content can be.

**Comment by mwilliamson** [comment]
Fixed by pull request: https://github.com/mwilliamson/mammoth.js/pull/49
