### ISSUE TITLE
Can only convert.Docx file,.Doc will make an error

### ISSUE THREAD

**Issue by highsea** [mwilliamson/mammoth.js#53]
Can only convert.Docx file,.Doc will make an [error](http://images0.cnblogs.com/blog2015/531703/201507/101736556898993.png)

![](http://images0.cnblogs.com/blog2015/531703/201507/101736556898993.png)

**Comment by mwilliamson** [comment]
Mammoth only supports .docx files. If you want to convert a .doc using Mammoth, you'll need to convert it to a docx first.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/mwilliamson/mammoth.js/issues/2
