### ISSUE TITLE
Hyperlinks in documents that were originally created with word < 2010 are not supported

### ISSUE THREAD

**Issue by Andrewpk** [mwilliamson/mammoth.js#55]
I have not tested all options, but it seems if you have a document that was originally a .doc file, or possibly you've created a docx file using the compatibility pack on an older version of word and saved as .docx, the hyperlink shows up in the xml in a strange and unsupported format.

Here is an example of such a case:

``` xml
<w:r w:rsidR="00B47673" w:rsidRPr="00B47673">
    <w:rPr>
        <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
        <w:color w:val="0563C1"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
        <w:u w:val="single"/>
        <w:lang w:val="de-DE" w:eastAsia="en-US"/>
        <w:rPrChange w:id="11" w:author="author, awesome" w:date="2015-07-16T18:31:00Z">
            <w:rPr>
                <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
                <w:color w:val="0563C1"/>
                <w:sz w:val="22"/>
                <w:szCs w:val="22"/>
                <w:u w:val="single"/>
                <w:lang w:eastAsia="en-US"/>
            </w:rPr>
        </w:rPrChange>
    </w:rPr>
    <w:instrText xml:space="preserve"> HYPERLINK "http://someawesomelink.com" </w:instrText>
</w:r>
<w:r w:rsidR="00B47673" w:rsidRPr="00B47673">
<w:rPr>
    <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
    <w:color w:val="0563C1"/>
    <w:sz w:val="22"/>
    <w:szCs w:val="22"/>
    <w:u w:val="single"/>
    <w:lang w:eastAsia="en-US"/>
</w:rPr>
<w:fldChar w:fldCharType="separate"/>
</w:r>
<w:r w:rsidR="00B47673" w:rsidRPr="00B47673">
<w:rPr>
    <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
    <w:color w:val="0563C1"/>
    <w:sz w:val="22"/>
    <w:szCs w:val="22"/>
    <w:u w:val="single"/>
    <w:lang w:val="de-DE" w:eastAsia="en-US"/>
    <w:rPrChange w:id="12" w:author="author, awesome" w:date="2015-07-16T18:31:00Z">
        <w:rPr>
            <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>
            <w:color w:val="0563C1"/>
            <w:sz w:val="22"/>
            <w:szCs w:val="22"/>
            <w:u w:val="single"/>
            <w:lang w:eastAsia="en-US"/>
        </w:rPr>
    </w:rPrChange>
</w:rPr>
<w:t>http://someawesomelink.com</w:t>
</w:r>
```

As you can see, this format greatly differs from the current hyperlink tag structure and becomes somewhat more difficult to parse. Our current solution is to have document creators copy and paste document data from these broken documents into a brand new Word 2010+ docx file and use that (which works great).
I just wanted to raise awareness of this issue so that others could find a solution instead of potential "hyperlinks don't work!!!" issues being raised - when they definitely do.

**Comment by mwilliamson** [comment]
Thanks for the report! It seems like both types of hyperlinks are valid, which is unfortunate (for me) in that the type you've described is harder to handle. Glad that you've found a workaround, I'll let you know if I find time to at least investigate supporting both formats.

**Comment by mwilliamson** [comment]
This should be covered by #110, let me know if that's not the case.

**Comment by MCTaylor17** [comment]
I was just going to mention this issue.  Nice timing!
