### ISSUE TITLE
Handling w:tbl and converting them into html tables.

### ISSUE THREAD

**Issue by itsyogesh** [mwilliamson/mammoth.js#6]
After converting a few documents I found that the tables that are present in the word are not recognised. So I looked at the document.xml of a sample docx file but couldn't make out any patterns as to how does it represent the data. Here is 3*3 table in docx.

http://pastebin.com/vgSJkeWd

So is there any way of figuring out what data does it convey and converting them into normal html tables.

P.S. Thank you so much for the creating mammoth.js.

**Comment by ArneBeuth** [comment]
Could you give a brief description of how class support for tables should be implemented? How would you start?

**Comment by mwilliamson** [comment]
I'm not sure I can give an answer without knowing a little more about what you're trying to accomplish. Specifically, what does the source XML look like, and what HTML do you expect to produce?

**Comment by ArneBeuth** [comment]
I am trying to get the names of word table templates into class attributes in the resulting tags.
No further style details, just the names.

**Comment by mwilliamson** [comment]
Off the top of my head, you'd need to implement at least:

* Reading of table styles from `word/styles.xml` (`lib/docx/styles-reader.js`)
* Reading table styles for `w:tbl` elements when parsing `word/document.xml` and similar (`lib/docx/body-reader.js`)
* Allowing style maps to map table styles, which change the HTML applied by the style map in `lib/document-to-html.js`, similarly to how paragraphs and runs are handled.

**Comment by ArneOb** [comment]
Well, I was on the road when I somehow managed to get the class names of custom tables in word to the markup output using a stylemap. (This is really cool for me!)
The making was a bit wild, so for the moment I am just happy it is working. During this process I touched more than the files you mentioned. If someone is interested, I could write a more detailed description using the remarks I made.
