### ISSUE TITLE
Chart/Graph Converter

### ISSUE THREAD

**Issue by kyleknighted** [mwilliamson/mammoth.js#60]
First off... this is an awesome project! You've all done an amazing job with this!

The biggest hurdle I am facing right now is that the files I am provided have "Chart Areas". Is there any way to convert these areas to images?

Thanks again!

**Comment by shackep** [comment]
I agree that having a way to do this would be handy, but I can see how that would be out of the scope of Mammoth.

We are using a workaround where we convert charts into images. Word does not make this easy, so it involves copying and pasting the chart into a powerpoint presentation and then having powerpoint convert the chart into an image and finally saving that image into a file. We are looking at using images in our .docx file from the start to be able to fully take advantage of mammoth and speed up our publication workflow.

**Comment by mwilliamson** [comment]
Thanks for the kind words. Unfortunately, at the moment, there's no way to convert charts to images: the best approach right now would be Peter's suggestion of converting charts to images in the source document.

I'd certainly be willing to add support for the conversion if there was a sensible way to do it, but I suspect it would involve reimplementing Office's chart rendering engine, which is a rather larger job that I can handle! Having said that, if you want to send me an example document, I can check what's actually included in the document.

**Comment by shackep** [comment]
@kyleknighted An even better workaround that does not involve powerpoint is to save the word doc as HTML. It will export all of the charts as PNG files in a 'Name_of_your_document_files' directory. These will be higher resolution than the ones you would get using powerpoint. I still need to find an automated way to go back and replace the charts with the generated image in the .docx file. Once that is done Mammoth can do what it is best at.

**Comment by kyleknighted** [comment]
@shackep Doing "Export as HTML" is the current concept to get the image for the Chart Areas.

I'm not familiar enough with the inner workings of DOCX XML, so I wasn't sure how that data is converted to an image by Word and if it was possible to replicate within mammoth.

Honestly, this has gotten me so close to where I need to be, that having to export a DOCX to HTML on occasion to grab a single image is good enough for me!

**Comment by mwilliamson** [comment]
> I'm not familiar enough with the inner workings of DOCX XML, so I wasn't sure how that data is converted to an image by Word and if it was possible to replicate within mammoth.

It's probably not straightforward, but just in case Word is also storing an image that we can use, feel free to send me an example document and I can take a look.

**Comment by kyleknighted** [comment]
I need to get express permission from another team regarding sharing the document I am working on converting, yey for corporate legal policies! I will work on getting back to you first of the year. Large parts of different teams are on vacation over the previous and next weeks.

**Comment by mwilliamson** [comment]
No worries, whenever you can is fine. Feel free to send an example just to demonstrate the issue if you like, just so I'm sure I'm looking at the right thing.

**Comment by kyleknighted** [comment]
Here is an example of a graph that I have in a docx file.
Export as HTML converts it to an image, so I can technically use that, but just curious if there is anyway to do it within the mammoth.js conversion process.

[graph-example.docx](https://github.com/mwilliamson/mammoth.js/files/79045/graph-example.docx)

**Comment by mwilliamson** [comment]
Thanks for the file. Unfortunately, there doesn't seem to be a static image stored in the file that Mammoth can use. I think the only practical solution would be to use something like unoconv to generate images that Mammoth can use.

**Comment by kyleknighted** [comment]
Sounds fair to me. Glad we had a chance to look through the options within Mammoth. Closing this as there is no potential resolution within Mammoth.

Thanks again for the great project!
