### ISSUE TITLE
Shapes

### ISSUE THREAD

**Issue by basvdheijden** [mwilliamson/mammoth.js#63]
Is it correct that mammoth.js does not convert shapes? I noticed the shape is totally omitted from the output HTML when I convert a .docx file.

**Comment by mwilliamson** [comment]
Yes, I suspect Mammoth will ignore any shapes it finds. Unless the `docx` format also happens to store a PNG or other image that represents the shape, doing a conversion is rather hard.

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything particularly sensible that Mammoth can do with shapes.
