### ISSUE TITLE
nomnom is deprecated

### ISSUE THREAD

**Issue by kyleknighted** [mwilliamson/mammoth.js#64]
https://github.com/mwilliamson/mammoth.js/blob/0.3.29/bin/mammoth#L3

The [nomnom](https://github.com/harthur/nomnom) library has been deprecated and they recommend switching to [commander.js](https://github.com/tj/commander.js)

**Comment by mwilliamson** [comment]
Is this actually causing an issue or are you just noting that it's deprecated?

**Comment by mwilliamson** [comment]
I've replaced nomnom with argparse in `master`. I didn't think it was worth making a release just for that though: usage should be the same, but the help will be slightly different, and unrecognised options will now cause an error.

**Comment by kyleknighted** [comment]
Sorry for not getting back sooner - was on Christmas break.
I am not getting any errors from using nomnom, I was just making note that it was deprecated.

I agree it's not worth a release on its own. I was going to put in a PR when I got back, but it seems like you've already made the changes for the next release.
