### ISSUE TITLE
Support for the chrome filesystem api for packaged apps?

### ISSUE THREAD

**Issue by carlelieser** [mwilliamson/mammoth.js#68]
I would love to use mammoth.js in my chrome packaged app, but I'm having quite a lot of trouble since I'm not using a type="file" input. I'm using chrome.filesystem which allows the user to choose an entry when called just like the type="file" input tag. When I put the resulting entry into mammoth, it outputs nothing. Any ideas on how to get this to work? Thanks!

**Comment by mwilliamson** [comment]
I'm afraid I'm not familiar with Chrome packaged apps. Assuming you're using the browser version of Mammoth, then can you not pass in the file as an array buffer as normal?

**Comment by deathstar57** [comment]
Yes, I tried to pass the file entry as an array buffer, but to no avail.

**Comment by mwilliamson** [comment]
Can you post the actual code that you're using and the error you're getting? Are you sure that the file entry you're passing in is actually an array buffer?

**Comment by carlelieser** [comment]
The code for opening a file goes something like this.
Can you modify it to work with mammoth.js? That would be amazing thanks!
```javascript
chrome.fileSystem.chooseEntry(
 {
 type: 'openFile', accepts:[{
 extensions: ['docx']
 }] 
 }, 
 function(fileEntry) {
 fileEntry.file(function(file) {
 var reader = new FileReader();
 reader.onloadend = function(e) {
editor.setHTML(e.target.result);
 };
 reader.readAsText(file);
 });

});
```

The html from mammoth should be passed to the quilljs editor once its done reading.

**Comment by mwilliamson** [comment]
You need to load the file using `FileReader` as an array buffer i.e. use `readAsArrayBuffer` rather than `readAsText`. You can then pass the array buffer to Mammoth by passing an object with the `arrayBuffer` set to the array buffer. You can see an example of this behaviour in `browser-demo/demo.js`.

**Comment by mwilliamson** [comment]
Closing since I think Mammoth should already have support, let me know if that's not the case.

**Comment by carlelieser** [comment]
I did what you said and it returns an empty string :/

**Comment by mwilliamson** [comment]
Reported as working fine in #71.
