### ISSUE TITLE
Convert drawings to images

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#70]
Is it possible to convert MS Word's "shape" and "smart art" drawings into images?  If not, is it possible to provide a placeholder in the output to indicate the drawing's previous location within the document?

For reference, the alternative involves copying the drawing and using "paste special" to select a picture as the output.  See: [save drawing object in microsoft word 2007 as jpg](http://answers.microsoft.com/en-us/office/forum/office_2007-word/save-drawing-object-in-microsoft-word-2007-as-jpg/082987c2-e7f3-4fb3-9276-bdd908d2dcb6)

**Comment by MCTaylor17** [comment]
I'm sorry, this is directly related to #63

**Comment by mwilliamson** [comment]
Closing since, as you say, it's already covered in another issue.
