### ISSUE TITLE
HTML id attribute not W3C compliant

### ISSUE THREAD

**Issue by jensscheerlinck** [mwilliamson/mammoth.js#76]
Using the mammoth.js library to transform a .docx to valid (x)html, we found that the id attributes that are generated start with a digit instead of a letter, which means it is not considered as a valid xhtml document by W3C's validator.

For us, this does not pose an issue, but just raising it as a potential issue.

Thank you for the very useful tool!

**Comment by mwilliamson** [comment]
Thanks for the report! The behaviour of IDs will change slightly in 1.0, where IDs will be used from the original document without any prefix, although I'm not sure whether IDs starting with digits are allowed in docx files. In any case, you can set the `idPrefix` option to an appropriate string if this does turn out to cause an issue for you (currently undocumented, but will be properly supported in 1.0 with only a slight change in behaviour).

**Comment by mwilliamson** [comment]
IDs no longer have a random numeric prefix, and you can now set a prefix to generated IDs using the `idPrefix` option.
