### ISSUE TITLE
Support for altChunks

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#78]
I ran into trouble with a file that was generated via html-docx-js (on npm).   The output was blank with the following error: 

```js
  {
    "type": "warning",
    "message": "An unrecognised element was ignored: w:altChunk"
  }
```
After opening the file and manually saving-as I was able to perform the conversion.

**Comment by mwilliamson** [comment]
Thanks for the report. This is a duplicate of #71, so feel free to continue the conversation there.

**Comment by MCTaylor17** [comment]
I appologize, I searched issues for "altChunk" and didn't see that in the results.
