### ISSUE TITLE
Wrong Conversion: Table with connected Cells (colspans)

### ISSUE THREAD

**Issue by schorschroch** [mwilliamson/mammoth.js#81]
Dear Michael,
first of all thank you for your excellent work on mammoth!
I think, I found a bug on converting docx tables with connected table cells.
Is it possible to add **colspan** to the converted html **td** tags? 
This would help me really a lot.

I've uploaded a docx:
[Table with connected table cells.docx](https://github.com/mwilliamson/mammoth.js/files/236564/Table.with.connected.table.cells.docx)

And the result as png:
![image](https://cloud.githubusercontent.com/assets/4487271/14818216/32230fdc-0bbc-11e6-9ba8-73614a461b02.png)

And here the result as it should be:
![image](https://cloud.githubusercontent.com/assets/4487271/14818426/57f75e74-0bbd-11e6-9da2-91c4b5f33a53.png)

Thank you in advance for your help.

Regards,
Schorsch

**Comment by mwilliamson** [comment]
Thanks for the kind words, and also for providing an example. I'll take a look when I get a chance, but not sure when that'll be.

**Comment by mwilliamson** [comment]
Cells spanning multiple columns should be supported in 1.0.1. Let me know if not!

**Comment by schorschroch** [comment]
Hi Michael,
Cells spanning multiple columns works now like a charm.
Once more thank you very much!
Schorsch

**Comment by mwilliamson** [comment]
No problem, glad it works for you!

**Comment by schorschroch** [comment]
Dear Michael,
is it also possible to convert combined vertical table cells (html-tag **rowspan**)?
Then I think we would cover all table layout properties.

Again thank you.

Schorsch

**Comment by mwilliamson** [comment]
Cells spanning multiple rows are handled differently to columns in docx, so would require at least the same work again. I'll take a look if I get a chance, but not sure when that'll be.

**Comment by mwilliamson** [comment]
Logged as #82.

**Comment by mwilliamson** [comment]
Cells spanning multiple rows should be supported as of 1.0.2.
