### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by gingerbbm** [mwilliamson/mammoth.js#85]
Hi. I installed Node and then did "npm install mammoth" and that all seemed to work, but when I type "mammoth <anything>" at a Terminal prompt I get "command not found". Sorry to ask a n00b question, but what step am I missing here?

Thanks.

**Comment by mwilliamson** [comment]
If mammoth has been installed into a local `node_modules` directory, it can be found under `node_modules/.bin` i.e. something like `node_modules/.bin/mammoth`.

**Comment by gingerbbm** [comment]
Yep, that's what I thought, but:
`
MacBook-Pro:bin $ pwd
/Users/gingerbbm/node_modules/mammoth/bin
MacBook-Pro:bin $ mammoth
-bash: mammoth: command not found
`

**Comment by mwilliamson** [comment]
I'd normally expect to find the commands `.bin`, not `bin`. Do you have such a directory? Also, I believe you'll need to run `./mammoth` rather than `mammoth`.

**Comment by gingerbbm** [comment]
Well I don't have `.bin`. But `./mammoth` works! Thanks for your help.

**Comment by mwilliamson** [comment]
Glad you got it working.

**Comment by Coreyp319** [comment]
For those that come after me, prefix "mammoth" with  **node_modules/.bin/** so that it appears like: 

node_modules/.bin/mammoth [input file]  [output file] etc.
