### ISSUE TITLE
Exceptions in `mammoth.images.imgElement` callback are too easily ignored

### ISSUE THREAD

**Issue by whoeverest** [mwilliamson/mammoth.js#86]
Here's the minimal code to reproduce the issue:

```
var mammoth = require('mammoth');

var options = {
  convertImage: mammoth.images.imgElement(function(element) {    
    return element.read().then(function(imageBuffer) {
      throw new Error("this won't appear anywhere");
    });
  })
};

mammoth.convertToHtml({ path: './doc-with-image.docx' }, options).then(function(html) {
  console.log(html.value);
})
```

The `imgElement` returns a rejected promise and the exception is ignored, resulting in a missing `<img>` tag in the html.

**Comment by whoeverest** [comment]
From what I can tell, this line in `lib/images.js` causes the problem:

`promises.when(func(element)).then(function(result) { ... }`

which is equivalent to:

```
Promise.resolve(function() { throw new Error(); }).then(function(res) {
  console.log('no error');
})
```

which prints 'no error'. Maybe it's a Bluebird issue?

**Comment by mwilliamson** [comment]
Mammoth handles errors in image conversion by converting them into warnings, which should be available on the `messages` property of the result. Is that not the case for you?

**Comment by whoeverest** [comment]
You're right, it does appear in `messages` as a warning. 

```
{ value: '...',
  messages: [ { type: 'warning', message: 'this won\'t appear anywhere' } ] }
```

Should all exception be handled this way, though? First, because it's easy to overlook that an error has occurred and second, because the stack trace is lost.

Just wondering if there's a way to separate real serious exceptions from the "can't convert node" case?

**Comment by mwilliamson** [comment]
Hmm, doing a best-effort conversion is often desirable, but I can see why you might want to fail-fast. Might the best approach be an adding an option to toggle the behaviour?

As for the stack trace: it's probably worth putting the original error onto the message.

Also, it might be worth generating message with type `error` rather than `warning`, and providing a quick way of getting just the errors rather than all messages.

**Comment by whoeverest** [comment]
I'm okay with tagging them as errors and providing a stack trace. Having a "fail fast on errors" option available also sounds good.

**Comment by mwilliamson** [comment]
If you're happy with marking them as errors and providing a stack trace, let's go with that. Not sure when I'll get a chance to implement it, so feel free to submit a pull request if you fancy it.

**Comment by whoeverest** [comment]
I submitted a PR, but I'm not completely satisfied yet. :-) It's still too easy miss the error when it occurs.

Maybe add `console.error(exception.stack)` in `results.error`? It will print the exception, but won't break the conversions process. We'd do this by default, no flags.

**Comment by mwilliamson** [comment]
I'm not keen on spitting things out to the console, especially since we are providing a way for the user to detect the errors rather than swallowing them silently.

**Comment by mwilliamson** [comment]
I've merged in the changes from your pull request with a couple of tweaks.
