### ISSUE TITLE
Word 2002 Corrupted Headers

### ISSUE THREAD

**Issue by MCTaylor17** [mwilliamson/mammoth.js#90]
See: [Text that was formatted with a paragraph style is formatted with a character style when you paste the text to another document in Word 2003 or in Word 2002](https://support.microsoft.com/en-us/kb/902064)

I have encountered this with multiple documents.  Unfortunately, it's not as simple as using the styleMap since the styles are run types, not paragraph.  That means the following:

    r[style-name='Heading 2 Char'] => h2:fresh

... will unwrap the parent paragraph allowing any siblings to spill out.  In my case, this was quite nasty because it treated new paragraphs as line-breaks so there were `<br>` tags and orphaned text everywhere.

My temporary solution is to use the styleMap to apply the following: 

    r[style-name='Heading 2 Char'] => span.heading2

... and target the class to move it and wrap it (`<h2>` in this example) after the fact.

**Comment by mwilliamson** [comment]
Could you provide a minimal example document? I think a style map might be able to solve this, but it's difficult to say without actually seeing an example.

**Comment by mwilliamson** [comment]
Closing since I don't think I can do anything helpful without an example. Feel free to post an example document and I'll take a look.
