### ISSUE TITLE
embed tag convert to an img tag

### ISSUE THREAD

**Issue by occasl** [mwilliamson/mammoth.js#91]
I have a word document that has images embed in it as follows:

```
<embed src="chips.jpg">
```

Is there a way I could reference the associated file that's in the the same directory as the Word document that is being converted to HTML so that it would be translated as:

```
<img src="chips.jpg">
```

Thanks,
Lou

**Comment by mwilliamson** [comment]
You mean that embed code is in the document as raw text? Or that it's present in the XML?

Could you provide a minimal example document with the expected HTML output?

**Comment by occasl** [comment]
Yes, the former. The word document literally has that `<embed>` tag but upon running mammoth against it, it doesn't pull in the image.  My thought is just copy the image to the output directory and change the the tag to an `<img>` tag so that you see the image in place of that tag.

**Comment by mwilliamson** [comment]
You could try using a document transform, or just inspecting the HTML after the conversion. I'm not really sure there's much beyond the existing document transform support that Mammoth can provide since this is quite a specific use case.

**Comment by occasl** [comment]
Ok, thanks again. I'm using cheerio for this too but will take a look at transforms as time permits.
