### ISSUE TITLE
How can I retain the numbering for headings?

### ISSUE THREAD

**Issue by occasl** [mwilliamson/mammoth.js#92]
I have a doc that is using numbers for each type of heading and subheadings. Those numbers are being stripped; how can I prevent that?

e.g.,

1 Heading
1.1 Heading 2
1.1.1 Heading 3
...

**Comment by mwilliamson** [comment]
Could you provide a minimal example document, and the expected HTML?

Assuming that the headings are numbered using the paragraph options in Word (i.e. not manually typed in) and that you'd expect those numbers to be present as text in HTML (i.e. not as part of a `<ol>`), then the only way you'd be able to do this at the moment is with a document transform: you'd have to walk the tree of elements, and prepend the relevant numbers whenever you come across a paragraph with the relevant heading type (and keep track of the counts).

**Comment by occasl** [comment]
Yes, exactly. The numbering is just part of the Word "numbering" feature so the numbers aren't actually part of the doc.

I ended up using [cheerio](https://github.com/cheeriojs/cheerio) to walk the HTML and add them during post processing. It's the only way I could think to do it.

**Comment by mwilliamson** [comment]
In which case, as I say, document transforms are probably your best bet, although I don't think it really adds anything if you already have code to add them to the generated HTML.

**Comment by occasl** [comment]
Ok, I'll take a look at those as well, but I was just a little anxious using them since there's the caveat that they are unstable.

**Comment by mwilliamson** [comment]
Indeed they are, although that shouldn't be a problem if you pin the version you're using. Modifying the HTML after the fact is probably about the same amount of work, and doesn't rely on what is essentially the internals of Mammoth, so on balance feels like the better option.
