### ISSUE TITLE
Ability to add table borders and padding

### ISSUE THREAD

**Issue by occasl** [mwilliamson/mammoth.js#93]
I'm finding that I had to alter the code a little to get table borders and some padding. 

e.g., Line 223-5 from document-to-html.js

```JavaScript
    function convertTable(element, messages) {
        return wrapChildrenInFreshElement(element, "table border=\"1\" cellpadding=10", messages);
    }
```

Converting tables with no borders doesn't provide a lot of value. Is there a way that we could override this with some style?

**Comment by mwilliamson** [comment]
Mammoth intentionally leaves off such attributes so that you can style the HTML using CSS. Does that not work for your case?

**Comment by occasl** [comment]
Got it. I'll do it that way. Thanks!
