### ISSUE TITLE
Support for "List Continue" Styles

### ISSUE THREAD

**Issue by ryanfitzer** [mwilliamson/mammoth.js#96]
Using [example-list-continue.docx](https://github.com/mwilliamson/mammoth.js/files/494503/example-list-continue.docx) and the following style map:

```python
p[style-name='List Number'] => ol > li:fresh
p[style-name='List Continue'] => ol > li p
```

I get the following HTML:
 
```html
<ol>
  <li>Item One</li>
  <li>Item Two</li>
  <li>Item ThreeThis is a “List Continue” style</li>
  <li>Item Four</li>
  <li>Item Five</li>
</ol>
```

I was expecting a paragraph element to be nested in the list item:
```html
<ol>
  <li>Item One</li>
  <li>Item Two</li>
  <li>Item Three
    <p>This is a “List Continue” style</p>
  </li>
  <li>Item Four</li>
  <li>Item Five</li>
</ol>
```

What would be the correct style map syntax to use in this case?

I'm running OS X 10.10.5 with Node.js v6.3.0.

**Comment by mwilliamson** [comment]
I think you're missing a `>` between `li` and `p`:

```python
p[style-name='List Number'] => ol > li:fresh
p[style-name='List Continue'] => ol > li > p
```

Although Mammoth should really produce an error for your style map, so
that's a bug.

**Comment by mwilliamson** [comment]
The latest version (1.2.3) should correctly produce warnings for these sorts of style mappings.

**Comment by ryanfitzer** [comment]
Thanks for the quick response! You were correct. Not sure how I missed that. I'm parsing a 170 page document and mammoth has been such a great tool. Thanks for all your hard work.

**Comment by mwilliamson** [comment]
Glad to hear it's useful!
