### ISSUE TITLE
Allow access to Word field codes via instrText

### ISSUE THREAD

**Issue by rmzelle** [mwilliamson/mammoth.js#98]
I'd like to use mammoth.js to extract bibliographic metadata from references put in with the Zotero reference manager. These references are usually encoded as fields, and their field code looks like:

```
<w:r>
    <w:instrText xml:space="preserve">
        ADDIN ZOTERO_ITEM CSL_CITATION {"citationID":"7kotdh7ut","properties":{"formattedCitation":"(Beese, Negishi, &amp; Levin, 2009)","plainCitation":"(Beese, Negishi, &amp; Levin,
        2009)"},"citationItems":[{"id":78,"uris":["http://zotero.org/users/1031436/items/4WATGD54"],"uri":["http://zotero.org/users/1031436/items/4WATGD54"],"itemData":{"id":78,"type":"article-journal","title":"Identification of Positive Regulators of the
        Yeast Fps1 Glycerol Channel","container-title":"PLoS Genet","page":"e1000738","volume":"5","issue":"11","source":"PLoS Genet","abstract":"Author Summary\nWhen challenged by changes in extracellular osmolarity, many fungal species regulate their
        intracellular glycerol concentration to modulate their internal osmotic pressure. Maintenance of osmotic homeostasis prevents either cellular collapse under hyper-osmotic stress or cell rupture under hypo-osmotic stress. In baker's yeast, the Fps1
        glycerol channel functions as the main vent for glycerol. Proper regulation of Fps1 is critical to the maintenance of osmotic homeostasis. In this study, we identify a pair of proteins (Rgc1 and Rgc2) that function as positive regulators of Fps1
        activity. Their absence results in hyper-accumulation of glycerol and consequent cell lysis due to impaired Fps1 channel activity. Additionally, we found that these glycerol channel regulators function between the Hog1 (High Osmolarity Glycerol
        response) signaling kinase and Fps1, defining a signaling pathway for control of glycerol efflux. Because members of the Rgc1/2 family are found among pathogenic fungal species, but not in humans, they represent potentially attractive targets for
        antifungal drug development.","URL":"http://dx.doi.org/10.1371/journal.pgen.1000738","DOI":"10.1371/journal.pgen.1000738","journalAbbreviation":"PLoS Genet","author":[{"family":"Beese","given":"Sara
        E."},{"family":"Negishi","given":"Takahiro"},{"family":"Levin","given":"David
        E."}],"issued":{"date-parts":[["2009",11,26]]},"accessed":{"date-parts":[["2011",10,21]]}}}],"schema":"https://github.com/citation-style-language/schema/raw/master/csl-citation.json"}
    </w:instrText>
</w:r>
```

Example file: [zotero-cit.docx](https://github.com/mwilliamson/mammoth.js/files/502858/zotero-cit.docx)

Is there any way to target `instrText`? When I try creating a style map for it, I get the following message:

> Did not understand this style mapping, so ignored it: instrText => div.csl Error was at character number 1: Expected element type but got identifier "instrText"

If I could monkey patch this in a personal copy that would be fine too, but I couldn't find any places in the code where `instrText` is explicitly ignored, and I couldn't figure out what to change.

(followup of https://github.com/mwilliamson/mammoth.js/issues/8#issuecomment-250647081)

**Comment by mwilliamson** [comment]
Any unrecognised elements are ignored, so instrText is never explicitly
ignored (hence the message). Can you use a separate paragraph or run
style for the fields?

**Comment by rmzelle** [comment]
I was planning to build a website where people can upload their own Word files, and requiring them to reformat their documents by hand before upload would be too complicated. Maybe I could use mammoth's document transform option, though (https://github.com/mwilliamson/mammoth.js#document-transforms). Do you know if that recognizes instrText?

Alternatively, it looks like I could add an xmlElementReaders handler for instrText at https://github.com/mwilliamson/mammoth.js/blob/206843c9f701a3e62ba7c45b07173471b6309870/lib/docx/body-reader.js#L105.

**Comment by mwilliamson** [comment]
Mammoth doesn't recognise instrText at all, so can't be accessed in a
document transform.

**Comment by rmzelle** [comment]
I know I'm not really using mammoth.js for its intended purpose, but for the curious:

I solved this for myself (https://github.com/rmzelle/ref-extractor/) by extending the variable "xmlElementReaders" to recognize `instrText` elements, and exporting the contents of each field to a global array variable: https://github.com/rmzelle/mammoth.js/commit/77bcac57a2f4f5095f7e8ae71419863dbdb3bc26#diff-68b60b2443cf3be90e7e7223aaf3d383

It requires me to use a customized version of mammoth.js, it seemed the easiest way to allow me to:

a) access the content of `instrText` elements
b) post-process the content of each `instrText` element
c) ignore any other content in the Word document

**Comment by mwilliamson** [comment]
I think there's two things here that would help you:

1) Being able to use the parser directly

2) Being able to extend the parser to handle different elements

Does that sound about right to you?

Exposing the parser so it can be used more easily without having to unzip the file should be straightforward, although it would likely be without any guarantees of stability between stability.

Adding in points of extensibility to parse other elements is reasonably straightforward to code, but might need a bit of thought around how to design the API.

Having said all of that, am I right in thinking that the only part of the document you're interested in is the `instrText` elements? In which case, I'm not sure that using Mammoth helps you, since you could just read `word/document.xml` out of the archive and search for all `w:instrText` elements. The only reason I can think that might give a different result is cases where Mammoth ignores certain elements, such as deletions.

**Comment by rmzelle** [comment]
> Having said all of that, am I right in thinking that the only part of the document you're interested in is the instrText elements?

Yes. (and I understand that that doesn't really align with the main purpose of mammoth.js)

> In which case, I'm not sure that using Mammoth helps you, since you could just read word/document.xml out of the archive and search for all w:instrText elements.

Yes, I can probably just unzip the documents and parse the XML file with more general JavaScript code. Feel free to close this issue (I'll keep using my modified copy of mammoth.js for now since it works, but I take your point).

**Comment by mwilliamson** [comment]
Okey doke, closing the issue.
