### ISSUE TITLE
Conversion replaces some spaces and few other characters with unicode characters

### ISSUE THREAD

**Issue by thammadi** [mwilliamson/mammoth.js#99]
I'm running mammoth with Node on Windows 7: "mammoth No.docx No.html"

When converting the attached document, some characters like spaces and '–' are getting converted into unicode characters like 'Â', 'â€“' etc.

[No.docx](https://github.com/mwilliamson/mammoth.js/files/517437/No.docx)

e.g: (text from docx)
**No. 6, 1901** converts to **No.Â 6, 1901**
**sections 1–183U** converts to **sectionsÂ 1â€“183U**

**Comment by mwilliamson** [comment]
The output file is UTF8 encoded, so you need to make sure that the resulting HTML is being viewed with a UTF8 encoding, for instance by including:

    <meta charset="utf-8">

in your final HTML document.

**Comment by thammadi** [comment]
yep, that fixes it, Thanks!

**Comment by mwilliamson** [comment]
Glad you got it sorted.
